### ISSUE TITLE
If bisulfite conversion rate is relatively low (90%), will it affect bismark mapping ratio ?

### ISSUE THREAD

**Issue by lss1227** [FelixKrueger/Bismark#110]
Hi, our lab have done WGBS on a kind of monkey. But the conversion rate of 3 sample is relatively low (only about 90%, the others are over 99%). Well 90% and 99% is from observation of fastqc report because the amount of our spike-in lambda is too little while doing experiments. This results in that the conversion rate of lambda cannot be used to present the conversion rate of our samples.
After doing mapping with the newest version of bismark, I find that the mapping ratio of low conversion rate samples is only about 56% while the mapping ratio of samples with normal conversion rate is about 80%. The parameter is the same for all samples.  
I know the reference of monkey is not quite as finished as the human or mouse genomes are, I still use default --score_min. According to the principle of bismark, I don't think convertion rate will affect mapping ratio. 
I also tried your suggestion --score_min L,0,-0.4 to realign **unmapped reads**, the mapping ratio of unmapped reads is about 38%. But the average methylation of CHH/CHG  is high, which is about 50%.
 It  makes me feel that --score_min can stop incomplete converted reads from mapping to reference.
(It seems that there is no contamination during experiments.)
Thank you for any comments.

**Comment by FelixKrueger** [comment]
Just very generally, initial FastQC reports are not necessarily a good way of assessing the bisulfite conversion rate because it operates on the raw FastQ reads which may still carry contaminants, reads that don't map etc. Instead I would suggest you look at the non-CG methylation in the M-bias plots.

> I know the reference of monkey is not quite as finished as the human or mouse genomes are, I still use default --score_min. According to the principle of bismark, I don't think convertion rate will affect mapping ratio.

It is correct that the _in-silico_ conversion should map sequences at the same rate irrespective of its methylation state. My guess is that these samples also contain some contamination, or maybe there was something dodgy about the sequencing run that resulted in more errors in the affected samples? You could try to run Fastq_Screen on the data to determine whether there are any contaminants. If you wanted you can just send me ~100K sequences of the samples to my email address (gzipped please) and I could quickly check this for you.

>I also tried your suggestion --score_min L,0,-0.4 to realign unmapped reads, the mapping ratio of unmapped reads is about 38%. But the average methylation of CHH/CHG is high, which is about 50%.
It makes me feel that --score_min can stop incomplete converted reads from mapping to reference.

This is a very puzzling result. Normally you see you ~50% methylation either at imprinted loci where one allele is fully methylated but the other one isn't, or whenever sequences are (mis-)aligning to an incorrect place in the genome, at which point you will perform more or less random calls for C positions and end up with 50% on average. 
Do the reads all align to a very confined region in the genome, so maybe they all came from the same class or repeats (which happened to just not map with in the default setting)? This could again be some contaminant, e.g. human, DNA, possibly even not even bisulfite converted, that aligns to a subfraction of your monkey genome. If this were the case you might need to pre-clean the data by getting rid of human contamination by aligning to the human genome first, and then using the leftover reads for your monkey genome. Again, I am happy to run a few tests here where everything is already set up.
