### ISSUE TITLE
Sometimes Bismark（0.16.3） break off

### ISSUE THREAD

**Issue by hmyh1202** [FelixKrueger/Bismark#113]
My parameter for single cell BS data:  bismark -p 4 -N 1 -un --non_directional -bowtie2 -path_to_bowtie bowtie2-2.2.3/ -bam -samtools_path samtools  -o outdir  Genome_INDEX_dir -1 Sample1_P_R1.fq.gz -2 Sample1_P_R2.fq.gz
 The log is as below:
FastQ format assumed (by default)
Each Bowtie 2 instance is going to be run with 4 threads. Please monitor performance closely and tune down if needed!
**1.  .o logfile**
chr chr1 (195471971 bp)
chr chr10 (130694993 bp)
chr chr11 (122082543 bp)
chr chr12 (120129022 bp)
chr chr13 (120421639 bp)
chr chr14 (124902244 bp)
chr chr15 (104043685 bp)
chr chr16 (98207768 bp)
chr chr17 (94987271 bp)
chr chr18 (90702639 bp)
chr chr19 (61431566 bp)
chr chr2 (182113224 bp)
chr chr3 (160039680 bp)
chr chr4 (156508116 bp)
chr chr5 (151834684 bp)
chr chr6 (149736546 bp)
chr chr7 (145441459 bp)
chr chr8 (129401213 bp)
chr chr9 (124595110 bp)
chr chrMT (16299 bp)
chr chrX (171031299 bp)
**2. the .e log file ended with :**
Now starting a Bowtie 2 paired-end alignment for CTread1GAread2CTgenome (reading in sequences from /annoroad/data1/bioinf
Found first alignment:
HISEQ:319:CA5H0ANXX:7:1101:1385:2000_1:N:0:CTAGTTA/1    77      *       0       0       *       *       0       0       A
HISEQ:319:CA5H0ANXX:7:1101:1385:2000_2:N:0:CTAGTTA/2    141     *       0       0       *       *       0       0       C
Now starting a Bowtie 2 paired-end alignment for GAread1CTread2GAgenome (reading in sequences from /annoroad/data1/bioinf
Found first alignment:
HISEQ:319:CA5H0ANXX:7:1101:1385:2000_1:N:0:CTAGTTA/1    77      *       0       0       *       *       0       0       A
HISEQ:319:CA5H0ANXX:7:1101:1385:2000_2:N:0:CTAGTTA/2    141     *       0       0       *       *       0       0       T
Now starting a Bowtie 2 paired-end alignment for GAread1CTread2CTgenome (reading in sequences from /annoroad/data1/bioinf
Found first alignment:
HISEQ:319:CA5H0ANXX:7:1101:1385:2000_1:N:0:CTAGTTA/1    77      *       0       0       *       *       0       0       A
HISEQ:319:CA5H0ANXX:7:1101:1385:2000_2:N:0:CTAGTTA/2    141     *       0       0       *       *       0       0       T
Now starting a Bowtie 2 paired-end alignment for CTread1GAread2GAgenome (reading in sequences from /data/....

**Comment by hmyh1202** [comment]
When the reads was converted to C-T / G-A Reads files， the bismark  immediately break off

**Comment by FelixKrueger** [comment]
Hi hymn,

Apologies for the late reply. I'm afraid from the above text I can't exactly see what the actual problem is, does the process get killed, maybe by your cluster queuing system? How much memory do you have on your system, and which genome are you aligning to? (non-directional alignments may take top to 20GB or so of RAM...). Could you please attach or send via email the entire error log from start to end? 

Just a few general comments:
- can you please update to the latest version of Bismark (v0.18.3) here: https://github.com/FelixKrueger/Bismark/releases

- I would probably change the command
```
bismark -p 4 -N 1 -un --non_directional -bowtie2 -path_to_bowtie bowtie2-2.2.3/ -bam -samtools_path samtools -o outdir Genome_INDEX_dir -1 Sample1_P_R1.fq.gz -2 Sample1_P_R2.fq.gz
```
to:
```
bismark -un --non_directional -path_to_bowtie bowtie2-2.2.3/ -o outdir Genome_INDEX_dir -1 Sample1_P_R1.fq.gz -2 Sample1_P_R2.fq.gz
```

because `-p 4` takes quite a few extra cores and doesn't speed up the alignment process very much (a single file will still need around 20 cores and ~20GB of RAM). If you have a lot of resources you could look into using `--parallel` but first we need to figure out why your run doesn't work at all. `-N 1` uses more memory, takes longer and is normally not necessary. I have left out all the options that are default anyway. 

Let me know how you get on. Best wishes, Felix
