### ISSUE TITLE
can Bismark be compatible with  hisat2 and sambamba for both alignment and sam/bam manipulatation 

### ISSUE THREAD

**Issue by likelet** [FelixKrueger/Bismark#114]
using bowtie2 and samtools is relative in low efficiency when comparing with the two tools listed above  . I open this issue for suggesting that authors may have a try to support hisat2 and sambamba in Bismarck.  
thanks .

**Comment by FelixKrueger** [comment]
Hi likelet, while it is in theory possible to implement HISAT2 as an aligner into Bismark I reckon that it would be a substantial amount of work. We can certainly keep this in mind for when we've got nothing else to do :) Would you be interested in this (and the sambamba manipulation) mainly for speed increase reasons or rather because of spliced alignments?

**Comment by likelet** [comment]
Hi Felix ,thanks for your response. Bismark is a well-designed mapping and analysis tool for BS-seq data, which I keep on using it for years. Currently, I mainly concern about it's mapping speed especially deal with WGBS data (since there are hundreds of samples at hand, and  run sample individually is really time consuming).  Besides, splicing alignment is not taken in consideration at present.
