### ISSUE TITLE
bismark2bedGraph fails

### ISSUE THREAD

**Issue by ahak** [FelixKrueger/Bismark#118]
I'm trying to run bismark2bedGraph in CHG context with the command:
    bismark2bedGraph --zero_based --CX --output oname CHG_context_input_pe.txt.gz

And get the following error:
*Sorting input file CHG_context_input_pe.txt.gz.chrname.methXtractor.temp by positions (using -S of 2G)
Use of uninitialized value $pos in string ne at /path/to/bismark/bismark_v0.18.1/bismark2bedGraph line 460, <$ifh> line 879147.
Missing (+/-) methylation call at /path/to/bismark/bismark_v0.18.1/bismark2bedGraph line 519, <$ifh> line 879147.
	main::validate_methylation_call(undef, undef) called at /path/to/bismark/bismark_v0.18.1/bismark2bedGraph line 465*

The line 879147 contains:
**DRR_num.various:identifiers_length=101	-	chr18	63936299	x**

**Comment by FelixKrueger** [comment]
Hmm, there seems to be a problem with the file format. Did you do anything to the CHG context files before feeding them to `bismark2bedGraph` such as merging, copying them between different platforms (such as Mac, Windows and Linux)? If that were the case either `dos2unix CHG_context_input_pe.txt.gz` or `mac2unix CHG_context_input_pe.txt.gz` might help solve this problem.

If you can't get this sorted could you send me the CHG file to take a look? Best, Felix

**Comment by ahak** [comment]
Thanks for the prompt answer. The files were not modified, neither transfered within platforms(only from linux to linux).
Here is the link to the file:
https://www.dropbox.com/s/x410gfnjbdlewu1/CHG_context_DRR016652_pe.txt.gz
Thanks.

**Comment by FelixKrueger** [comment]
Hi ahak,

I just ran  the command

```
bismark2bedGraph CHG_context_DRR016652_pe.txt.gz -o out
```

and it ran to completion just fine... I was using version 0.18.2 but I don't think there was any change from 0.18.1. So hmm, not quite sure what to suggest now. Maybe try again?

**Comment by FelixKrueger** [comment]
PS: It completed equally fine with `--zero_based` specified.

**Comment by ahak** [comment]
Hi FelixKrueger,

I've tried without ```--zero_based``` and now I get:

_Died at /path/to/bismark/bismark_v0.18.1/bismark2bedGraph line 486._

Thanks for checking. I'll post here once I figure out what causes the problems.

**Comment by FelixKrueger** [comment]
This is a little odd, *line 586* merely closes the filehandle from the in-file. This should only happen once the file has been processed entirely, and you could comment this line out if you wanted to. 

In case this is a `gzip`-stream issue you could also `gunzip` your CHG file to start with then then run `bismark2bedGraph` again.

**Comment by svrever** [comment]
Hi,
I have a similar, but different issue with bismark 2bedGraph. I was trying to convert the CHH context file to bedGraph, which resulted in an error:

$ bismark2bedGraph --CX --scaffolds --buffer_size 90% -o out1_n-sort.bedGraph.gz CHH_context_MS_XL1-3_combined_n-sort.txt.gz

The genome of interest was specified to contain gazillions of chromosomes or scaffolds. Sorting everything in memory instead of writing out individual chromosome files ...
Sorting input file CHH_context_MS_XL1-3_combined_n-sort.txt.gz by positions (using -S of 90%)
sort: write failed: .//sort2emEOv: Protocol error
Died at /media/sf_E_DRIVE/BISMARK_PROGRAM_FILES/bismark_v0.18.1/bismark2bedGraph line 486.
needLargeMem: trying to allocate 0 bytes (limit: 100000000000)

the input file I was using is quite large (> 50G), and the genome I am working with has more then 400,000 scaffolds.  Allocated memory sise (90%) was about 40G. The script was running for about 12 hours before crush, and total size of temporary leftover files on the disk is about 450G.  Can this be helped?
Thanks,
Sergei

**Comment by FelixKrueger** [comment]
Hi Sergei,

I have not heard of this error before to be honest. A bit of googling the error shows that `sort: write failed: .` are fairly common, also `needLargeMem: trying to allocate 0 bytes (limit: 100000000000)` shows up quite often. I haven't looked at the responses in various forums in detail yet, but it seems to suggest that some input files (or temp files?) are empty, would that be a possibility?

I'm afraid I can only just suggest a few things I would try out now, maybe apart from trying to read up the errors (which are not really bismark2bedGraph but more `sort` related).

- I have personally never used 90% as argument for the `--buffer`, maybe you could try `--buffer 20G` next to see if it was just that?
- can you try to make a smaller subset of your file, say 1M CHH positions, and see if that completes fine?
- is there a chance that the CHH context file has been modified in some way between the methylation extractor and `bismark2bedGraph`?
- is there a chance that the scaffolds have some really odd names that could lead to sort not being able to identify them as chromosome names?
- if you wanted to you could send me a chunk of your CHH data and I could try to replicate the error on my side?

Sorry if this is not immediately more helpful, Best, Felix

**Comment by svrever** [comment]
Hi Felix,
thanks for the reply. I also looked into google, but could not make much sense of it. I have a feeling that it is the size of CHH file that is causing problems. CpG and CHG files straight from the same methylation extraction run were converted to bedGraph just fine. From the the look into the TEMP folder it seems that while converting CHH to bedGraph program created about 30 16G temp files and then started to stitch them together into sort2emEOv, failing at ~213G size. I will try to run bismark2bedGraph on a smaller 14G CHH file (with --buffer 20G option) just to prove it can be converted.  And I am not sure of how to make the chunk of CHH data file.

Sergei

**Comment by svrever** [comment]
Bismark2bedGraph on  14G CHH file forked fine. Is there an option to split big CHH files before processing and combine resulting bedGraph files afterwards?

Sergei

**Comment by FelixKrueger** [comment]
I'm afraid there isn't. How much space do you have free on your device? We use the output directory of `bismark2bedGraph` as temporary directory for sort (instead of the default /TMP), so maybe the big file just fills up all of your hard drive? If you wanted to split the process into 2-3 separate processes you would have to somehow write a script that does the sorting separately I am afraid. Then you could just concatenate the coverage outfiles.

**Comment by svrever** [comment]
No, the drive does have enough space. I will think about splitting/combining options, thanks!

Sergei
