### ISSUE TITLE
bismark_genome_preparation fails due to duplicated chromosome names (?)

### ISSUE THREAD

**Issue by marchoeppner** [FelixKrueger/Bismark#119]
Hi,
using Bismark 0.18.2 on Centos6 and was trying to create an index for human assembly hg38 obtained from UCSC. 

However, I get the following error:

`Exiting because chromosome name already exists. Please make sure all chromosomes have a unique name!`

This worked just fine for the EnsEMBL versions of GRCh37 and GRCh38. 

According to:
grep "^>" | wc -l
grep "^>" | sort -u | wc -l

all chromosome names in the hg38 assembly are unique (the ALT chromosome names are variations of the canonical reference name with underscores etc, of course). So this must have something to do with how Bismark parses chromosome names? I suppose I could remove ALT chromosomes, but was wondering if that is sensible or not (maybe providing alignment sinks will increase overall accuracy?). 

Cheers,
Marc

**Comment by FelixKrueger** [comment]
Hi Marc,

Bismark uses the first word as chromosome name until it hits a white space (so empty space, tab, etc), and often the problem is that just that. There is also a chance that you've got weird line endings at the end of the lines which could lead to the same error, could you try `mac2unix` or `dos2unix` on the reference file to see if that was the problem?

I have pushed an update to the `bismark_genome_preparation` that will also report which chromosome already existed so it should be very easy to see what went wrong. Please just clone the latest development update and try again. Cheers, Felix

**Comment by marchoeppner** [comment]
Cheers - but I can only see 2 branches - master and dinucleotide_cov_plot, but not devel or development ? And nothing has been pushed to the other two branches in the past couple of days

**Comment by FelixKrueger** [comment]
Oh sorry the push didn't get through, try now.

**Comment by marchoeppner** [comment]
So the problem was that, in the folder for hg38, we had two copies of the genome (genome.fa and hg38.fa) - for legacy reasons. Since Bismark combines all fasta files in one folder as a reference, that's where the duplicated IDs came from. Oh well! Thanks for the quick reply!

**Comment by FelixKrueger** [comment]
Excellent, glad you got it sorted!
