### ISSUE TITLE
coverage2cytosine inconsistent accounting

### ISSUE THREAD

**Issue by vpbrendel** [FelixKrueger/Bismark#127]
There are a couple of places in the current code when a last G on the top strand is not accounted for with comment:

"### If the very last position is a C in CpG context on the bottom strand we need to exclude it because its top strand equivalent
### will have been rejected due to insufficient length for $tri_nt"

I think this needs a bit of work.  First of all, the code does not check whether the context is CpG.  Second, presumably we need top and bottom strand only when CpG counts are merged.  And third, the restriction is not invoked when a sequence has no read coverage.

What does that mean currently?
- if a sequence ends in ...AAG, the G is counted if there is no read coverage for this contig, but rejected otherwise
- if a sequences ends in ...ACG, the G is counted but the C is not because it lacks trinucleotide context (I would prefer to count it in context CGN)

Of course only small numbers of sites are affected, but as the code includes provisions for this accounting, I think we should fix it.  On a practical level, I have applications that combine creports from different samples, and for that to work, I expect all reports to report on the same sites (which gets violated because of the third feature mentioned above).

Thanks, Volker

**Comment by FelixKrueger** [comment]
Hi Volker,
I am now back and will look into this. Thanks for your suggestions.

**Comment by FelixKrueger** [comment]
Hi Volker,

Thanks for pointing out the issue with `substr`, I have now corrected this is everywhere in the `coverage2cytosine`. 

I also agree that chromosomes which get covered should be treated in the same way as chromosomes or scaffolds which didn't. I will try to fix this tomorrow.

The last issue is a little more tricky, mainly because it can't actually be fixed within `coverage2cytosine`, or at least not alone;

If a sequence ends in `...ACG`, then there may be an alignment on the reverse strand starting with `CGT...` which is perfectly valid. Top strand alignments on the other hand will have been rejected during the Bismark alignment itself and classified as `"Chromosome sequence could not be extracted"` sequence. If you are working with a genome like human or mouse this really only happens a handful of times for many millions of sequences and usually affects the MT chromosome only anyway. On top of that, if I see a sequence aligning to the exact start or end of a chromosome I am normally quite sceptical, but this could just be a personal issue of mine...

I can see that it might turn up more times when you have many more chromosomes/scaffolds, but this would mean we would actually have to go back to Bismark and change the behaviour of extracting the chromosomal sequence as a first step.

Say we did that, there would be the next issue that the methylation extractor currently classifies every cytosine context containing an `N` as Unknown context and disregards it when writing the information out to a file. And then finally, as you said, we would need some additional checks in `coverage2cytosine` disallow sequences at the end unless their context is CGN. 

I know that methylation in social insects is very scarce so you would ideally like to account for every possible event, but do you really think there is enough (credible) information in these few cases we are talking about that would justify looking at all of the issues here?

Cheers, Felix

**Comment by vpbrendel** [comment]
Hi Felix:
Thanks for looking into this.  I think treating the covered and uncovered sequences in the same way is sufficient, as then creport files from different samples can be fairly compared or merged.  For the terminal nucleotides, I think coverage2cytosine should remain consistent with methylation_extractor - I completely agree that those few terminal sequences can be consistently ignored (they are not fair game anyway because it's harder to find reliable read mappings at the ends).
Volker

**Comment by FelixKrueger** [comment]
Excellent, I have now tried to change the processing of uncovered chromosomes in line with covered ones (here 9dacc74bbc31723483d40116ff03b87d28d94c6c). Please let me know if you are still experiencing issues with merging creports. Best, Felix

**Comment by vpbrendel** [comment]
All working as it should.
Thanks, Volker

**Comment by FelixKrueger** [comment]
Great, thanks thanks for the feedback.
