### ISSUE TITLE
coverage2cytosine file handling issues

### ISSUE THREAD

**Issue by rifius** [FelixKrueger/Bismark#129]
coverage2cytosine CpG output fails in NOMe seq mode when split by chromosome requested.  Coverage file not open.
NOMe seq always produces gz files, irrespective of --gzip.
GpC output does not split by chromosome when --split_by_chromosome.

**Comment by FelixKrueger** [comment]
I did now have another go at getting `--split_by_chromosome` to work again (ba8786edee6db5793824eb602a8c5125e8119d76 and e1a22958be6bf2c111c32ec79ae8ebf1a812ba42). In my tests all combinations of default, `--gzip`, `--gc`, `--NOMe` and `--split_by_chromosome` appear to be working as intended. Please let me know if something isn't working on your end, otherwise I will aim for a new release soon. Cheers, Felix

**Comment by FelixKrueger** [comment]
This is now included in the latest v0.19.0 release: https://github.com/FelixKrueger/Bismark/releases/tag/0.19.0
