### ISSUE TITLE
CT SNPs during methylation call

### ISSUE THREAD

**Issue by RoseString** [FelixKrueger/Bismark#130]
Dear @FelixKrueger ,

Is there a way to eliminate CT (GA) SNPs during methylation extraction? I used SNPsplit to separate reads based on fixed differences between alleles and it worked nicely. For this reference genome, only fixed differences between alleles were masked by Ns.

Since CT(GA) polymorphisms may affect real DNA methylation call, my thought is to give a different reference with all the SNPs (not just fixed differences) masked by Ns when running bismark_methylation_extractor. Is that gonna work?

P.S. I didn't give SNPsplit the reference with all SNPs N-masked, because SNPsplit calls any reads with deleted Ns 'conflicting' and would lower the splitting efficiency. To improve the splitting efficiency, I masked only fixed differences.

Hope my description is clear. Thank you very much!

**Comment by FelixKrueger** [comment]
Hi @RoseString,

I hope I am getting your point, aplogies if I am missing it :smirk_cat:
The methylation extractor doesn't currently have an option to ignore certain positions in the genome, but I suppose there are two rather easy ways around this:

1. First you could carry out the methylation extraction and generate a coverage file of CpG positions. Then you could post-process the coverage file and exclude all CT or GA positions (this would need a very short script, or could be done in R).
2. You could mask both the SNPs which are discriminating your two strains and CT/GA SNPs with Ns in the SNPsplit genome preparation, and align your BS-Seq data to that reference. When it then comes to using SNPsplit to sort your reads according to strain you should be able to only feed it the actual SNP file  with `--snp_file` but not the CT/GA polymorphisms. This should work because positions in the genome involving an N will not participate in the methylation call procedure and will receive a `.` (dot) in the methylation call string.

Do you think either of these options would work for you?

**Comment by RoseString** [comment]
Hi @FelixKrueger,

Thank you so much for your detailed answers! I think the first option would work best for me. 

The second option definitely would work too, but I just have a little concern about lower splitting efficiency it could cause. From my past experience with SNPsplit, any reads with ^N (deletions of N(s) in the reference) would be categorized as 'CF' (conflicting). For example, if a read mapped to the reference has a deletion of N (**where a CT/GA polymorphism is**) and a bunch of G1 SNPs (**genome 1-specific SNPs**), the read would be tagged as 'CF' not 'G1', even if it contains G1 SNPs. Therefore, masking all SNPs including CT/GA polymorphisms in the reference may lower splitting efficiency. Is this correct?

I'll go for the first option for now. Thank you again!!

**Comment by FelixKrueger** [comment]
Hi Rose,

It is true that reads with a deletion of the N (^N in the MD:Z string) are considered conflicting, this would however really only apply for deletions at this position (not sure how frequently this would occur but probably not very often). 

N-masked positions on the other hand should not be deleted though and thus C>T transitions would be simply ignored for the allele-assignment and counted as `N was not present in the list of known SNPs`. So in theory these positions won't have received a methylation call, and should be irrelevant for the allele-splitting procedure. If you have some time you could of course try both methods, and ideally find that they will produce (roughly) the same result.

All the best, Felix

**Comment by RoseString** [comment]
Hi @FelixKrueger,

I believe I must have misunderstood how it works. Thank you for the correction and help. I'll close this issue now.

**Comment by FelixKrueger** [comment]
Great, let me know if there is anything else I can assist you with. Best, Felix
