### ISSUE TITLE
empty BAM file with single-end data

### ISSUE THREAD

**Issue by gunjangala** [FelixKrueger/Bismark#131]
Hello,
I am trying to run bismark for single-end data using the following command. It results in empty BAM file. Not sure what I am missing. Can you please take a quick look and let me know.

```
RUNDIR=/ifs/home/BiSulfiteGenome_analysis/WGS-BS
bismark_ref_genome=/ifs/home/mm10/
fastq_WGS=/ifs/home/test.fastq
bismark --multicore 4 -N 1 -p 20 -n 1 --bowtie2 ${bismark_ref_genome} -q --se ${fastq_WGS} --temp_dir ${RUNDIR}/temp_dir
```

Thanks,
Gunjan

**Comment by FelixKrueger** [comment]
Hi Gunjan,

I don't think you are necessarily missing something, but if anything you might be trying to use more resources than you have available.

Here are my comments:
- `--multicore 4` will use four times as many resources as just a single version. For the mouse genome this is ~50GB of RAM, and - combined with `-p 20` will use roughly 180 CPUs. Do you have this available?
- `-N 1` unless required I would use the default (which is 0) because `-N 1` uses more memory and takes longer
- `-p 20` We have heard reports that giving Bowtie2 more than 4 cores per thread actually has a negative impact of the alignment speed as the methylation calling etc can't keep up. That's why there is a warning that you should probably not exceed `-p 4` when you run Bismark.
- `-n 1` is redundant, and should only be used for use with Bowtie 1
- Finally, it is very important to use appropriately trimmed data for the alignment step, so please run your file through Trim Galore (in default mode) first (if you haven't already done so)

And lastly: If you look at the error log file or watch what Bismark is doing on screen you will probably be able to tell what went wrong. Most often it runs out of memory (high numbers of `--parallel`), but you should be able to spot that. If you've got any problems identifying the course I invite you to send me the error log file to take a look.

I hope you will get to the bottom of this soon, All the best, Felix

**Comment by FelixKrueger** [comment]
Did you have any luck finding out what went wrong?

**Comment by gunjangala** [comment]
I tried with and without assigning threads/multicores (with sufficient compute power and space) but the BAM output was quite small as compared to tmp.bam files. I would be using trimgalore and re-running Bismark. Will let you know how it goes.

Thanks,
Gunjan

**Comment by gunjangala** [comment]
This time it worked. The problem was with my input files and not at bismark step. 
Thanks,
Gunjan

**Comment by FelixKrueger** [comment]
Thanks for letting us know. All the best, Felix
