### ISSUE TITLE
Can I mix paired-end and single-end files in the same run?

### ISSUE THREAD

**Issue by DiegoZvallo** [FelixKrueger/Bismark#137]
Hi Felix, I was wondering if it's possible to mix the paired and the unpaired files that trimmomatic gives as output after the adapter and quality trimming?
Or it's better to run it separately, and if so, when can I mix the output?

And one other thing, I have biological replicates for my experiment, do you think that I should merge the fastq files? Or should I run them separately? Do you know softwares that deals with biological replicates in BS-seq experiments? As far as I know, methylkit and DMRCaller (the only ones that I used) doesn't have the option.

Best

Diego

**Comment by FelixKrueger** [comment]
Hi Diego,

If you have a mix of single-end and paired-end files you need to align them separately. Assuming you are looking at a directional library, the paired-end alignments as well as Read 1 in SE mode may be aligned in default conditions, i.e. directional mode. Since Read 2 is complementary to Read 1, R2 needs to be aligned using the option `--pbat`.

While we are at it, in case you are dealing with RRBS data you might want to consider using Trim Galore (https://github.com/FelixKrueger/TrimGalore) for the trimming step as it automatically detects the adapters used and has extra functionality for RRBS trimming the command would simply be: 
`trim_galore --rrbs --paired read1.fast.gz read_2.fastq.gz`

PE and SE data also needs to be methylation extracted in their respective modes. You can then combine the output together for the `bismark2bedGraph` step by simply giving it all the CpG* context calls from both the PE and SE runs. A command for this would be:

`bismark2bedGraph --buffer 10G -o output_file CpG*`

Biological replicates should definitely be processed individually, if you needed to merge the resulting data in the end to get higher coverage you could always do this after the mapping step if needed. I believe methylKit does handle biological replicates via logistic regression. We personally use SeqMonk for many of our analyses, but there are quite a few other DMR packages out there, bsseq from the BSmooth package for example. 

I hope this helps,
Best, Felix

**Comment by DiegoZvallo** [comment]
Hi Felix, thanks for your detailed answer.
Actually, I'm not dealing with RRBS data. Last year I wrote a question in the bismark's seqanswer forum related to which strand should I expected to have data from in an amplicon sequencing experiment. 
http://seqanswers.com/forums/showthread.php?p=196435#post196435

Now I'm dealing with the same type of data. Does this means that I should ran both PE and SE reads in a --non-directional mode?

Does TrimGalore have an amplicon sequencing mode? Do you recommend me to use it anyway? 

I notice that SeqMonk is also developed by the Babraham Institute. Did you think that it is possible to analyses my amplicon sequencing data, including the biological replicates as they are, and not for merging them and get higher coverage? Actually the good thing about amplicon sequencing coupled to NGS is the depth.  

Thanks again

Best, Diego

**Comment by FelixKrueger** [comment]
Hi Diego,

Yes I think you should run both in non-directional mode and then only use the strands you are expecting. Trim Galore should work just fine for that kind of data, just drop the `--rrbs` option.

And yes SeqMonk should be able to analyse your data including the biological replicates (also using logistic regression).

All the best, Felix

**Comment by DiegoZvallo** [comment]
Hi Felix, thanks for your detailed answer.
Actually, I'm not dealing with RRBS data. Last year I wrote a question in the bismark's seqanswer forum related to which strand should I expected to have data from in an amplicon sequencing experiment. 
http://seqanswers.com/forums/showthread.php?p=196435#post196435

Now I'm dealing with the same type of data. Does this means that I should ran both PE and SE reads in a --non-directional mode?

Does TrimGalore have an amplicon sequencing mode? Do you recommend me to use it anyway? 

I notice that SeqMonk is also developed by the Babraham Institute. Did you think that it is possible to analyses my amplicon sequencing data, including the biological replicates as they are, and not for merging them and get higher coverage? Actually the good thing about amplicon sequencing coupled to NGS is the depth.  

Thanks again

Best, Diego
