### ISSUE TITLE
Mapping Warning Info

### ISSUE THREAD

**Issue by hmyh1202** [FelixKrueger/Bismark#142]
>>> Writing bisulfite mapping results to pTregrep1_P_R1.fq.gz_bismark_bt2_pe.bam <<<

Dear,sir:
I got the information below when do alignment:
Reading in the sequence files R1.fq.gz and R2.fq.gz
Use of uninitialized value in length at bismark_v0.9.0/bismark line 3053, <$__ANONIO__> line 71310.
Chromosomal sequence could not be extracted for	E00513:166:HC3L2CCXY:1:1101:13961:21667_1:N:0:CTCTCGAC	lambda114

So why this error was happend?

**Comment by FelixKrueger** [comment]
Were you really using Bismark v0.9.0, which is some 4 and a half years outdated? 

Just generally:
```
Chromosomal sequence could not be extracted for E00513:166:HC3L2CCXY:1:1101:13961:21667_1:N:0:CTCTCGAC	lambda114
```
This is not an error message but merely a warning that it could not extract 2bp of chromosomal sequence upstream (or downstream) of the mapped read because the sequence probably aligned to the very edge of the reference sequence. This is not normally a problem.
```

Use of uninitialized value in length at bismark_v0.9.0/bismark line 3053, <$ANONIO> line 71310.
```
This is an error, but frankly I am not going to investigate issues of releases that are ~26 releases behind. If you still see the error with the most up-to-date version (0.19.0 or 0.19.1_dev) I will take another look.

**Comment by hmyh1202** [comment]
OK , Thank you!
