### ISSUE TITLE
filter_non_conversion in human genome: what parameters should we choose?

### ISSUE THREAD

**Issue by jlsovaz** [FelixKrueger/Bismark#144]
Hello Felix,

I am a new user of Bismark. I am trying to map reads from targeted bisulfite sequencing (a set of 5 amplicons from human genome). After mapping, I get ~95% of mapped reads. In the report, the methylation call shows a very little amount of methylated Cs in other contexts (CHG and CHH): < 0,1% of methylated C's from the total.

However, in terms of reads, using the filter_non_conversion tool, it makes a big difference. If I run the filter_non_conversion with a default threshold (=3), I loose < 0.1% of my reads; but if I want to be strict (only 1 C in no-CG context), I loose almost the 15% of the mapped reads. So my question is: What is better? What is the best option, to filter, to not filter, to filter in a more strict manner...?

This is the first time I am using github to make a question (don't know if it's the appropriate place to do it). I hope I would explained my issue correctly.

Thanks in advance,

Jose Luis

**Comment by FelixKrueger** [comment]
Hi Jose,

First of all it is good news that you get such a high mapping efficiency with a conversion efficiency of 99.9%. To be honest I don't think that the filtering for non-conversion is needed in this case as less than 0.1% of reads are filtered out if you were to use a threshold of 3. I am pretty sure that the results won't change noticeably, even if you were to filter super stringently with a  threshold of 1. 

I am also not convinced that you 1 is a good threshold to use, because you would essentially apply an arbitrary cutoff to what might have been a truly methylated cytosine. Maybe you could rather use the new `--percentage` option and say anything where at least say 80% of non-CG were methylated in the entire read will get booted. In any case, I don't think the actual results are going to change much.

I hope this helps, Cheers, Felix

**Comment by jlsovaz** [comment]
Thank you very much for your advice. I'm only interested in methylated and non methylated cytosines in CpG context, so I was afraid of reads with methylated non-CG citosines (these reads would be the result of an incorrect bisulfite conversion). 

I applied the --percentage option and the results show again a very low number of reads filtered, so I think I won't use the filtering for non-conversion. As you said, the final result maybe won't change considerably.

> I am also not convinced that you 1 is a good threshold to use, because you would essentially apply an arbitrary cutoff to what might have been a truly methylated cytosine.

I agree with you. For future works I'll try to filter with the default threshold or using the --percentage option.

Regards,

Jose
