### ISSUE TITLE
Concordant/discordant/dovetail reads

### ISSUE THREAD

**Issue by jlsovaz** [FelixKrueger/Bismark#145]
Hello Felix,

I would want to know what is exactly a concordant or discordant alignment in paired end reads (and dovetails as well). The explanation mentioned in the user guide seems to be clear, but finally I don't understand what would be the best option with --nomixed, --no-discordant or --dovetail. I mean, Is it better to have concordant than discordant alignments? Should I be worried if the mapping found a high number of discordant alignments but less concordant alignments?

Sorry about the question, maybe is very basic in terms of alignment theory.

Thank you in advance,

Jose

**Comment by FelixKrueger** [comment]
Hi Jose,
You can read a bit more about the theory of discordant reads over at the Bowtie2 manual site:
http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#concordant-pairs-match-pair-expectations-discordant-pairs-dont

Just generally, in Bismark we only consider concordant paired-end alignments where both reads of a pair align well, are oriented towards each other and are within a sensible distance of each other (governed by the options `-I` and `-X`). Alignments should not be really discordant unless something weird happened during the library preparation, or possibly if you have structural variation or translocations in your genome. We try to focus on the less weird parts of the genome, which is why `--no-mixed` and `--no-discordant` are on by default. Does this help?

**Comment by jlsovaz** [comment]
Yes, this helped, thanks, finally I understood. However, I am doing the mapping with targeted bisulfite sequencing, so I have 5 different amplicons (with different length, so maybe the mix among all the reads could affect to the efficiency). Today I did a demultiplexing before the mapping, and the number of concordant alignments improved.

Now I have another doubt referring to directional and non directional bisulfite sequencing. If I understood the concept, the main difference between could be that for non directional bisulfite sequencing, you do the PCR amplification after the bisulfite treatment, so the converted bases wil be on the 4 strands. Is this correct?

I have performed a non directional bismark and, for instance, the output for one amplicon was:

Final Alignment report
======================
Sequence pairs analysed in total:       44621
Number of paired-end alignments with a unique best hit: 42955
Mapping efficiency:     96.3%

Sequence pairs with no alignments under any condition:  1666
Sequence pairs did not map uniquely:    0
Sequence pairs which were discarded because genomic sequence could not be extracted:    0

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:       42955   ((converted) top strand)
GA/CT/CT:       0       (complementary to (converted) top strand)
GA/CT/GA:       0       (complementary to (converted) bottom strand)
CT/GA/GA:       0       ((converted) bottom strand)

I don't understand this output. If its a non directional method, I would expext the same number of reads in the four strands (approx). But in this case they are mapped reads in one of the four strands. Is this an error that I am doing with bismark?

Thank you in advance,

Jose Luis

**Comment by FelixKrueger** [comment]
Hi Jose,

This behaviour is not unexpected for amplicon sequencing, it very much depends on your library design strategy. To understand which strand you are expecting I suggest you get a piece of paper and a pen and draw it out in front of you. Normally, the bisulfites PCR primers are designed against a sequence on the top strand, and since the top and bottom strand strand of bisulfites libraries are no longer complementary after the bisulfites reaction you will only get methylation information for the top strand.

In some scenarios you would could see OT and CTOT strands in the library, but apparently the Illumina primers were ligated in such a manner that you only ever see the OT strand. Since close to 100% of sequences align to the OT strand I am pretty sure that you are doing the right thing. I hope this (and sketching it out on paper) helps! All the best, Felix

**Comment by jlsovaz** [comment]
Perfect Felix. Thank you very much for your response. I understood (and actually I needed to draw in a paper).

Regards,

Jose
