### ISSUE TITLE
Context change between XM tag and CX report 

### ISSUE THREAD

**Issue by martinjvickers** [FelixKrueger/Bismark#149]
Hi Felix,

I hope you're well. I've noticed something odd with extracting the methylation into a CX report. If I have the following mapped read from Bismark;

```
@HD	VN:1.0	SO:unsorted
@SQ	SN:1	LN:30427671
@SQ	SN:2	LN:19698289
@SQ	SN:3	LN:23459830
@SQ	SN:4	LN:18585056
@SQ	SN:5	LN:26975502
@SQ	SN:mitochondria	LN:366924
@SQ	SN:chloroplast	LN:154478
@PG	ID:Bismark	VN:v0.19.0	CL:"bismark TAIR10 test.fastq --path_to_bowtie /usr/local/bin"
NS500422:333:H3TJVBGXY:1:11101:10016:14444_14207	16	3	10009985	0	58M1D17M	*	0	0AAATTTCCAATAAATAAAAATCATCCCCAACCACTACAATAAACAATAAAAATTAAACAAAAAAAAAAACATATT	EE//AAAEE//EEE//EEA<AAEEEEEEEAEEEEEEEEE/AEEEEEEEEEEEEEEEE/EEEEEEEEEEEEAAAAA	NM:i:23	MD:Z:1G0G8G1G4G16G1G2G1G1G0G1G0G1G3G0G2^A0G2G1G3G4G1C0	XM:Z:.hh........h.h....h................x.z..h.h.zx.hh.h...hh..z..h.h...h....h..	XR:Z:CT	XG:Z:GA
```

After running the methylation extractor like so and pulling out the methylated/unmethylated bases (of which I'm expecting 21 as displayed in the above `XM` tag);

```
./Bismark/bismark_methylation_extractor --comprehensive --cytosine_report --bedGraph --CX test_bismark_bt2.bam --genome_folder TAIR10
cat test_bismark_bt2.CX_report.txt.CX_report.txt | awk '{if($4!=0 || $5!=0) print $0}'
```
I get the following;

```
3	10009986	-	0	1	CHH	CTC
3	10009987	-	0	1	CHH	CCT
3	10009996	-	0	1	CHH	CAT
3	10009998	-	0	1	CHH	CTC
3	10010003	-	0	1	CHH	CTT
3	10010020	-	0	1	CHG	CAG
3	10010022	-	0	1	CG	CGC
3	10010025	-	0	1	CHH	CAT
3	10010027	-	0	1	CHH	CTC
3	10010029	-	0	1	CG	CGC
3	10010030	-	0	1	CHG	CCG
3	10010032	-	0	1	CHH	CAC
3	10010033	-	0	1	CHH	CCA
3	10010035	-	0	1	CHH	CTC
3	10010039	-	0	1	CHH	CAA
3	10010040	-	0	1	CHH	CCA
3	10010044	-	0	1	CHG	CTG
3	10010047	-	0	1	CHH	CTT
3	10010049	-	0	1	CHH	CTC
3	10010053	-	0	1	CHH	CTT
3	10010058	-	0	1	CHH	CAT
```
I get the 21 bases but only two are unmethylated in the CG context, but in the `XM` tag above it shows I should be expecting 3. It seems that the base at position 10010044 has been changed from a `CG` to a `CHG`. 

I can see why this is when looking at the bases in the reference, the `CTG`, due to the deletion, but my question is why wasn't this picked up in the first place by bismark when creating the `XM` tag only for `bismark_methylation_extractor` to change it? Does this mean that the `XM` tag is being created incorrectly or that `bismark_methylation_extractor` is doing something it shouldn't, or is this how it is supposed to work?

**Comment by FelixKrueger** [comment]
Hi Martin,

It is potentially possible that there is a discrepancy in sequence context between the Bismark output and the genome-wide cytosine report. The reason for that is that when Bismark performs its methylation call (the one you see in the XM tag), it extracts a genomic sequence that aims to be a genomic equivalent to the read sequence. For reads that contain deletions, this may result in a context change. So here the genomic sequence is `CTG` but since the `T` is deleted in the read the resulting context is a `CG` methylation call.

The methylation extractor itself will simply extract the base-resolution calls from the BAM files and write them out to C* context files. 

The following `bismark2bedGraph` step uses the C* context files to construct a coverage file. Until this point, all files (`BAM`,`C*` and `.cov.gz`) use the methylation call produced by Bismark, so as close to the probable context as possible.

Now the final step, `coverage2cytosine` is purely based on the reference genome sequence and does *NOT* care about what actually happened within reads. This is primarily done to have a common set of reference positions, even if it means that for some select reads it might get the context wrong (else you might end up with multiple contexts for the same position and then everything would get more tricky...). 

So the coverage files are probably the more 'truthful' files to work with if you wanted to call them that. Under default circumstances (CpG context only), a context change from CpG to some other context would simply not appear in the (CpG context only) coverage file, and the position would simply be missing from the genome-wide CpG-report. If you run everything in `--CX` mode the whole situation is a little more complicated...

I hope this answers your questions?

**Comment by hmyh1202** [comment]
So, SNP information should be invited to reduce that bias ?

**Comment by martinjvickers** [comment]
Hi Felix,

Sorry for the late reply. Thank you for the explanation, that makes perfect sense. 

Cheers,

Martin
