### ISSUE TITLE
Strand orientation

### ISSUE THREAD

**Issue by hmyh1202** [FelixKrueger/Bismark#151]
Dear sir:
I got confused for strand orientation of BAM file. 
I had got the BAM file of bismark with default parameter.
First， I got the reverse strand（that is -） using SAMTOOLS view -f 16 *bam  and got forward strand mapped reads(that is +) using using SAMTOOLS view -F 16 *bam.
Then, the flag of + is 163 and 99 but with tag of XR:Z:GA XG:Z:GA and XR:Z:CT XG:Z:CT, and the  flag of - is 83 and 147 with tag of XR:Z:CT XG:Z:GA and XR:Z:GA XG:Z:CT.

Now, I want get watson strand and crick strand mapped reads If just screen that by XG tag ？ CT is +, and GA is -.

The best

**Comment by FelixKrueger** [comment]
In single-end mode, OT and CTOT reads will both receive a FLAG of 0 while OB and CTOB both receive a FLAG of 16.

In paired-end mode the flags are like this:

```        
                                       Read 1       Read 2

                              OT:         99          147 
                              OB:         83          163  
                              CTOT:      147           99  
                              CTOB:      163           83 
```

As you can see we have to fudge the FLAGs a little because we here dealing with two copies of the top strand and two copies of the reverse strand. If you want to just top strand (Watson) alignments you need to extract values 99 and 147, if you want just bottom strand (Crick) alignments you need to filter for FLAG values 83 and 163.

**Comment by hmyh1202** [comment]
OK  Thanks
