### ISSUE TITLE
deduplicate_bismark (sorting by name and multiple option)

### ISSUE THREAD

**Issue by bandapanda** [FelixKrueger/Bismark#152]
Hello Felix,

We are stuck on a obstacle during implementation of the whole pipeline for methylation calling and we hope you could help us. We have two pipelines which include all Bismark tools (bismark alignment, deduplicate_bismark and bismark_methylation_extractor). One is sequential and another one is parallelized by chromosome after alignment.

We found out that the problem we have originates from deduplicate_bismark. I read that deduplicate_bismark requires BAM file which is sorted by name. For that purpose we used the following tools:

- Sambamba Sort
- Picard SortSam
- Sambamba with a natural-sort option (as in samtools)

All these tools have the option of sorting by read name which was enabled. Using these tools we got different results at the end of deduplicate_bismark(BAM file) and as a consequence methylation_extractor gives different coverage files too. With Sambamba sort and Picard SortSam, we got the same results in the sequential workflow. In addition, these results are the same when we use Picard SortSam in the parallelized workflow. We got different results when using other previously mentioned sorting tools. We checked the BAM file before deduplicate_bismark and it was same in all cases with different sorting tools. 

Could you please help us by giving us an insight into the basis on which deduplicate_bismark discards reads? Which read properties (cigar string, tags etc.) it looks at when it decides which reads to discard? Does it differ from regular DNA sample deduplication which starts from BAM which is sorted by coordinate?

In addition, one question about the new multiple option in deduplicate_bismark. We saw in the code that before converting the BAM file into a SAM file, you use samtools cat for concatenating parts of BAM file which are provided to the tool. Is it an issue that already sorted files are being concatenated because there is a possibility that the final sorting order is not correct?

**Comment by FelixKrueger** [comment]
Hi @bandapanda,

The deduplication is fairly simple as it works only by taking chromosome, start, end as well as orientation into account (for single-end it is only chromosome, start and strand but assume this is not what you are talking about). The paired-end workflow looks like this:

- 2 consecutive lines are extracted from the BAM file (which is the reason why the files need to be name sorted)
- from those we work out the strand via the read conversion and genome conversion tags (OT and CTOT are `+`, OB and CTOB are `-`)
- we then work out the start and end positions of a read pair, factoring in `CIGAR` operations (`I`,`D` and `M`)
- from this we create a composite string `strand:chr:start:end` and store this in a data structure:
1) if this is the first read pair for this chr, start, end and strand it will be kept, i.e. written to the `deduplicated.bam` output file
2) if there was already a read pair with identical coords the read is discarded

Regarding the file merging:
We do indeed use `samtools cat` for the merging as I was under the impression that this will guarantee the line-by-line order of the input files also for the merged output file. (interestingly `samtools merge` does mostly keep the order, but at transitions from one file to another there may be irregularities which can break the entire downstream process (unless you use the option `-n` at the same time, or re-sort the merged file afterwards by name).
I would assume that there may be problems if you concatenate coordinate-sorted and deeply sequenced 
files because if the sequencing happened on the very same sequencing machine you may end up with different reads having the **exact same** readID because they happen to have occupied the very same tile, x- and y-coordinate on the flow cell. If in doubt you should be able to name-sort the input files before using `samtools cat`, and then ideally it should all work out.

I hope this clarifies a few things?
