### ISSUE TITLE
Bismark bam format 

### ISSUE THREAD

**Issue by josesovaz** [FelixKrueger/Bismark#156]
Dear Felix,

I write this issue to ask you if the bam file created with Bismark has the same "universal bam" format As I read in the manual, I think is a little bit different. If not, I would want to ask you if there is the possibility to convert the Bismark bam like any genomic bam file (even manually).

Thank you in advance,

Regards,

Jose

**Comment by FelixKrueger** [comment]
Hi Jose,

The Bismark BAM file should adhere to the standard BAM conventions. It does have a few optional fields to accommodate the bisulfite specific features, and it required some tweaking of the FLAG values to fit standard BAM FLAGS (because Bisulfite-Seq can have 4 different strands as opposed to just 2 strands in conventional sequencing). But the bottom line is: it should behave pretty much like any other BAM file.

**Comment by josesovaz** [comment]
Perfect. Thank you very much for your answer. 

Regards,

Jose
