### ISSUE TITLE
Bismark inconsistent output type

### ISSUE THREAD

**Issue by rossg5309** [FelixKrueger/Bismark#157]
The many times I've used bismark the out put is usually *_bismark_bt2_pe.sam.gz. On a recent run, about 1/3 of my samples output both a *_bismark_bt2_pe.sam.gz and a *_bismark_bt2_pe.bam and the other 2/3 output just a *_bismark_bt2_pe.bam file.

I'm digging in to see if there are any differences now but am wondering why this might occur.

**Comment by FelixKrueger** [comment]
Hmm, the Bismark default is to write out BAM files. For the BAM conversion is will use the version of Samtools you specify with `--samtools_path`. If that wasn't specified it tries to find any installed version of Samtools itself (with `which`). Only if Samtools was not installed in your PATH and you didn't specify a path manually it should write out a `sam.gz` file. 
This has been in place for a long time, are you running the latest version? I hope this makes sense, Felix

**Comment by rossg5309** [comment]
Hi Felix, thank you very much for your speedy response.

It is true that I do not specify `--samtools_path` and that Samtools is not typically installed in PATH, which is why I would expect consistent `sam.gz` output. This output works fine for my purposes so I skip the additional step of conversion to BAM.

This latest batch was performed with identical options, albeit on a different compute cluster than I typically use. What is confusing, is that within a single job on multiple consecutive samples, one (usually the first) will produce `sam.gz` output and BAM output while the next two will produce only BAM output.

It looks to me like this new compute node has Samtools installed in PATH, which is then automatically used for BAM conversion. Just not sure why some runs produce `sam.gz` output and others do not. Are the `sam.gz` always created and then cleaned up after conversion to BAM? Maybe cleanup is missing some?

**Comment by FelixKrueger** [comment]
This sounds very odd to be honest. It is being decided on start-up whether to do a BAM conversion or not, and there is not temporary cleanup involved. Maybe the new cluster has some nodes with samtools in the PATH and others without?

I any case, I would highly recommend you upgrade to v0.19.0 to stay up-to-date. Also, I would just generate BAM files because it streaming to samtools or to gzip on the fly will hardly make a difference. There might even be some downstream steps that assume BAM format, but I might confuse this with SNPsplit right now (would have to check).

**Comment by rossg5309** [comment]
Sounds good, I'll look into the distribution of Samtools on nodes to see if that might be the source. Thank you for your input and all of the awesome tools you create.

**Comment by FelixKrueger** [comment]
Thanks for the kind words!
