### ISSUE TITLE
"No last chromosome defined..." bismark methylation extractor

### ISSUE THREAD

**Issue by varunorama** [FelixKrueger/Bismark#162]
Hello Felix,

I have been running into this problem for quite some time: 

***************************************************************************************************

Stored sequence information of 125724 chromosomes/scaffolds in total

==============================================================================
Methylation information will now be written into a genome-wide cytosine report
==============================================================================

>>> Writing genome-wide cytosine report to: Day0_S85_L003_R1_001_trimmed_bismark_bt2.CpG_report.txt.gz <<<

No last chromosome was defined, something must have gone wrong while reading the data in (e.g. specified wrong file path for a gzipped coverage file?). Please check your command!

Finished generating genome-wide cytosine report

*******************************************************************************************************

The command that I am running is: 

bismark_methylation_extractor -s --gzip --multicore 4 --bedGraph --buffer_size 2G --cytosine_report --output /path/to/genome/directory/  --genome_folder /path/to/trimmed/bamfile/Day0_S85_L003_R1_001_trimmed_bismark_bt2.bam

Based on previous issues raised by fellow Bismark users, it seems that this is a path issue. One user (justinjohns in https://github.com/FelixKrueger/Bismark/issues/43) mentioned to specify an out directory which I have done. However, I am still getting the above error and all of my temp files exist (suggesting my run did not complete). Any thoughts on how to resolve this issue? 

Possible areas for fix? 
- My bam files are not in the same folder as my genome directory (do not think this should be an issue, but given my genome is very large (~30G) would this make a difference?)
- Memory demands for sort? I ran this using a buffer_size of 10G before as well. Would it be better to increase to 20G?

Thanks,
Varun

**Comment by FelixKrueger** [comment]
I think the problem here is that you are dealing with a genome that consists of 125724 (or in other words: a gazillion) contigs. This normally crashes your OS' capability of files it can handle at the same time, and thus the output coverage file is probably empty, which is why it can't find a last chromosome. The solution to this should be to use the following option:

```
--scaffolds/--gazillion  Users working with unfinished genomes sporting tens or even hundreds of thousands of
                         scaffolds/contigs/chromosomes frequently encountered errors with pre-sorting reads to
                         individual chromosome files. These errors were caused by the operating system's limit
                         of the number of filehandle that can be written to at any one time (typically 1024; to
                         find out this limit on Linux, type: ulimit -a).
                         To bypass the limitation of open filehandles, the option --scaffolds does not pre-sort
                         methylation calls into individual chromosome files. Instead, all input files are
                         temporarily merged into a single file (unless there is only a single file), and this
                         file will then be sorted by both chromosome AND position using the Unix sort command.
                         Please be aware that this option might take a looooong time to complete, depending on
                         the size of the input files, and the memory you allocate to this process (see --buffer_size).
                         Nevertheless, it seems to be working.
```

Using more memory might make the sorting a bit quicker, but it should work nevertheless.

**Comment by adesalegn** [comment]
this process is really time taking. It been almost 2 days on MacOS using 10 cores and still not finished.

**Comment by SNGJING** [comment]
I've had this issue recently as well, and it's a real headache

**Comment by FelixKrueger** [comment]
did using `--scaffolds` fix it?

**Comment by SNGJING** [comment]
> 使用修复了吗？`--scaffolds`

I've used it, and I don't get any errors, but the file generated is wrong, it doesn't generate CpG_report.txt, and the other files are empty

**Comment by SNGJING** [comment]
> > 使用修复了吗？`--scaffolds`
> 
> 我已经使用了它，我没有收到任何错误，但是生成的文件是错误的，它没有生成CpG_report.txt，其他文件是空的

![image](https://github.com/FelixKrueger/Bismark/assets/153048112/8991f040-a2bd-49b8-9caa-0469d822f208)

**Comment by FelixKrueger** [comment]
Hmm. I cannot really see too much in this screenshot, but it is clear that the coverage file (`cov.gz`) is empty, and since this is the input file for the CpG report you cannot expect anything useful. Can you say what you did further upstream, and see if the methylation extraction and bismark2bedGraph conversion goes well (this is the one that requires the `--scaffolds` option...).

**Comment by SNGJING** [comment]
The command I'm running is:
![image](https://github.com/FelixKrueger/Bismark/assets/153048112/125e7449-351e-4365-8318-b557732bb423)

**Comment by FelixKrueger** [comment]
There is a lot going on in this command ... What you need to do now is identify at which stage it goes wrong, and leads to an empty coverage file. You can roughly break the process down into 3 sections (which can also be run individually), I'll give you some comments for each below.

1) **methylation extraction**

Did this step complete alright? If it did you should get a splitting report as well as M-bias.txt files. Since this step can take quite a while (especially with ignoring options specified), you can potentially start with the bedGraph step from the CpG, CHH and CHG files (see 2)) 

Some things to consider: single- or paired-end mode should be auto-detected, just drop `-p`. The options `--no_overlap --report --counts` are default, just lose them. `--parallel 30` seems quite high, but if it completes - fine

`--ignore 10 --ignore_r2 2`: I personally haven't used these options for a decade or so. If you need to ignore that much of both reads you should probably have done that at the trimming step already. Which kind of libraries did you run? It will also make the extraction a lot slower (and as outlines above is almost certainly worse than hard-clipping at the trimming step).

2) **bismark2bedGraph**

This command almost certainly goes wrong somewhere, as you do not end up with valid coverage file. From you screenshot above it appears that you've got a huge `bedGraph.gz..` file (as well as an empty one... why is that?). The bedGraph and .cov.gz files get written to at the same time, so this is strange.

Not quite sure what happens if you specify 500GB for the sort command, but maybe it would be a better option to use `--ample_memory` instead?

3) **coverage2cytosine**

Not sure you want to use the split by chromosome option, but first you need to sort out the previous step...

In any case, studying closely what goes on on screen, or in the log file, is the only way to get to the bottom of this. (maybe a two more quick questions: which version of Bismark are you running, and what machine (specs) are you running this on?

**Comment by SNGJING** [comment]
Dear Felix,
Based on your suggestion, I've removed the arguments ----no_overlap --report --counts --split_by_chromosome, it worked. I don't know why, but it succeeded in generating the file I wanted, thank you very much.
Finally, there is a small problem, removing the default parameter --report, and not generating summary.txt
Thanks for your help!

**Comment by FelixKrueger** [comment]
Glad to head it did now work. The use of `--report` is not necessary as it is on by default. The option. `--cytosine_report` should be the one launching the CX_report.txt file generation, but it takes no argument...
