### ISSUE TITLE
write unmapped reads to SAM file

### ISSUE THREAD

**Issue by PeterParker1** [FelixKrueger/Bismark#163]
Hello Felix,
I have been using Bismark these days. Unfortunately, the mapping effiency is very low, about 13%. Here is the script:
bismark -N 1 -I 0 -X 1000 --non_directional --multicore 3 --bowtie2 /data/genome -1 in.1dd.fq -2 in.2dd.fq
The optinon -un/--unmapped can write unmapped reads to two files (paired end), but does Bismark offer another option that writes unmapped reads to SAM file? Since SAM file includes some mapping information. it may help me figure out what caused the low mapping effiency. Thanks a lot!

**Comment by FelixKrueger** [comment]
Hi Peter,

There is no functionality in the default version of Bismark to write out unmapped reads to the BAM/SAM file as such. I do however doubt that this is actually something you actually want, because all it would tell you is that the reads don't map (hence the name...).

Very often there is another reason for why your (paired-end) reads do not map, and often you can find out the reason by doing one or more of the following:

- Run the data through Trim Galore to remove adapters and low qualities
- run the trimmed data through FastQ_Screen to identify if there are large amounts of contamination (or e.g. PhiX or Lambda spike-ins etc).
- run R1 on its own in single-end mode to see it that has a higher mapping efficiency. If yes then there might be some kind of problem with the paired-end nature of your reads
- look at the FastQC profile to see if there are any obvious problems there (e.g. biases at the start/end of reads?
- why are you running your data in --non_directional mode? Which kind of library prep did you use? 
- `--multicore 3 ` and `--non_directional` together sounds like you will need round 50GB of RAM (if you were dealing with human sequence). Do you have enough resources for that?

If you wanted to you could send me some say 200K reads (gzipped) via email and mention the genome you wanted to align against and I can give it a go.

Cheers, Felix

**Comment by PeterParker1** [comment]
Hello Felix,
Thanks for your suggestions! 
1. I have trimmed the paired-end data before mapping with Bismark, so this may be not the cause of low mapping effiency. And here is the script:
trim_galore --quality 20 --phred33 --stringency 3 --length 30 -o in --paired in_1.fastq in_2.fastq
2. I'm going to run FastQ_Screen as you told me.
3. Running R1 is also a good idea.
4. Actually the  library is not bisulfite, but they are similar to some extent. The library kit is NEB ultra II. I am not quite sure whether it's right to run in --non_directional mode.
5. Each server of our supercomputing system has at least 96 GB RAM.
I' ll first do as you suggest above. If the problem still cannot be solved, then I'll consider sending you 200K reads.
Thanks again!

**Comment by FelixKrueger** [comment]
Excellent, good luck and don't hesitate to contact me again if you have any questions. Cheers, Felix

**Comment by PeterParker1** [comment]
Hi Felix,
I sent you an email several hours ago, but I received an email saying the email address felix.krueger@bbsrc.ac.uk couldn't be found.

**Comment by FelixKrueger** [comment]
That's correct, it is now felix.krueger@babraham.ac.uk (changed in 2011 or so...).
