### ISSUE TITLE
Question about reads counts

### ISSUE THREAD

**Issue by Camethyleabergen** [FelixKrueger/Bismark#173]
Hi,

I'm having an issue on WGBS data and bismark. I have 3 different samples, and it seems that I have a different results in coverage between samtools (1.8) and Bismark methyl extract.
I'm using deduplicated files, probably by bismark, but we have difficulties to be sure by which tool actually. 
I'm working exclusively on mtDNA, so you can have very high coverage because of the multiple copies in each mitchondrion.
Basically what I did? 
I used samtools depth -m 0 and awk it to get only the mtDNA positions. The maximum depth is about 22000. 
With Bismark methyl extract, I used it to extract the methylation status for each C. I only took in account the CpG context for that project. The file for each sample is the same. From that, I group by position the number of reads took in account by methylextract (about the same value as a depth then). I have sometimes up to a depth of 45000. (200 out of 16659 are >22000).

In IGV, I have same results as samtools.

I don't see why is it so different? 
Does Bismark ME take in account also the duplicated marked reads? 
Any issue of the same kind reported?

Best,

**Comment by FelixKrueger** [comment]
Hi @Camethyleabergen,

The Bismark workflow normally consists of:
 1. Alignment (using `bismark`)
2. Deduplication (using `deduplicate_bismark`)
3. methylation extraction (using `bismark_methylation_extractor`).

The deduplication step (2.) physically removes duplicated reads from the file and does not mark them like e.g. PicardMarkDuplicates does.
Bismark's methylation extractor extracts **all** methylation calls from the entire file you use input files because it expects that duplicates have been removed already.

I would recommend you try out [SeqMonk](https://github.com/s-andrews/SeqMonk) for the visualisation and analysis of your issue because it is dead easy to use and you can easily just hop to the MT, look, perform quantitations of methylation calls from the original BAM file, the deduplicated file you have right now, or a deduplicated file produced with `deduplicate_bismark`. I am sure that within a few minutes you can find all the answers to the questions raised above. Cheers, Felix

**Comment by Camethyleabergen** [comment]
Thanks Felix, I'll have a look at this !

cheers
