### ISSUE TITLE
filtering of rare CpG sites

### ISSUE THREAD

**Issue by AnnikaBlume** [FelixKrueger/Bismark#181]
Hi,
I have numerous rarely covered CpG sites in my data, which are not in a CpG context in my reference genome. I assume these to appear from "mutations" (H -> G) right after a C, missleadingly converting this position into a CpG site. By looking at the raw data, I found this kind of mutation also in samples, in which this position was not called as CpG site, but in less than 1% of the reads.
Is it therefore true that the filtering value for calling a CpG site is 1%?
Would it be possible to change that?

Thank you a lot
Best,
Annika

**Comment by FelixKrueger** [comment]
Hi Annika,

I am not exactly sure I understand the 1% filtering value exactly, but I can say some general things.

You are right that the context of cytosines may change in certain circumstances, more specifically when the base downstream of a C is deleted (insertions are treated differently). One gets to choose between making the decision to a) simply ignore such positions that disagree with the genomic reference sequence, or b) to include these positions as well as their changed context because this is what the reads say. We went with option b), because we often see a state change in the methylation as well (especially when the shift is between CpG and non-CG).

So the Bismark coverage file contains both positions that are CpG positions in the genome, as well as a  few positions that had their context call changed due to a deletion downstream. If you really wanted to eliminate these positions from your data altogether you could process the data further to a genome-wide CpG report using `coverage2cytosine`. This report is strictly based on the reference genome sequence, so any positions that were had a different context call due a deletion would no longer be present.

Does this help at all?

**Comment by AnnikaBlume** [comment]
Hi Felix,

thank you for the quick answer!
Just one more question with a bit more specific explanation:
I had a look at a specific non-CpG site in my data in three different samples. The site was called as an unmethylated CpG site in two of the samples (>1% of Gs at the position) and it was not called in a sample with <1% of Gs at the position. This is why I assumed that 1% of reads is the criteria to call a CpG site. Is that true or can you explain why I have the CpG site called in two but not the third sample.

Thanks again
Best, Annika

**Comment by FelixKrueger** [comment]
Bismark is not doing anything clever for context-swaps, such as applying any thresholds. If two samples support a context change but a third one doesn't it probably just means that that sample did not have a genomic deletion next to that position which caused the context change.
