### ISSUE TITLE
genome-wide cytosine report output question

### ISSUE THREAD

**Issue by LQHHHHH** [FelixKrueger/Bismark#187]
Hi Bismark team,

By using command `bismark_methylation_extractor -p --no_overlap --comprehensive --bedGraph --gzip --CX --counts --cytosine_report --genome_folder ./ --buffer_size 10G XXX.Clean.1_bismark_bt2_pe.bam`, I have got a file named _XXXX.CX_report.txt.CX_report.txt_ , it seems include CpG CHH and CHG reports.

Is there a option that can separate CpG CHH and CHG reports into _*.CpG_report.txt_, _*.CHG_report.txt_, _*.CHH_report.txt_, instead of _*.CX_report_.

Thanks a lot!

**Comment by FelixKrueger** [comment]
While there is no special option to separate the three contexts even further, you can achieve this only using certain contexts from the primary methylation extractor output as input for `bismark2bedGraph` and `coverage2cytosine`.

The code would probably look something like this:

**Step 1** (context-specific methylation extraction):
```
bismark_methylation_extractor --gzip XXX.Clean.1_bismark_bt2_pe.bam
```
**Step 2** (context-specific coverage file generation):
```
bismark2bedGraph --buffer 10G -o CpG_context CpG_*_XXX.Clean.1*
bismark2bedGraph --buffer 10G --CX -o CHG_context CHG_*_XXX.Clean.1*
bismark2bedGraph --buffer 10G --CX -o CHH_context CHH_*_XXX.Clean.1*
```

**Step 3** (context-specific cytosine report generation):
```
coverage2cytosine --gzip --genome ./ -o CpG_report CpG_context.cov.gz
coverage2cytosine --gzip --genome ./ -o CHG_report CHG_context.cov.gz
coverage2cytosine --gzip --genome ./ -o CHH_report CHH_context.cov.gz
```

I hope this helps. Best, Felix

**Comment by LQHHHHH** [comment]
Hi Felix,

I have tried three steps above, but when I run step 3 e.g. `coverage2cytosine --gzip --genome ./ -o ./report_file/CHH_report_DWCK CHH_context_DWCK.gz.bismark.cov.gz` . The running information show: 
```
Summary of parameters for genome-wide cytosine report:
==============================================================================
Coverage infile:                                CHH_context_DWCK.gz.bismark.cov.gz
Output directory:                               ><
Parent directory:                               >/home/spark/yinhao/<
Genome directory:                               >./<
CX context:                                     no (CpG context only, default)
Genome coordinates used:                        1-based (default)
GZIP compression:                               yes
Split by chromosome:                            no

```

the CX context show `no (CpG context only, default )` and output file named _CHH_report_DWCK.CpG_report.txt.gz_ , it seem only report CpG context. It also cannot separate the three contexts.

Can I directly use a script to extract CpG CHG CHH from DWCK.CX_report.txt.CX_report.txt? Is this reasonable？

Here is part of content of _CHH_report_DWCK.CpG_report.txt.gz_

```
Chr3    143     +       0       0       CG      CGT
Chr3    144     -       0       0       CG      CGG
Chr3    149     +       0       0       CG      CGG
Chr3    150     -       0       0       CG      CGC
Chr3    152     +       0       0       CG      CGG
Chr3    153     -       0       0       CG      CGC
Chr3    168     +       0       0       CG      CGA

```

Thanks!

**Comment by FelixKrueger** [comment]
Hi, yes you are right, you would have to include `--CX` as well or it will default to CpG context only. 

However, the problem with `--CX` is that it will still report one line for every single C in the genome, even though you should only get values of >0 for positions that were covered as CpG, CHG or CHH context. I suppose running a script or a clever `awk` command could do the filtering as well...

**Comment by LQHHHHH** [comment]
So you mean I should get the position that value >0 and then separate CpG CHG CHH from _DWCK.CX_report.txt_

**Comment by FelixKrueger** [comment]
So if you followed the steps above, you will get 3 different coverage files, with only the CpG calls, CHG calls or CHH calls that you actually observed in your experiment. 

If you want to gone step further and use these context filtered coverage files for `coverage2cytosine` like so:

```
coverage2cytosine --CX --gzip --genome ./ -o CpG_report CpG_context.cov.gz
coverage2cytosine --CX --gzip --genome ./ -o CHG_report CHG_context.cov.gz
coverage2cytosine --CX --gzip --genome ./ -o CHH_report CHH_context.cov.gz
```

You will end up with the the 3 files:
```
CpG_report
CHG_report
CHH report
```

The difference between the coverage files and the is mainly that
- coverage files contain only positions that were covered in your experiment
- coverage file may occasionally contain a different genomic context than the genomic reference sequence which can be a result of insertions but mainly deletions (as an example you could have a genomic CHH like this one: `CTTAGTCT` which has a 3bp (`TTA`) deletion right downstream of the C; this would change the context to `CGTCT`, which would now be CpG context.

- cytosine reports are strictly based on the genomic reference sequence, and each of them will contain the same number of lines (every single C in the genome)
- if you supply only a limited subset of coverage files (e.g. CpG, or CHH context only), then only those positions will have values other than 0. Or in other words: if you feed it CHH context files then all positions in either CpG or CHG context should have counts of 0 0 (methylated / unmethylated).
- The only exception to this are positions where the context was changed due to deletions downstream of the C.

I suppose you could either use a script or clever `awk`ing to filter a comprehensive CX-report for either the context and/or the number of counts (maybe using several passes), however the steps outlined above would work with the tools that are already available and wouldn't require you to come up with a script of `awk` solution at all. Hope this is now clearer?

**Comment by LQHHHHH** [comment]
Hi Felix,

Thanks for your patient answer.

It helps me a lot.

Best wish,
Qionghou Li
