### ISSUE TITLE
How does Bismark call methylation from bam files?

### ISSUE THREAD

**Issue by dansapozhnikov** [FelixKrueger/Bismark#193]
Hi Felix,

Sorry if this is the wrong forum to post this question...I don't think it is an issue as more likely I just don't understand this.

Can you please explain how the bam alignments relate to methylation percentage? For example, here is one C that has 27 As and 29 Gs mapped to it from the combination of pairs and previously-unmapped singles:
![image](https://user-images.githubusercontent.com/41095622/43929712-1a34d9de-9c04-11e8-8ee5-cd55acdacbb7.png)

After methylation extraction, the methylation value is 4%. Should it not be (29 G)/(56 total A+G) = 51%? How is 4% calculated?
To make this file viewable I had to sort it, does that have something to do with it? 

Thanks!

Best,
Dan

**Comment by FelixKrueger** [comment]
Hi Dan,

This is a bit tricky to answer without seeing the actual data. Just generally, if we assume that you are looking at a genomic G position, which would mean a C on the reverse strand, then I would agree that the calculation you are suggesting is what I would expect. If the position is a genomic C (C on the forward strand), then both G or As would be considered as SNPs and would not participate in methylation calling.

What does the coverage file say about this position? You should be able to simply grep for the position to see the actual counts that were taken into consideration here. If this doesn't resolve it, could you extract the reads from the sorted and indexed BAM file (e.g. using `samtools view`) and send them to me via email so I can take a closer look?  Cheers, Felix

**Comment by dansapozhnikov** [comment]
Hi,

Sorry for not clarifying: the genomic position is a G. This nearly 50-50% read count occurs at every C or G that is called by Bismark, as show below:

![image](https://user-images.githubusercontent.com/41095622/43966561-3bd795cc-9c90-11e8-86b2-8b543f1e400b.png)

Here is the breakdown of the mapped reads for that example G from IGV:

![image](https://user-images.githubusercontent.com/41095622/43966695-9542c58c-9c90-11e8-91b3-9097b62d27bb.png)

And here is the bismark coverage, as you asked for:

scaffold1       793358  793358  4       1       24


I will be sending you the extracted reads shortly.

Thanks for your help!

Dan

**Comment by FelixKrueger** [comment]
Hi Dan,

Thanks for sending some sample data. I just took a look, and I have to admit that I don't exactly know what is going on, but I have a suspicion that your workflow is somehow introducing these issues. Maybe IGV is interpreting the FLAG values in the reads in a weird way since? Here is what I did:

I took the PE and SE bam files you send and extracted the methylation calls. This had to be done in SE mode since your subsetting and/or sorting procedure left unpaired reads in the PE file. I then had a look at the data in SeqMonk, this is what I saw:

![methylation subsetted region](https://user-images.githubusercontent.com/5870509/43993675-4d797288-9d89-11e8-84e9-64390dc4df97.png)

The maximum read depth was 55 reads, and from the lower track one can see that the regions - with one exception - almost universally unmethylated (blue reads). The coordinates or numbers I extracted don't seem to match up with your example above:

```
scaffold1	793291	793291	0	0	17
scaffold1	793292	793292	0	0	12
scaffold1	793324	793324	0	0	23
scaffold1	793325	793325	0	0	20
scaffold1	793369	793369	0	0	24
scaffold1	793370	793370	14.8148148148148	4	23
scaffold1	793458	793458	0	0	8
scaffold1	793459	793459	0	0	9
scaffold1	793481	793481	0	0	5
scaffold1	793482	793482	0	0	7
```

To keep things simple I would suggest you simplify the workflow somewhat to that things are not getting too convoluted:

1. Get Bismark v0.19v.1
2. All the trimming in your Step 1 and Step 2 can be accomplished with the following command in Trim Galore:
`trim_galore --paired WGBS_R1.fastq.gz WGBS_R2.fastq.gz`
3. Align the trimmed reads against your SNP-modified reference genome (usually writing out unmapped reads and treating them in SE mode doesn't add a lot to the final dataset, but it makes the workflow much more complicated)
4. In case you really want to pursue the PE + SE route you can then run the methylation extractor on each file separately, and then run `bismark2bedGraph -o out CpG*` (no merging of the bam files is required for this.

(As a side note, Trim Galore as well as Bismark does not need unzipping of any files, this will save you a lot of time).

Could you just run this workflow and see if you are still seeing weird things in IGV? I suggest comparing the output in SeqMonk so you know if IGV got it wrong :)

I hope this helps in any way. Cheers, Felix

**Comment by dansapozhnikov** [comment]
Thank you Felix. I don't know why the data does not align to the Cs I sent you. It should only be off by a single base pair.

I will try your workflow immediately and let you know what happens!

**Comment by dansapozhnikov** [comment]
Hi Felix,

So I've done your workflow and have obtained the same type of IGV display discrepancy.
The methylation percentages in the bedgraph are virtually identical (obviously a little different because of no singles). 

I tried to view in SeqMonk but it does not seem to have any capability to view methylation (even C or T SNPs) without the Bismark coverage file.

It's hard for me to believe that the genome is on average 50% methylated as is displayed in IGV, but at the same time, reads are reads - if it says there is a certain amount of Cs and Ts there, is that not true? Or could there really be an encoding issue?

Thanks for the help.

Dan

**Comment by FelixKrueger** [comment]
Hi Dan,

I agree with you that a 50% methylation is very suspicious, or more generally if you ever encounter 0, 50 or 100% in any biological experiment most likely something fishy is going on...).

SeqMonk does, despite its name, not use any of the underlying sequence but works solely with mapped coordinates. SeqMonk's forward and reverse read data model has been specifically exploited for BS-Seq data to display and calculate with methylated (forward strand, red reads) and unmethylated (reverse strand, blue reads) cytosines, so the coverage file, or also the extracted methylation call files, are the native methylation input data in SeqMonk.

Having said that, SeqMonk is capable of importing the BAM reads in the orientation the reads have (where the red and blue would mean the read mapping orientation), and also importing the methylation data separately, or in addition to the reads. Since the reads seem to agree perfectly with the BAM files, and the methylation data in SeqMonk agrees perfectly with the coverage files, my guess is that IGV is getting something muddled up (probably the FLAG value?).

I would suggest you pick a very small region with a manageable number of reads, say 2-4, and really extract out the reference sequence as well as the read sequences and draw them out on a sheet of paper (or in Powerpoint etc.). From the read IDs in the BAM file you can grep out the sequences from the original FastQ files if needed (with e.g. `zcat  file_R1.fq.gz | grep -A 3 READ:ID:lane:tile:x:y: > single_read.fq`). This might help because BAM files are formatted so that reads are displayed as forward strand reads all the time, but reverse reads will obviously be reverse complements thereof. (If you have non-directional or PBAT alignments it will get a little more complicated...).

This should very quickly tell you what you should trust, and we don't have any reason to believe that it would be SeqMonk or a coverage file. If you could post your example here it might help others with a similar issue in the future. I will be on holiday for a while from tomorrow, so if you could find the issue soon I could still take a look :P

**Comment by dansapozhnikov** [comment]
Sorry, I'm confused by this:
"_Since the reads seem to agree perfectly with the BAM files_, **and the methylation data in SeqMonk agrees perfectly with the coverage files**, my guess is that IGV is getting something muddled up (probably the FLAG value?)."

I am not understanding how SeqMonk is calculating methylation independently of Bismark or what you mean by reads agreeing with the bam file.

**Comment by dansapozhnikov** [comment]
OK, I've done as you said about the FASTQ, except I did not go for a region with a manageable number of reads because I wanted a typical example - not sure if this was a stupid decision. I am having trouble conceptualizing this. I have reduced the information to reads from two strands, but am stuck now trying to figure out how to make the second group align to the forward strand:
![image](https://user-images.githubusercontent.com/41095622/44283509-9c56e000-a22c-11e8-8fbf-69702aa01af7.png)

Do you know how to convert that second group so that it aligns by coordinate with the first?

**Comment by dansapozhnikov** [comment]
OK, so I don't think I explained this quite well.
Here, I extracted the reads that map to a certain cytosine with samtools view.
Then I converted to fastq format with samtools fastq.
Then I extracted just the sequences with another bash command.

Then, I had four groups of sequences corresponding to the four possible strands/orientations. Then I reverse complemented a bunch to reduce it to four groups. 

I do not believe the top group is actually aligned by coordinate to the top group. It is just the program finding the best possible alignment based on sequence similarity but what you see there are actually top and bottom strands in possibly incompatible orientations.

**Comment by dansapozhnikov** [comment]
So I am wondering how to resolve this by coordinate so I can look at one position and make conclusions, as you did with position 96.

I am not too familiar with working with top and bottom bisulfite-converted strands and figured you might know a good way to do this.

**Comment by FelixKrueger** [comment]
Hi Dan, 

oh wow that is yet another convoluted workflow :) I am pretty sure you can't do that because none of the tools you are using are natively suited to work with bisulfite data. It might just about work if you just use Read 1 in single-end mode, because Read 1 can either align to the top strand or the bottom strand, just like normal DNA. I am sure this would yield the same results as the Bismark coverage files or SeqMonk.

As soon as you take read 2 of paired-end files in as well you are asking for trouble, because technically the R2 looks either like an alignment to the strand that is complementary to the top strand, but **is not the bottom** strand (CTOT), or it is complementary to the bottom strand (CTOB, but it is **not the top strand** either). These concept of these strands simply don't exist in a standard DNA- (2 strands only) world, so the `FLAG` values for these reads look like the ones on the bottom strand, even though they are just complements of the top/bottom strands.

It is important to understand that after bisulfite conversion the original top and bottom strands lose their complementary nature. I am now absolutely convinced that you are just looking at artefacts from using tools that are not meant to handle bisulfites converted reads. If you want to see what the methylation looks like in your samples of interest I would really recommend the coverage files/SeqMonk route: it only takes a few minutes and just works :)

**Comment by dansapozhnikov** [comment]
Do you see how the first group aligns to the "ref" - the reference forward strand from the genome? I have tried to make the second group align with the bisulfite-coverted reverse-complement, complement, reverse of the that same "ref" sequence and nothing seems to align. I have tried to change the order to first reverse-complement/reverse/complement and then bisulfite convert the "ref" strand and still no luck. I cannot figure out how to logically resolve this.

**Comment by dansapozhnikov** [comment]
So are you saying that if I take CTOT or CTOB there is no logical way to perform an _in silico_ reverse-complement/complement/reverse combined with _in silico_ bisulfite conversion to obtain the top strand?

**Comment by FelixKrueger** [comment]
Again, I can only repeat what I suggest above. If you would extract 1 or 2 read pairs from the FastQ files (not involving any samtools or BaM to FastQ conversion tools that introduce errors), get the genomic sequence of that region from Ensembl, and put down the sequences to the places that the Bismark BAM files tell you it will all make sense.

Bisulfites-Seq is super confusing, even for me after all those years. I can send you some slides with more examples of how read alignments are performed, but this would have to wait until after I am back from holidays (will fly out in a few hours). For the time being you can just rest assured that Bismark is handling all the confusing parts for you, all you need to do is look at % methylation values and see how this answers the biological questions you have.

 Regarding your CTOT/CTOB question: Yes there is a logical way to do the transformations, but neither Samtools nor IGV will help you there and you would have to write your own scripts to do all that (or you just save yourself a nice weekend and let Bismark do the work for you. I will nevertheless try to come up with a quick example in the next post (which will also be my last one as I need to pack a suitcase... )

**Comment by dansapozhnikov** [comment]
OK thanks Felix, I do trust that it is fine, it's just I was looking for a logical way to convince by boss that this is the case :)

**Comment by FelixKrueger** [comment]
4
    OT   TTTCGTTTTTTAGAGAGAGAGGAGAGA
    CTOT AAAGCAAAAAATCTCTCTCTCTCTCTC

If you look at this example and we assume the R1 aligns in forward direction and R2 in reverse orientation. R1 would get a methylation call at position 4, and Bismark will do a C to T lookup. Because Bismark knows that R1 aligned to the OT strand, it will then perform a G to A lookup in R2 some 22 positions into the read (the read from the sequencer starts with CTCTCT....). So in this case we need to do a G to A lookup at a position that is a C on the top strand.

R2 will get a FLAG value in the BAM file that *looks* like it is a reverse read (in fact the FLAG value will say: 1) I am Read 2 of a Pair, 2) I am part of a proper pair, 3) I align in reverse orientation, 4) my parter aligns in forward orientation). As you can see, all these attributes are technically correct, and they are exactly the same you would have in a normal DNA alignment, but for the methylation calling this is very relevant because we don't do methylation calls at bottom strand Cs, but Gs. Again, this is because this read is a technical copy of R1, and **not** the bottom strand as such. 

It is this concept that will do your head in every single time you think about it. If your boss has any further questions I'd be happy to Skype to her/him when I am back from the hols. All the best, and enjoy the data analysis! Over and out. Felix

**Comment by jeremycfd** [comment]
Hi @FelixKrueger,

I came here planning to ask about this very same problem, so I'm somewhat relieved that I'm not the only person finding discrepancies between the results of bismark_methylation_extractor and viewing the bam files with IGV. Since your comments to others in this thread have been that introducing additional processing steps between mapping and methylation extraction can cause these problems, I'm not sure if my workflow is causing the problem or if I'm still getting confused about the read orientations.  Currently, after mapping I merge bam files with samtools (to accommodate the fact that the same library is sequenced on multiple sequencers and that we want to maintain that information in the bam files), then I use Picard to remove duplicate reads, and then to get things back in the correct order I use samtools to sort on read name. Should we avoid doing -any- manipulations/cleaning of the bam files before using the methylation extractor, or are these sorts of things support?

Thanks!

**Comment by dansapozhnikov** [comment]
Hey @jeremycfd I just wanted to say that Felix was absolutely right and there is probably just some encoding error in the flag values that prevents IGV from displaying it properly. Looking at the bedgraph/coverage files, the pattern of methylation makes perfect logical sense. 

I tried to do no extra manipulations and still could not view them. 

I think the bottom line is you cannot view the aligned reads properly on IGV. If you're interested in viewing methylation on a browser, your only options, I think, are to view a bedgraph file on IGV or the coverage file that is outputted by methylation extractor on SeqMonk.

On as separate note, I am not sure if your workflow works: 
1. You should probably be using the deduplication script that is supplied with Bismark - no sorting is required after and the file is directly used in methylation extractor.
2. I don't think merging is necessary. You can run methylation extractor on each set and then combine them by using both as input to the bismark2bedgraph module.

That way you minimize the potential disruptions caused by external scripts/programs.

I think @FelixKrueger will give you much better answers when he returns from vacation, but just wanted to let you know my two cents

**Comment by jeremycfd** [comment]
Thanks Dan. Am going to toy around with this a bit. Everyone around here uses IGV for viewing DMR bams, so I guess I need to convince them to change.

**Comment by FelixKrueger** [comment]
Hi both,

I think you have already answered everything correctly, I just wanted to add a few comments. 

The Bismark pipeline is designed to work as a single stream-lined workflow from start to finish, including deduplication, extraction etc. In theory it should be possible to add additional steps using third party tools, as long as they are carried out properly. For example external deduplication must ensure that duplicates are not only flagged as such but are also removed from the files. 
Also, paired-end files must not drop single reads or get the read pairs out of sync. The same applies for merging BAM files: as was mentioned before, `samtools merge` must be carried out with the flag `-n` so that the reads are merged name sorted (otherwise you might get mix-ups or read IDs at file transitions). Alternatively one can use `samtools cat` which simply concatenates Bismark BAM files and thus keeps read pairs in sync. Merging the same files of the same library from several runs is indeed recommended for deduplication purposes. This can be done either i) at the FastQ file level, ii) at the BAM file level (see above), or iii) using `deduplicate_bismark --multiple` which treats multiple BAM files as the same library.

And yea, IGV seems to have problems with the fact that there are 4 different strands in bisulfite seq, I don't think you can really blame it though because it is kind of a niche application.... Let me know if you are still having any additional problems. Cheers, Felix
