### ISSUE TITLE
Random error during pipeline

### ISSUE THREAD

**Issue by AdrianS85** [FelixKrueger/Bismark#201]
https://github.com/FelixKrueger/Bismark/blob/809759d5de7a5737cc74a85bdf4b882ed9b1d1c9/bam2nuc#L64

Hello!

I noticed wierd behavior of bam2nuc tool. While working in Singularity-Ubuntu18.04 and performing pipeline written in nextflow (here is the pipeline: https://github.com/AdrianS85/varia/blob/master/RRBS.nf) I am getting code 1 errors during bam2nuc run (nextflow error output: https://github.com/AdrianS85/varia/blob/master/error_nextflow_bam2nuc). Despite the error, the output file is correctly generated (but of course my pipeline crashes). 
If I am interpreting Nextflow message correctly, the "error" happens somewhere in `generate_nucleotide_report` function. 
I think this also happens with bismark2summary - Im not sure, because I did not reproduce the error. It happend once and because it is the last step of the pipeline and it produces proper output, I just ordered nextflow to ignore it.

Any ideas?
Best
Adrian

EDIT: Sorry, forgot to add - it happens only to some bam2nuc runs. Files for other samples are produced without a problem. Also, the same file that "errored" before, when run on its own in command line works perfectly well (and produces the same output as "failed" run).

EDIT2: Exactly the same problem with main bismark tool

**Comment by FelixKrueger** [comment]
Hi Adrian,

I can see that this is a really annoying little bug... Given that the output of the Bismark modules that `terminate with an error exit status (1)` do actually finish alright, and produce the same files when run on the command line on their own, it looks likely that the problem is somewhere in the pipelining system.

Just to be sure I just checked all `bismark`, `bismark2summary` and `bam2nuc`, and the code doesn't contain any `exit 1` statements unless you call `--help`. So the error exit status is not produced by the Bismark code itself, but it might come from the perl interpreter itself? We have sometimes seen that errors can occur with pipelining systems when run on cluster environments because a) there are problems with resources (which is probably not the case here because everything finishes fine), or b) when there are timing issues, e.g. processes get ended by the cluster before buffers were flushed correctly etc. For Clusterflow, which we are using over here, we had to add a few `sleep()` statements at the end of runs to give the compute nodes enough time to clean up after themselves, flush buffers etc. Doesn't seem very elegant but seems to have worked in some cases.

Maybe you can forward or reference this issue on the NextFlow project page? Sorry I can't be of more help.

All the best, Felix

**Comment by AdrianS85** [comment]
Hey Felix!

The sleep command is actually very good suggestion, thank You! I will try it and write back the result : ]

**Comment by AdrianS85** [comment]
It took me a while, but I can report that analysis now works. I've added 10 seconds of `sleep` after finished run of every bismark instance, but what I think really helped is setting `/tmp/` directory to be writtable within the container. Do bismark use `/tmp/` for anything?
Anyway, perhaps my problem and solution will help somebody. Once again - Thank You Felix, for tips and writing the tool!

Adrian

**Comment by FelixKrueger** [comment]
Thanks for the feedback! Just for the record, Bismark doesn't use `/tmp/` anywhere.
There was a time when `bismark2bedGraph` used `sort`  in its default settings (which does use `/tmp/`), but we have quite early on replaced this with using the Bismark output directory which is given as `--dir` for sorting since this doesn't cause issues with running out of space (`/tmp` is often not very large...). All the best, Felix
