### ISSUE TITLE
Possible bug in positional argument <singles>

### ISSUE THREAD

**Issue by PoisonAlien** [FelixKrueger/Bismark#209]
Hi Felix,

This is the bismark usage for one of the fastq input modes:
```
<singles>         A comma- or space-separated list of files containing the reads to be aligned (e.g.
                         lane1.fq,lane2.fq lane3.fq). Reads may be a mix of different lengths. Bismark will
                         produce one mapping result and one report file per input file.
```
According to the usage, I passed two fastq files as an input (space separated). Below is the command,

```
bismark --non_directional \
--output_dir AS-277117-LR-38819/  \
--basename AS-277117-LR-38819 \
--rg_id AS-277117-LR-38819 --rg_sample AS-277117-LR-38819 -p 4 \
/bigdisk/ref_db/mm10/bismark/ \ 
clean/AS-277117-LR-38819/AS-277117-LR-38819_R1.fastq.gz \
clean/AS-277117-LR-38819/AS-277117-LR-38819_R2.fastq.gz
```
But it ended aligning only the last argument `(AS-277117-LR-38819_R2.fastq.gz)`. My pipeline ran for 20+ samples and it was the same for all the output. 

To confirm, I re-ran above command by separating files by comma instead of space, and it generated two separate bam files - just as it supposed to do.

Juts letting you know, it could be possible potential bug. 

Bismark version: v0.19.1

**Comment by FelixKrueger** [comment]
Hi PoisonAlien,

I just took a look at your command, and I think the problem is that you are trying to submit a list of files (either comma or space separated), but you are using the option `--basename` at the same time. This will result in every single name of your file receiving the very same output name, thus they will all overwrite each other and only the last sample will be present. So I suggest dropping `--basename` if you want to supply all sample names sequentially, or submit the data in a loop where the output file is derived from the filename somehow.

Alternatively, since the files end in `R1.fastq.gz` and `R2.fastq.gz`, don't you maybe want to run the samples in paired-end mode instead (options `-1` and `-2`)? And potentially trim the data with Trim Galore (`--paired`) before aligning?

Cheers, Felix

**Comment by PoisonAlien** [comment]
Yup, just figured it out. `--basename` is the culprit. If its not of trouble, could you please update the docs. Its not really clear for a novice user. A lot of time was spent on alignment - only to see that half of the reads were missing. 

Yes they are paired end data, already trimmed and cleaned. But since these are single cell, paired-end mode resulted in poor alignment mode, hence I am trying with single end mode.  

Thanks for quick response.

**Comment by FelixKrueger** [comment]
That makes sense. I have added some additional help text for `--basename`. If you clone the latest development version you should see it. Let me know if you require any further help down the line.

**Comment by PoisonAlien** [comment]
Hi Felix,
After alignment, I marked duplicates with `picard` and now I am running `bismark_methylation_extractor`. 
Does `bismark_methylation_extractor` ignores PCR duplicates? Because I see that Cytosine Methylation Report generated by bismark aligner and methylation extractor identical in terms of numbers. 

P.S: Sorry, I did not want to open a new issue for this.

**Comment by FelixKrueger** [comment]
The methylation extractor extracts methylation calls from all reads it is being fed, even if they were marked as duplicates by other packages such as Picard.

Bismark comes with its own deduplication module, called `deduplicate_bismark`, which is designed to identify - and remove - duplicate reads. The usage is simply:
```
deduplicate_bismark --bam file.bam
```

I hope this helps. Best, Felix

**Comment by PoisonAlien** [comment]
Got it. Wasn't aware of  `deduplicate_bismark` as I was trying everything starting with `bismark`.  I will read the docs properly. 
Thank you for quick and helpful response.

**Comment by FelixKrueger** [comment]
You're very welcome.
