### ISSUE TITLE
bismark_methylation_extractor: --no_overlap

### ISSUE THREAD

**Issue by josesovaz** [FelixKrueger/Bismark#213]
Hello Felix,

I have one doubt about how methylation_extractor works using the parameter: --no_overlap vs              --include_overlap. In my specific case I have targeted sequencing, and the overlap between read1 and read2 exists (the target sequenced region is as short as the length of the read, so the overlapping region is big). 

What is exactly the difference (in terms of methylation_extractor output) between using --no_overlap or --include_overlap?? I mean, If I add --include_overlap I will have in the output the same letter called twice (read1 +read2) for all the same overlapped positions? 

Example of my question:

read 1 --> position 1 --> z
read 2 --> position 1 --> z
read 1 --> position 2 --> Z
read 2 --> position 2 --> Z

And so on (...)

I would want to take into account the two reads (I suppose all the mate pairs will call the same letter, but if not? ) but without calling twice the same position in the output. 

Thanks,

Jose

**Comment by FelixKrueger** [comment]
Hi Jose,

Yes, Read 1 and Read 2 should report exactly the same methylation state for the same positio. Tis is because Read 2 is a mere PCR copy of Read 1. 
Some people investigated the question if they ever don't agree, and I believe the answer was that they disagreed in less that 0.001% of cases or so. In other words: Ever since we simply forget about the discrepancy between R1 and R2 as it is negligible, and run the extractor in its defaults setting (i.e. overlaps are only counted once).

**Comment by josesovaz** [comment]
Thank you for your answer Felix.

Regards,

Jose
