### ISSUE TITLE
merge CHG CHH and CpG cytosine.CX_report.txt files 

### ISSUE THREAD

**Issue by JennyHTLee** [FelixKrueger/Bismark#215]
Hi Felix,

What is the best way to merge CHG CHH and CpG cytosine.CX_report.txt files into one?

I ran bismark2bedGraph and coverage2cytosine independent of bismark_methylation_extractor, therefore ended up with 6 cytosine.CX_report.txt files (sometimes 4 or 5 as some OT files are empty).

Ideally I would like to imitate the output of running bismark_methylation_extractor with --bedGraph and --cytosine_report on, i.e. no duplicated positions. I would like to input it to the DMRCaller R pacakge published recently.

The cytosine.CX_report.txt files are 12-15 GB each, is it possible to avoid cat and sort? I have 100 accessions of a 1GB genome, so I am trying to be as memory/time efficient as possible ...

Please let me know if you have any suggestions, thank you very much!

Cheers,
Jenny

**Comment by FelixKrueger** [comment]
Hi Jenny,

I am not sure I completely understand what you are trying to accomplish exactly (especially the 100 accessions of a 1GB genome...).

- I think the easiest way would be to re-run the methylation extractor on the BAM files with `--bed --cytosine --CX` specified. Do you still have the (deduplicated) BAM files available?
- next  easiest would probably be to run bismark2bedGraph again, but using all context file as input rather than only one context/strand at a time. A command could look like so: 
`bismark2bedGraph --gzip -o SampleXY.cov C*SampleXY*.txt.gz`
As a next step you could use `coverage2cyosine ... --CX SampleXY.cov.gz` to get a single CX report. (by the way, I am not sure how the DMRCaller package will cope with a matrix of that size... maybe you want to limit yourself to just the CpG context?)
- Alternatively you could write a script that reads in all coverage files, stores all calls in a data structure, and then write out a single, merged coverage file. This could then be the input for `coverage2cytosine` as mentioned before.

Do you think one of these options would help?

Cheers, Felix

**Comment by JennyHTLee** [comment]
Hi Felix,

_- I think the easiest way would be to re-run the methylation extractor on the BAM files with --bed --cytosine --CX specified. Do you still have the (deduplicated) BAM files available?_

**I do have the BAM files, I ran them separately to save on resource usage as bedGraph and cytosine steps are not multithreaded (or have I misunderstood?). I mentioned the 100 samples and genome reference size just to relate to the analysis time taken. Just to fit with my server specifications, I ran multithreaded methylation extractor 1 sample at a time, then bedGraph and cytosine multiple samples at 
 once.**

_- next easiest would probably be to run bismark2bedGraph again, but using all context file as input rather than only one context/strand at a time. A command could look like so:_
_`bismark2bedGraph --gzip -o SampleXY.cov C*SampleXY*.txt.gz`_
_- As a next step you could use coverage2cyosine ... --CX SampleXY.cov.gz to get a single CX report. (by the way, I am not sure how the DMRCaller package will cope with a matrix of that size... maybe you want to limit yourself to just the CpG context?)_

**This is great, I was not aware that bismark2bedGraph can take multiple C\* files. I will go with this solution!**
**Ideally I would want to keep CHH and CHG as this is a plant species. But you are probably right because DMRCaller crashed with my average-sized test file :( I would have to figure this out ...**

Thanks for your prompt response and your time!

Cheers,
Jenny

**Comment by FelixKrueger** [comment]
Excellent, glad it helped!
