### ISSUE TITLE
bismark has output files at all and no first alignment 

### ISSUE THREAD

**Issue by Anguscgm** [FelixKrueger/Bismark#226]
I have run bismark on two datasets, one is my own and another the test_data.fastq followed with the Bismark package. However, while I did not encounter errors, I am unable to obtain the first alignment, and also the output files (test_dataset_bismark.bam and test_dataset_bismark_SE_report.txt) are not existent (not created instead of being empty).

The code I run of the two datasets, respectively, are:
1) My dataset
bismark --parallel 8 --genome /reserve01/data02gp/index -1 269B_L1_1.fq -2 269B_L1_2.fq
2) Testing dataset
bismark -u 10000 --parallel 8 --genome /reserve01/data02gp/index test_data.fastq

The logs are attached for reference.
[269B_L1.log](https://github.com/FelixKrueger/Bismark/files/2815729/269B_L1.log)
[test_dataset.log](https://github.com/FelixKrueger/Bismark/files/2815730/test_dataset.log)

I have checked most, if not all, similar issues on GitHub and Biostars, but still unable to solve the issue.

Note:
- My Bismark is of version 0.20.0, bowtie2 of version 2.3.4.3 and samtools of version 1.9. Bowtie2 and samtools are properly placed in PATH.
- I am running on Linux
- My genome reference is downloaded from Ensembl, GRCh38 whole genome (ftp://ftp.ensembl.org/pub/release-95/fasta/homo_sapiens/dna_index/Homo_sapiens.GRCh38.dna.toplevel.fa.gz)
- I believe my hardware used are much more than enough to satisfy the hardware requirement
- I have placed the fastq files in the current working directory, as the Bismark guide has noted.
- I have tried re-running bismark_genome_preparation just in case the genome reference is corrupted, but the problem is not solved, and there is no apparent change to the files.
- I have read issues #34 and #165 which appeared to be similar problems but still cannot solve the issue.

I would be grateful if anyone who has encountered something similar to shed some light on the issue. Please kindly let me know if any more information is necessary.

Thank you very much!

**Comment by FelixKrueger** [comment]
Dear @Anguscgm,

Both your log files contain the following line:

`Forking unsuccessful. Proceeding using a single thread only`

It appears that something is preventing the program from getting forked, e.g. platform incompatibility (like Windows), or possibly your cluster environment is not allowing programs to spawn additional instances of itself? 

Checking the code, it would appear that Bismark is not in fact continuing with as a single thread (as indicated), but instead simply `die`. I probably intended to carry on using a single thread but never actually did that. Having thought about it just now, we thought it is probably to leave in the `die` statement so that users see that something is fundamentally not working. Instead, I have now changed the text to:

```
[FATAL ERROR:] Forking unsuccessful. This normally means that something is fundamentally not working with the fork command. Please run again without the --parallel option, or ask your system admin to look into this.
```

This is the first time I hear about this happening, so I can't really tell you how to fix it exactly. Changing the command to

```
bismark --genome /reserve01/data02gp/index -1 269B_L1_1.fq -2 269B_L1_2.fq
```
should do the trick, i.e. losing the option `--parallel 8`. Alternatively you would need to investigate why your system does not allow the `fork` command to take effect...

**Comment by Anguscgm** [comment]
Dear @FelixKrueger ,

Thank you very much for your prompt response!

I shall try and update to this issue as soon as possible.

**Comment by Anguscgm** [comment]
Thank you for the solution.

It did solve the problem. I am also able to run the --multicore argument after some help from my system admin.

**Comment by FelixKrueger** [comment]
I'm glad to hear that! Out of interest, do you know what caused the issue? Cheers, Felix

**Comment by FelixKrueger** [comment]
Thanks for that extra information. Felix
