### ISSUE TITLE
writes out all the alignments for sequence with multiple alignments

### ISSUE THREAD

**Issue by Shicheng-Guo** [FelixKrueger/Bismark#23]
Added new option --ambig_bam --multiple for Bowtie2-mode only, which writes out a single all the alignments for sequences with multiple alignments to a special file ending in .ambiguous.bam.

**Comment by FelixKrueger** [comment]
Do you mean that Bismark is erroneously writing all alignments to a the file instead of just a single one?

**Comment by Shicheng-Guo** [comment]
No. I mean. Bismark only output one alignment randomly. I want to output all the possible alignments.  Can you add a option to achieve it?

**Comment by FelixKrueger** [comment]
I am afraid this is nothing we are likely to add as an option because it would be hugely more time consuming and the output if not likely to be very useful to many. If you wanted to get a list of all alignments to any strand you could run Bowtie 2 separately to the CT and GA converted genomes (can be found inside the Bisulfite_genome folder) and merge the output.

**Comment by Shicheng-Guo** [comment]
Thanks Felix, Yes, you are quite right. I have tried the process you told to me. Yes. there will be more than 30 alignment for some reads and I do will be cost lots of time. Thanks. 

`bowtie2 -x ~/db/aligndb/hg19/bismark/Bisulfite_Genome/CT_conversion/BS_CT ZNF154.fastq`

We can use bowtie2 -a to do this by ourself. 

Many thanks.

**Comment by FelixKrueger** [comment]
Ecellent.
