### ISSUE TITLE
deduplicate_bismark : error Failed to determine read and genome conversion from line: 

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [FelixKrueger/Bismark#237]
Hi,
    I used the bismark to remove duplication in my three BS-seq samples. But only one have this error. 
![image](https://user-images.githubusercontent.com/46480129/53852779-25353d80-3ffe-11e9-90f5-f8334fce3026.png)

    I'm not sure when I made some mistakes. Could you please help me ?
    Thanks in advance.
Best wishes.
Yu Liu

**Comment by FelixKrueger** [comment]
The line you show in your screenshot indicates that the BAM file is truncated in the middle of the line (and therefore misses the read and genome conversion fields. Are you using the latest version of Bismark? I am just asking because it should attempt to check whether the file is truncated, and bail out right at the start.

So you need to go back to the alignment step, and see if that finished correctly (is there a complete alignment report?). Alternatively, maybe the file got truncated during a copying procedure?

**Comment by ggoodstudydaydayup** [comment]
Thanks a lot, I align it once again and find the reason. There was a mistake in the first alignment and no error report in my nohup.out .

**Comment by FelixKrueger** [comment]
Excellent, glad it got sorted.
