### ISSUE TITLE
Question about sam/bam flag 

### ISSUE THREAD

**Issue by sunshine-lp0** [FelixKrueger/Bismark#241]
Hi Felix,

There is a problem that has bothered me for a long time. 
![image](https://user-images.githubusercontent.com/33354198/54732329-25246880-4bce-11e9-9db6-a55be9e948cc.png)

Why flag "179,131,67,115" can be proper alignment? Are read 1 and read 2 in different orientation？ I don't understand why this is proper alignment though they mapped wrong orientation.

Best，

**Comment by FelixKrueger** [comment]
I assume that you are asking a question regarding the 'old' FLAGs Bismark used before v0.8.2 (i.e. prior to 2013)?

The answer to that is that the FLAG values we used initially had to be a compromise of what is effectively happening, and what the SAM FLAGs allow you to express. 
- one the one hand, the alignments we paired-end and proper alignments, as this is the way alignments are carried out (thus we set those bits in the FLAG tag)
- one the other hand, let's assume a top strand alignment, then R1 would technically align to the `OT` strand, and R2 to the `CTOT` strand. This is a valid, proper paired-end alignment, but the problem is that both R1 and R2 are informative for the top strand only, and *do not* carry any information for the OB strand. Thus, the orientation were set to `++`, or `--`.

Since this kind of FLAG value is a kind of kludge, we changed the values some 6 years ago to:

```
                  default                         old_flag
                                       ===================              ===================
                                       Read 1       Read 2              Read 1       Read 2

                              OT:         99          147                  67          131

                              OB:         83          163                 115          179

                              CTOT:      147           99                  67          131

                              CTOB:      163           83                 115          179
```

Now technically, this is yet another kludge, as the paired-end reads are **not** on the reverse strand in classical DNA terms, but on the complementary strand of one of the usual DNA strands. Since this is a concept that only exists for bisulfite experiments, we just have to live with it one way or another. I hope this answers your question?

Cheers, Felix

**Comment by sunshine-lp0** [comment]
Exactly! 
"Both R1 and R2 are informative for the top strand only, and do not carry any information for the OB strand."
"The paired-end reads are not on the reverse strand in classical DNA terms, but on the complementary strand of one of the usual DNA strands."
I understand it but sometimes i'm woolly-minded. :)
Thank you very much! That's help me a lot. :)

**Comment by sunshine-lp0** [comment]
I'm sorry, Felix.
I think FLAG value in v0.20.1 should be like this:
![image](https://user-images.githubusercontent.com/33354198/56074803-1a36af80-5deb-11e9-9084-e9638b8f2260.png)

So is there something wrong with this picture you wrote above?
![image](https://user-images.githubusercontent.com/33354198/56074830-9204da00-5deb-11e9-97e4-9a715be0add8.png)


And I want to ask another question: How can I judge if read2 is forward strand or reverse strand when read2 flag is 163? It can be OB(ref-) or CTOB(ref+). I have some issues with dealing with bam file using Pysam tool. And I have checked that a paired-end reads: read2 flag was 163 and it mapped to ref-, meanwhile, read1 flag was 83 and it mapped to ref+.

I  dont't known if I've made myself clear. Look forward your reply.
Thanks very much!

**Comment by sunshine-lp0** [comment]
In my method, read2 is OT/OB. So when read2 flag is 163, it's OB and it aligns to ref-. So corresponding read1 is 83, it's CTOB and it aligns to ref+.
Okay, I think i understand that in the bismark userguide:
![image](https://user-images.githubusercontent.com/33354198/56074997-f6c13400-5ded-11e9-9879-2fd7b0d1facc.png)

But if I want to use Pysam tool to deal with bam file, should I change the falg values? what can I do? 
Look forward your help.
Thanks, Felix!

**Comment by FelixKrueger** [comment]
I am not exactly sure this is something I can help you with I am afraid. We can just quickly go over the the example you posted above, R1 having a FLAG of 83, R2 having a FLAG of 163 (OB read-pair):

FLAG 83 for Read 1 means:
- read is paired
- read mapped as proper pair
- read is first in pair (R1)
- read is reverse strand

It is *this Read (1)* that gives the read pair its general orientation, namely an alignment to the reverse strand (= OB).

Flag 163 for Read 2 means:
- read is paired
- read mapped as proper pair
- read is second in pair (R2)
- mate is reverse strand

If you would take this in isolation, it would mean that this read aligns to the CTOB strand (if mapped in single-end, non-directional mode). The read is not mapped in single-end, non-directional mode however, so it needs to be regarded as R2 of R1, which is the read giving the entire pair its orientation. Also, while CTOB alignments look like forward strand alignments, they are really forward looking alignments that align to the reverse complement of the _reverse_ strand, which means the reference is still the reverse strand. 

Does this help at all?

**Comment by sunshine-lp0** [comment]
I thought I've understood your explanations above. When CT/OB strand is R1 which gives the entire pair its orientation, It's the situation you said above. 

But I still want to confirm my process.
**Q1:**  In my method, CT/OB strand is R2 which governs the orientation of the entire alignment, CTOT/CTOB strand is R1, so i used "--pbat -1 R1.fastq.gz -s R2.fastq.gz".  Am I right?

**Q2:** I got a bam file after mapped with "--pbat -1 R1.fastq.gz -s R2.fastq.gz". In this bam file, Flag 163 for Read 2 means that it aligns to the reverse strand. FLAG 83 for Read 1 means aligns to the reverse complement of the reverse strand, which look like forward strand alignments. **(Refer to the below)**

![image](https://user-images.githubusercontent.com/33354198/56107341-43387b00-5f78-11e9-9df2-4720012f8727.png)

Thanks very much!

**Comment by FelixKrueger** [comment]
**To your Q1:** 
with `CT/OB`, do you mean `OT/OB`? And no, it is always R1 that governs the orientation of the entire alignment, R2 is simply a reverse-complemented copy of whatever R1 is (generated in a PCR reaction).

Nevertheless, CTOT gives methylation call information for the top strand (albeit in the opposite direction of an OT alignment), and CTOB yields information for the bottom strand (albeit in the opposite direction of an OB alignment).

**To your Q2:**
In the Bismark output BAM file, Read 1 of a CTOB alignments gets a FLAG of 163, and not 83 as in your table from above. 
FLAG 163 for Read 1 is supposed to indicate that it is not the reverse strand as such, but the reverse complement to the reverse reads, which here mean: CTOB. As mentioned above, in order to achieve this the FLAG values for R1 and R2 needed to be kludged in some way, and we have done this by giving R1 the FLAG of "second in pair", and R2 the FLAG of "first in pair".

This had to be done so that in a genome browser such as SeqMonk, both OT and CTOT reads appear as forward reads (as they are informative for the top strand), and both OB and CTOB reads appear as reverse reads (as they are both informative for the bottom strand). If we were to change the values to what you are suggesting the orientation of the reads would be exactly opposite of what you would expect, and for non-directional libraries you would get a mix of forward and reverse (looking) alignments for OT/CTOT or OB/CTOB reads, which would confuses people even more. 

So again, we have to make some compromises here, because the FLAG system is not made to deal with 4 strands of DNA but just the *ordinary* 2 strands. 

Having said all that, for all modules in Bismark the FLAG value is really just cosmetic and aims to please people who like to look at their reads in a genome browser. Most of the downstream Bismark tools work with a combination of `Read Conversion` and `Genome Conversion` anyway, sp they do not rely on the FLAG values in that regard. 

I hope this helps?

**Comment by sunshine-lp0** [comment]
Felix… I want to cry …
According to my primer design, my read2 data is OT/OB strand, my read1 data is CTOT/CTOB strand.  What arguments should I use to do alignment？

Only when i use —pbat -1 R1.fastq -2 R2., the mapping efficiency can reach 50%.

**Comment by FelixKrueger** [comment]
The easiest way to find out what you need is to draw it out on a sheet of paper. Alternatively, to make see what is in your data, you can just run the alignments in `--non_directional` mode and see if you get alignments for either OT and CTOT, or OB and CTOB, etc. It may also help you to look at your aligned reads in a genome browser, e.g. SeqMonk, to see if there is directionality at the regions you tried to amplify. e.g. if the region is a forward feature, do you get forward alignments exclusively? Or a mix? But yea, it is confusion, no doubt about that....

**Comment by sunshine-lp0** [comment]
If I use --non_directional mode, the mapping efficiency is only about 0.8%.

Below is the experimental principle, we catch the "CGCGCGG" region of OT/OB. After sequencing, read2 data is OT/OB strand which has "CGCGCGG" at the beginning position. 

![image](https://user-images.githubusercontent.com/33354198/56180527-45640d80-603c-11e9-99b4-cf34866f00af.png)

**Comment by FelixKrueger** [comment]
Oh that looks complicated... Without going into it too much, here are a few comments:

- `--pbat` is merely a subset of `--non_directional` (namely the CTOT and CTOB alignments). This means that `--non_directional` should certainly yield at least the same mapping efficiency as `--pbat` alignments, and not much less. Either the non-directional mode creates extremely similar sequences at different locations that will now make the reads map to two different positions with identical alignment scores (which will get the sequences discarded; you can check this in the alignment report under 'ambiguous alignments'), or you have changed something else that will result in the sequences not mapping as well as in `--pbat` mode.
- before mapping, you need to make sure that you remove the anchor sequence, the UMI and the RS sequence from your R2 before you start the alignments. Ideally, you write the UMI into the read ID of the FastQ reads (simply append them with `:UMISEQUENCE` to the read ID), because then you can use the option `--barcode` of `deduplicate_bismark` to factor the UMIs in for deduplication.
- Couldn't you try to do single-end mapping of just R1 to see if that aligns well on its own? It looks like R1 does not carry any artificial sequences, therefore it should map fine on its ow, and should also give you the very same strand assignments as PE alignments.

**Comment by sunshine-lp0** [comment]
(1)I used "--pbat --single_end ...R1.fastq.gz" or "--single_end ...R2.fastq.gz", the mapping efficiency both can reach 50%. 

![image](https://user-images.githubusercontent.com/33354198/56190448-ce8b3c80-605c-11e9-8e77-d051709daf7d.png)

https://github.com/FelixKrueger/Bismark/issues/235

(2) And I want to ask if this is right in the user guide of v0.20.0?
"Default" is what we use now in the v0.20.0? 
![image](https://user-images.githubusercontent.com/33354198/56190605-232eb780-605d-11e9-8aed-44cd46214381.png)

Thanks, Felix.

**Comment by FelixKrueger** [comment]
(1) So when you align in SE mode you get 50% mapping (what happens when you align SE mode with `--non_directional`?), but the efficiency drops to 0.8% in paired-mode? I am confused...
(2) Yes, default is the one that is being actively used.

**Comment by sunshine-lp0** [comment]
Yes, Felix. If I align SE mode with --non_directional, I can also get about 50% mapping, which did four times alignment.  But FLAG in R1 bam file have issues, which represent opposite meaning for flag itself. FLAG in R2 bam file is ok.

**Comment by FelixKrueger** [comment]
Yes, again SE mode the FLAG is 0 for OT and CTOT, and 16 for OB and CTOB to indicate the strand for which the alignment is informative.

**Comment by sunshine-lp0** [comment]
![image](https://user-images.githubusercontent.com/33354198/56194328-5117fa00-6065-11e9-9490-7dbff2247a19.png)

"--pbat" mode only launch two alignment threads to the CTOT and CTOB strands. So I used "--pbat" to map R1 data, which are PCR product  of OT/OT, i.e. CTOT/CTOB.  Am I wrong?

**Comment by FelixKrueger** [comment]
That could be right, but it really also depends on the circumstances at which the Illumina adapters are ligated on, and in which direction etc... If the non-directional mode tells you that (almost) all of your alignments come from the CTOT and CTOB strands, then you are right to use `--pbat` mode.

**Comment by sunshine-lp0** [comment]
Dear Felix,

Q1: Flags in bismark bam files are different from standard SAM format flags (ordinary DNA alignment flags). Right?

Q2: Can you help me to explain the two flag in the red frame?
![image](https://user-images.githubusercontent.com/33354198/56207663-e1fcce80-6081-11e9-8449-e59c952a1367.png)

Thanks a lot!

**Comment by FelixKrueger** [comment]
Q1: the single-end flags are exactly the same. We try to keep the PE flags as close to a natural 2-strand DNA template as possible, but since there are 4 strands in bisulfite-seq and the SAM format only caters for 2 ('standard' DNA), it isn't possible to be mean exactly the right thing in both the SAM Flag and the real  situation. I would probably describe the OT and OB strands as pretty much the same as for ordinary DNA alignment flags (even though the reverse-mate in the SAM format is not equal to the reverste strand in real-life).

Q2: Haven't we talked about this in quite some detail above? Here it is again:

**FLAG 83 for Read 1 means:***

- read is paired
- read mapped as proper pair
- read is first in pair (R1)
- read is reverse strand
It is this Read (1) that gives the read pair its general orientation, namely an alignment to the reverse strand (= OB).

Flag 163 for Read 2 for CTOB reads was suggested by you, and I don't agree with it as I have explained above. Using this value would orient the read pair in a forward direction, but the read pair is informative for the reverse strand. Thus, Read 2 of CTOB alignments should get a value of 83, and not 163.

**Comment by sunshine-lp0** [comment]
Thank you so much for your patience! :)
I think I should be deep in meditation...
Thank you~

**Comment by FelixKrueger** [comment]
Sounds like a good plan :) Let me you if you have any additional questions upon re-emerging [from the mediation]. Cheers, Felix

**Comment by sunshine-lp0** [comment]
I’m sorry about the confusion above. To be clearer and also to save your time, could you please answer the following questions with just one word each?
1. Which one is right? Picture 1 or Picture 2?

Picture 1:
![image](https://user-images.githubusercontent.com/33354198/56217705-46298d80-6096-11e9-8785-0ccfed911e01.png)


Picture 2:
![image](https://user-images.githubusercontent.com/33354198/56217667-314cfa00-6096-11e9-9e5b-653cb0f81149.png)


2. Before getting the sequencing data, we know whether R1 is OB/OT strand or CTOT/CTOB strand (Suppose the library is directional). Yes / No?

3. Only based on paired-end alignment bam files, we can’t determine which of OT/OB/CTOT/CTOB strands the R1 and R2 align to. Yes / No?

4. The relationship between OT and CTOT is not equivalent to the relationship between R1 and R2 (in the context of paired-end sequencing). Yes / No?

**Comment by FelixKrueger** [comment]
1) The one in `bismark --help` (Picture 2)
2) (Ideally) yes
3) No
4) yes

**Comment by sunshine-lp0** [comment]
Hi Felix,
Just few words question again~
Only based on the bam file, which read is R1?   
![image](https://user-images.githubusercontent.com/33354198/56258707-0f3d9100-6103-11e9-9ca9-a99f12b7c7a0.png)

**Comment by FelixKrueger** [comment]
R1 is always the first one reported. `GA/CT/GA -> CTOB`

**Comment by sunshine-lp0** [comment]
Flag 163 in SAM Format means:

read is paired
read mapped as proper pair
read is second in pair
mate is reverse strand

So, in this read pair, R1 needs to be regarded as "read is second in pair"?

**Comment by FelixKrueger** [comment]
correct.

**Comment by sunshine-lp0** [comment]
Hi Felix, 
I really appreciate your patience and thank you so much for your valuable reply all the time.
Here are "Yes / No" questions again...  (If the answers of six questions are all "Yes", I think I've realized my issues and could solve it in my project.)

1. In the bam file, we can not judge R1/R2 based on FLAG value. We judge it based on the order. 
It is R1 which always the first one reported. It is R2 which the second one reported.
Yes / No?

2. In the bam file, R1 is corresponding to OT/OB/CTOT/CTOB strand and OT/OB/CTOT/CTOB information. 
Yes / No?

3. In the bam file, R2 is just the reverse complement of the R1, and R2 is corresponding to OT/OB/CTOT/CTOB information, but not corresponding to OT/OB/CTOT/CTOB strand itself.
Yes / No?

4. In paired-end "--pbat" mode, R1 will align to CTOT/CTOB. R2 is just the reverse complement of the R1. R2   can not be called OT/OB. Because the descriptions of CTOT/CTOB aim at the read pair or aim at R1 which governs the orientation of the entire alignment. 
Yes / No?

5. In paired-end "directional"(default) mode, R1 will align to OT/OB. R2 is just the reverse complement of the R1. R2   can not be called CTOT/CTOB. Because the descriptions of OT/OB aim at the read pair or aim at R1 which governs the orientation of the entire alignment. 
Yes / No?

6.In paired-end "--non_directional" mode, R1 will align to OT/OB/CTOT/CTOB. R2 is just the reverse complement of the R1. R2   can not be called OT/OB/CTOT/CTOB. Because the descriptions of OT/OB/CTOT/CTOB aim at the read pair or aim at R1 which governs the orientation of the entire alignment. 
Yes / No?

All the best!

**Comment by FelixKrueger** [comment]
Yes to all! 







Finally :)

**Comment by sunshine-lp0** [comment]
Thank you very much!!!!! :)

**Comment by sunshine-lp0** [comment]
![image](https://user-images.githubusercontent.com/33354198/56346001-aaae2f00-61f3-11e9-9393-a1a978e6fe71.png)

Hi Felix, I'm sorry that I met a new problem.

In this picture, R1 FLAG is 147. GA/CT/CT --> CTOT.
Why the value of column is 74? I think it should be -74.
