### ISSUE TITLE
some question about bismark outputs

### ISSUE THREAD

**Issue by sridewi1** [FelixKrueger/Bismark#245]
Dear Felix,

I have a few question about bismark and bismark methylation output.

1. after some bismark optimization using `-I 0 -X 1000` and `--score_min L,0,-0.4` I got a better mapping efficiency. But how far can I go with this parameter? In theory, I can use much less stringent score and got even better mapping efficiency, right?

2. I am analyzing RRBS experiment data (library preparation: Premium RRBS kit from Diagenode). So theoriticaly only regions with high CpG content would be enriched and sequenced. But why is the uniquely alignment rate only ranging between 38-66%? Was it the conversion efficency of the kit not as good, so we still have in some samples around 50% unaligned reads?

3. What is the difference between cytosine methylation and cytosine methylation after extraction? Could you please explain it? I never work with RRBS data before and still try to understand it. 

I hope you can help me with my questions. I am a big fan of your group's tools (FastQC, Fastqscreen, trimGalore, SeqMonk, and of course Bismark :)). Thank you and your group effort for awesome tools!

Cheers,
Dewi

**Comment by FelixKrueger** [comment]
Hi Dewi,

> after some bismark optimization using -I 0 -X 1000 and --score_min L,0,-0.4 I got a better mapping efficiency. But how far can I go with this parameter? In theory, I can use much less stringent score and got even better mapping efficiency, right?

In my experience, changing the `-X` parameter has normally no noticeable effect on the mapping efficiency because fragments typically are well under 200bp in length (which is a consequence of the harsh conditions of the bisulfite treatment). `-I 0` is the the default anyway. Finally, relaxing the `--score_min` function may indeed lead to (initially) higher mapping efficiencies (but alignment time will also go up...). You need to keep in mind though that this increase in mapping efficiency may also allow more errors to come through, and also more alignments to incorrect positions in the genome. Ultimately, if you relax the alignments too much the mapping efficiency will go down again as there might several places where sequences could go. `--score_min L,0,-0.4` is probably still a good compromise of accuracy and mapping efficiency.



> I am analyzing RRBS experiment data (library preparation: Premium RRBS kit from Diagenode). So theoriticaly only regions with high CpG content would be enriched and sequenced. But why is the uniquely alignment rate only ranging between 38-66%? Was it the conversion efficiency of the kit not as good, so we still have in some samples around 50% unaligned reads?

The mapping unique mapping rate is a primarily a function of (among others):
- appropriate trimming. Typically, `trim_galore --rrbs sample.fastq.gz` does the trick
- read length (the longer the better...)
- SE vs PE. Sometimes, PE libraries come with additional problems
- the quality of the library preparation
- contamination within the library. Especially for RRBS, sequencing facilities often add a spike-in of unconverted PhiX DNA (up to 50%!) to the sample to help with the base diversity during the base-calling process)


The conversion efficiency has nothing to do with the mapping rate, you should be able to map completely unconverted genomic DNA, or fully bisulfite converted sequences (or anything in between) with the same efficiency.



> What is the difference between cytosine methylation and cytosine methylation after extraction? Could you please explain it? I never work with RRBS data before and still try to understand it.

The difference between these two categories is that the first statistics in the HTML report are extracted from the alignment report, and the second set ("cytosine methylation after extraction") are extracted from the splitting report, i.e. after the methylation extraction step. If you ran `deduplicate_bismark` on the original BAM file you might have removed all duplicate read alignments, so in theory the values can be somewhat different (if the regions that were highly duplicated had a specific methylation pattern). In practice, they often look pretty similar.

For RRBS, you normally do not perform a de-duplication step (unless you used UMIs), so the numbers should really be identical for the mapping and extraction step.

I hope these comments help?

**Comment by sridewi1** [comment]
Hi Felix,

thanks for the prompt reply!

> In my experience, changing the -X parameter has normally no noticeable effect on the mapping efficiency because fragments typically are well under 200bp in length (which is a consequence of the harsh conditions of the bisulfite treatment). -I 0 is the the default anyway. Finally, relaxing the --score_min function may indeed lead to (initially) higher mapping efficiencies (but alignment time will also go up...). You need to keep in mind though that this increase in mapping efficiency may also allow more errors to come through, and also more alignments to incorrect positions in the genome. Ultimately, if you relax the alignments too much the mapping efficiency will go down again as there might several places where sequences could go. --score_min L,0,-0.4 is probably still a good compromise of accuracy and mapping efficiency.

I think I will stay with this score. You are right about the decreasing of sensitivity if a far too loosen parameter was used. 

> appropriate trimming. Typically, trim_galore --rrbs sample.fastq.gz does the trick

I indeed used `trim_galore` and the `--rrbs` option to trim my data before further processing it with Bismark. So I supposed 38-66% uniquely mapping rates are the best I can get for now.  

> read length (the longer the better...)

the read length is 75 bp and after the trimming between 20-74 bp. Would you suggest a longer sequencing read length, if I want to do another RRBS sequencing? Or is it depends on the organism and biological samples?

> SE vs PE. Sometimes, PE libraries come with additional problems

So, would you always suggest to do single-end sequencing for RRBS?

> contamination within the library. Especially for RRBS, sequencing facilities often add a spike-in of unconverted PhiX DNA (up to 50%!) to the sample to help with the base diversity during the base-calling process)

![grafik](https://user-images.githubusercontent.com/24940249/55338727-9a7f1b80-54a1-11e9-9ec4-b734b8431990.png)
I did checked the data using Fastq Screen and could not find any major contamination within the library (in my opinion), so I supposed I can ruled out this point.

> The difference between these two categories is that the first statistics in the HTML report are extracted from the alignment report, and the second set ("cytosine methylation after extraction") are extracted from the splitting report, i.e. after the methylation extraction step. If you ran deduplicate_bismark on the original BAM file you might have removed all duplicate read alignments, so in theory the values can be somewhat different (if the regions that were highly duplicated had a specific methylation pattern). In practice, they often look pretty similar.

![grafik](https://user-images.githubusercontent.com/24940249/55339124-5b9d9580-54a2-11e9-8173-2d422ed6806e.png)
I did not run `deduplicate_bismark`, just as you suggested for RRBS data. But strangely I did not got identical cytosine methylation pattern before and after the extraction. Or is it normal that these numbers behave this way? 

> I hope these comments help?

Yes it does help a lot! Thank you so much! I really appreciate it 

cheers,
Dewi

**Comment by FelixKrueger** [comment]
A few comments: 
- to see if the paired-end experiment is bringing down the mapping efficiency, you could try to just align R1 on its own (in default mode, or also adjust the score_min option). If that number is considerably better than PE, R2 might introduce a problem (does the Diagenode kit have any specific needs when it comes to processing?)
-  RRBS samples generally have a lot of fragments between 40 and ~150bp. So going up massively with the read length, as well as paired-end alignments might not results in a lot of extra data. If I had a choice, I would probably go for single end, 125-150bp run these days.
- did you run FastQ screen in `--bisulfite` mode?
- another factor that may affect the after-extraction values that I forgot to mention is the overlap detection and removal (as soon as reads overlap in, the overlapping portion of R2 is not taken into account). Sorry for not mentioning this in the first place.

**Comment by sridewi1** [comment]
> to see if the paired-end experiment is bringing down the mapping efficiency, you could try to just align R1 on its own (in default mode, or also adjust the score_min option). If that number is considerably better than PE, R2 might introduce a problem (does the Diagenode kit have any specific needs when it comes to processing?)

the mapping efficiency using only R1 and adjusted score_min indeed delivered even higher alignment rates for almost all my samples with exception for one sample, which the alignment rate goes down by 1%.

> did you run FastQ screen in --bisulfite mode?

I am not sure why, but the `--bisulfite mode` doesn't really work for me. FastQ screen could not find any reference index for bisulfite data.

> another factor that may affect the after-extraction values that I forgot to mention is the overlap detection and removal (as soon as reads overlap in, the overlapping portion of R2 is not taken into account). Sorry for not mentioning this in the first place.

the cytosine methylation score before and after extraction score using only R1 reads delivered the identical scores just as you mentioned before. 

Thanks for your help!

**Comment by FelixKrueger** [comment]
FastQ Screen does not yet allow downloading bisulfite indexes, but I have opened a job for this already (https://github.com/StevenWingett/FastQ-Screen/issues/3#issue-404321918). Hopefully Steven will find some time over Easter to add this...

In the meantime, you could send me some files (the first 100K reads, FastQ, gzipped) via email and I can quickly run it over here.

**Comment by FelixKrueger** [comment]
We have followed this up via email, it is all looking pretting good.
