### ISSUE TITLE
0.22.0 has performance issues. 

### ISSUE THREAD

**Issue by yuqiu77** [FelixKrueger/Bismark#254]
I compared 0.22.0 vs previous versions on a WGBS test datasets.  Previous versions (from 0.18.1 to 0.21.0) could complete the analysis in less then 10 min with --parallel 4.  v0.22.0 took almost 2 hours.  I checked CPU utilization with top command, and the CPU utilization was very low.

**Comment by FelixKrueger** [comment]
Interesting you should say that, I was also under the impression that things were moving way slower than they used to... I will try to look into changes that were made just before I went on holidays, and will update here as soon as possible.

**Comment by FelixKrueger** [comment]
I believe the 'performance issues' are now resolved, can you please clone the latest development version and try again? If this works for you I will make a new hot-fixed release very soon. 

Apologies for the inconvenience.


PS: The issue was the placement of a single closing squiggly bracket `}`, which really should have included that one nasty sleep statement...

**Comment by yuqiu77** [comment]
I could confirm that the speed is back to normal with the latest version.  Thanks for the quick fix!

**Comment by FelixKrueger** [comment]
Thanks for the quick feedback. I'll try to make a new release soon.

**Comment by FelixKrueger** [comment]
Just to quickly mention that I have now made a new release featuring this fix: https://github.com/FelixKrueger/Bismark/releases.
