### ISSUE TITLE
The question about ambiguous reads

### ISSUE THREAD

**Issue by yinhm4** [FelixKrueger/Bismark#256]
Hi Felix,

I have a problem about the ambiguous reads. I want to get all of multiple alignment positions.
But I use the options --ambig_bam to run Bismark ,but it only can output one of multiple alignment positions. Is there a method to get all of multiple alignment positions？

Thank you very much for your help in advance.
Sincerely yours,
Kangqi Yin

**Comment by FelixKrueger** [comment]
Bismark does intentionally not output several different multi-mapping positions, because if we cannot be sure about where a sequence really came from we are also not confident to infer the alignments methylation state.

For cases where you simply wanted to know where a bisulfite converted sequence aligns to in the genome I have at some point created an experimental version of Bismark that allows you to output several different alignment positions: https://github.com/FelixKrueger/BismarkMultimappingLocations.

Note that this only works in single-end mode, and outputs BAM files for `--limit INT` alignments as they come straight from Bowtie 2, i.e. without performing any methylation calls. Is this something you might find useful?

**Comment by yinhm4** [comment]
It's useful for me. And I have two questions.
1.Does this method not support the parameter --parallel?
2.The bowtie2 parameter -a make the procedure run so slow. Could I change the parameter to -k ？

**Comment by FelixKrueger** [comment]
1. It almost certainly doesn't. It was really just a quick & dirty attempt to allow more than one ambiguous alignment which someone really needed to answer a question.
2. You could try changing that, I don't know if it would work the same way. But yes, looking for many repetitive alignments **is** slow...

**Comment by yinhm4** [comment]
I'm sorry to bother you again. First of all, thank you for your reply. And I want to ask you a question which make me confused.
In the link "https://github.com/zhanglabvt/BAM_ABS", I find they can get the ambiguous reads in SAM format (output of Bismark tool).  They can get ambiguous reads from the output of Bismark, which makes me very confused. I sent emails to the three authors asking how they got it, but no one replied to me. 
Do you know how they did it?
Thank you very much for your reply in advance.

**Comment by FelixKrueger** [comment]
I'm afraid I hadn't heard of this previously.

**Comment by yinhm4** [comment]
I see, thank you very much again.
