### ISSUE TITLE
sprintf in bismark2report misformatted

### ISSUE THREAD

**Issue by Jeltje** [FelixKrueger/Bismark#258]
Extremely minor issue:

`Bismark-0.22.1/bismark2report`
line 170
 `my $time = sprintf ("%02d:%02d", $hour,$min,$sec);`
should probably be
 `my $time = sprintf ("%02d:%02d:%02d", $hour,$min,$sec);`
to avoid getting the warning `Redundant argument in sprintf `

**Comment by FelixKrueger** [comment]
That's very interesting, because I saw the warning message just yesterday when we were running our training course on a virtual machine. But when I just tried to reproduce it on our cluster, there just isn't any warning whatsoever!

In any case, thanks for the suggestion, I have now changed the code and can confirm that the time stamp does now also include a seconds field.
