### ISSUE TITLE
Bismark need to be optimized to be faster on mapping 

### ISSUE THREAD

**Issue by whhyh1314** [FelixKrueger/Bismark#261]
Hi, Felix

Bismark is a very useful tool to do the methylation NGS sequences mapping.

I used the following parameter to align the raw data to hg19 genome sequence.
Bismark-0.17.0/bismark ./default/ --fastq   --multicore 2 -p 4 -o ./ --temp_dir ./temp  -1 R1_001.clean.fastq.gz -2 R2_001.clean.fastq.gz

The PE sequences' size is 61M (reads). It took 192 minutes to complete the mapping. While It took only 90 minutes when I using bwa-meth do the mapping. I think bismark is too slow, do you have any advices to speed up except increase the number of threads ?

**Comment by FelixKrueger** [comment]
Hi @whhyh1314, 

In my experience, the following factors may (somtimes hugely) impact the mapping speed:
- whether or not the input data is of high quality and adapter trimmed (this is why we recommend stringent adapter trimming with Trim Galore) 
- the repeat content of the genome/library
- the mapping stringency (more or less the more stringent, the quicker)
- especiallly for paired-end libraries: the type of library, e.g. whether there are many unmappable fragments due to chimeric reads etc (PBAT, single-cell)

Bismark is almost certainly not programmed very efficiently, but given all the other variables affecting the speed this is probably not the biggest problem.

In your case, I would:
- upgrade to the latest version (v0.22.1 is the latest, yours is > 2 years out of date)
- use Trim Galore for trimming (a default command `trim_galore --paired R1.fq R2.fq` is normally enough; if you have some special type of library additional parameters might be advisable: https://rawgit.com/FelixKrueger/Bismark/master/Docs/Bismark_User_Guide.html#ix-notes-about-different-library-types-and-commercial-kits)
- in my experience, the option `-p 4` has hardly any noticable positive effect on the overall speed, while using `--parallel 4` instead of `--parallel 2` should cut the time roughly in half while using the same number of cores

At the end of the day you probably spent days or even weeks preparing the samples and geting the libraries sequenced, and will most likely spend days or even weeks analysing the data, so wether or not you 'lost' a few minutes in between doesn't appear like a deal breaker to me....

**Comment by FelixKrueger** [comment]
Closing this issue as there are no further comments.
