### ISSUE TITLE
 bismark_methylation_extractor only for methylation of CpG

### ISSUE THREAD

**Issue by Shicheng-Guo** [FelixKrueger/Bismark#27]
the current version of  bismark_methylation_extractor could call methylation level for CpG, CHG and CHH. Do you think we can call methylation for CpG only? can we have such option? 

the result for CHH and CHG is too large, sometimes we can not output them if we don't need them, therefore, we really need an option to omit these two file.

**Comment by FelixKrueger** [comment]
You can specify `--gzip` to compress the output to ~10% of the uncompressed size, and later remove unwanted files with a command such as `rm CH*` if you really want to get rid of them. I am afraid there won't be a special option to look at CpG context exclusively because disk space is not a primary concern anymore these days...

**Comment by moqri** [comment]
Thanks for your great tools!
I would also like to mention that since most of the current epigenetic research focuses on CpGs, it would be great to add this feature to only return CpGs similar to the "-n" parameter in DNMtools
