### ISSUE TITLE
Bismark calculate bs rate

### ISSUE THREAD

**Issue by soleilll** [FelixKrueger/Bismark#287]
Hello！
I have some problem when i calculate the bs rate.I combined the genome.fa and oligo.fa.Then make index and bismark mapped.I try to extract the reads mapped to the oligo.fa,but there were no reads succeeded.So i can't get the bs rate(C/C+T).
Is the oligo 60bp too short to map?
Can you help me with the problem?Thank you very much!

**Comment by FelixKrueger** [comment]
Hi @soleilll 

I assume the oligo sequence you have is an oligo you spiked into your experiment before doing the bisulfite conversion, e.g. the 5mC/5hmC oligos CEGX used to distribute?

Generally, if you use Bismark in end-to-end mode, which is the default, then you can only align to a 60bp oligo sequence if the read length in your experiment was 58bp or shorter. Longer reads can by definition not map fully. You have a few options here:

- you could and (probably should) pad the oligo sequence with `NN` on either side, so that a full match to the sequence doesn't get removed because the sequence is too short to extract the cytosine context of the first two and last two base pairs

- in case your read-length exceeds 60bp, you could hard-trim the sequences to 60bp (e.g. with Trim Galore, option `--hardtrim5 60`)

- instead of hard-trimming you could also try to align the reads in `--local` mode to allow softclipping. Like hard-trimming, this will most ikely also require the padding with `Ns` on either side

You don't have to repeat the alignments to the 'genome+oligo' reference, but you can just index the oligo sequence itself. Alignments to just this sequence should be lightning fast.

Let me know how you get on.

**Comment by soleilll** [comment]
Hi@FelixKrueger 

yes, is oligos used to distribute.

I have tried to add the --local parameter, but it said "Unknown option: local". Then i use bowtie2 to map my RNAseq data to test the setting --local, it works well. So i wonder is there any problems when bismark calling the bowtie2? 

I'll try the other two options later.

Thank you very much!!!

**Comment by FelixKrueger** [comment]
Which version of Bismark are you using? Try upgrading to the latest version (v0.22.2), or clone the development branch.
