### ISSUE TITLE
Mbias plot looks strange

### ISSUE THREAD

**Issue by soleilll** [FelixKrueger/Bismark#291]
Hi,
    I'm looking at M-bias for my samples(RRBSdata) and i'm noticing that the CpG line keeps going up.
But i noticed that the lines of  other's M-bias plot  always go stable and flat with some ups and downs.
I don't know whether this trend is right or wrong.
   My trim data:
`trim_galore --phred33 --illumina --stringency 3 -e 0.1 --gzip --length 35 --rrbs --fastqc -o /public1/data/lixinjie/trimmeddata/  --paired /public1/data/lixinjie/Rawdata/M7-WYWPE19011597/M7-WYWPE19011597_R1.fq.gz /public1/data/lixinjie/Rawdata/M7-WYWPE19011597/M7-WYWPE19011597_R2.fq.gz`
 My map data:
`bismark --bowtie2 -N 0 -L 20 --quiet --un --ambiguous -o /public1/data/lixinjie/mappeddata/ /public1/data/lixinjie/mm10genome/ -1 /public1/data/lixinjie/trimmeddata/M7-WYWPE19011597_R1_val_1.fq.gz -2 /public1/data/lixinjie/trimmeddata/M7-WYWPE19011597_R2_val_2.fq.gz`
![image](https://user-images.githubusercontent.com/48310080/70146657-99ac2280-16dd-11ea-8338-8510cd62a872.png)
![image](https://user-images.githubusercontent.com/48310080/70146774-db3ccd80-16dd-11ea-8798-effc8bd96992.png)
 And when i use another code to extract the methylation information, i got an even weirder plot.
`bismark_methylation_extractor -p -comprehensive --bedGraph --counts --cytosine_report --buffer_size 20G --ignore 3 --ignore_r2 1  --genome_folder /public1/data/lixinjie/mm10genome/ /public1/data/lixinjie/mappeddata/M7-WYWPE19011597_R1_val_1_bismark_bt2_pe.bam -o /public1/data/lixinjie/mappeddata/mbiasadjust/`
![image](https://user-images.githubusercontent.com/48310080/70147112-95343980-16de-11ea-8aef-88a5190d3a55.png)
![image](https://user-images.githubusercontent.com/48310080/70147160-aa10cd00-16de-11ea-9794-d7ee5a7798b1.png)

Thanks,
April

**Comment by FelixKrueger** [comment]
A couple of comments:

Trim Galore step
 `--stringency 3` is not advisable, as you it will potentially miss out on quite a few potential adapter read-through events, and hence each of those reads will also include filled-in basecalls at the 3' end of reads. Did you perform the fill-in reaction with fill methylated or unmethylated cytosines?

```
trim_galore --rrbs --paired M7-WYWPE19011597_R1.fq.gz M7-WYWPE19011597_R2.fq.gz
```
May I ask which versions of Trim Galore and Bismark you were using?

I agree that it is slightly worrying to see a trend of the average methylation increasing towards the 3' end of a reads, but I am afraid I don't really have an explanation for why this happens. What I find even a bit more worrying though is the fact that Read 1 and Read 2 disagree in their methylation levels by ~20%. Maybe this is not so relevant though, because you seem to have done paired-end 150bp sequencing, and most reads underwent pair-overlap removal, so the overall number of calls of R2 is generally quite low (as is expected for RRBS).

While looking at the number of calls in your reads (just R1) again, I noticed that the calls seem drop buy around half from the 5' end to the 3' end. This would indicate that many fragments are very short, and maybe those reads are located firmly within CCGG rich areas of the genome, i.e. CpG islands hich are generally lowly methylated. Reads that extend out for the full length already start getting into genomic territory that is no longer lowly methylated? This might also explaing why R2 is generally more highly methylated...

I am also not sure whether should remove the first positions in your reads, as they are kind of by definition interogating a CpG position. We would probably not ingore any positions for RRBS data, and just continue to analyse the data as it is.

**Comment by Soleilcode** [comment]
Hi Felix,

Thanks for your advise!

I'm using bismark version v0.22.1 and  trim_galore version 0.6.4_dev.And i think we perform the fill-in reaction with just normal unmethylated cytosine. As the RRBS protocl says, after MspI treat, then fill in automatically.

`--stringency 1`(as default)will it be too strict?And i wonder if a few potential adapter will make difference to the methylation calling output?Is the impact serious for downstream analysis?

Exactly, we did the PE 150, so after the reads underwent pair-overlap removal, the overall data still usable, right?

Thanks,
April

**Comment by FelixKrueger** [comment]
Regarding the stingency. I don't think it will be a deal breaker, but why include artificially unmethyated calls when you can avoid it?

I would indeed just go ahead and analyse the results.

**Comment by soleilll** [comment]
I rerun the data with --stringency 1, but  it does not seem to have improved much.
Is this result due to data quality?Will it improve if I increase q to 30(I'm trying)?I've searched some pages but I  have not found anything like this.This made me feel very confused and frustrated.
QAQtears……

**Comment by FelixKrueger** [comment]
I don't think playing with the absolute thresholds will change fundamentally what the experiment/library  is you have in front of you. I would now just take the data as it is, and proceed further to downstream analysis.
