### ISSUE TITLE
merging bam files

### ISSUE THREAD

**Issue by demis001** [FelixKrueger/Bismark#299]
@FelixKrueger 

I am using `bismark_methylation_extractor` for the first time. Would you please give me a guideline how to proceed.
1. I did  a paired-end reads, a significant portion of each lane does not have a paired mates. I did a three steps alignment, one as pair two as single end. 

```
bismark -n 1 --genome $GENODIR --multicore 28 -1 ${SAMPLE}_L001_R1_val_1.fq.gz   -2  ${SAMPLE}_L001_R2_val_2.fq.gz -q -N 1 -p 4  --bowtie2 --dovetail --maxins 500
      bismark -n 1 --genome $GENODIR --multicore 28  ${SAMPLE}_L001_R1_unpaired_1.fq.gz    -q -N 1 -p 4  --bowtie2
      bismark -n 1 --genome $GENODIR --multicore 28  ${SAMPLE}_L001_R2_unpaired_2.fq.gz    -q -N 1 -p 4  --bowtie2
```
I have seen the parameters for  `bismark_methylation_extractor` and it says, the SE/PE options is mandatory. How should I proceed at this stage. Do I have to merge the above three bam files -> dedup -> and run as PE ? What is the best way to handle this?

2. I have many individuals for cases and controls, I remember years ago I merged all cases to  a single bam files and controls to single bam files and call methylation status with different application. Does this  approach works in bismark? what is the best approach? I used this approach to overcome the coverage issue. 

Best,
@demis001

**Comment by demis001** [comment]
Found your comment in one of the older issue.

"In case you really want to pursue the PE + SE route you can then run the methylation extractor on each file separately, and then run bismark2bedGraph -o out CpG* (no merging of the bam files is required for this."

Looks like, DMRfinder handles the second part of the question.

@demis001

**Comment by FelixKrueger** [comment]
Hi @demis001,

This kind of question has come up before in some form or another, so I might nick some answers from previous issues.

If you have a mix of single-end and paired-end files you need to align, deduplicate and methylation-extract them separately as you suggested. The paired-end alignments as well as Read 1 in SE mode may be aligned in default conditions, i.e. directional mode. Since Read 2 is complementary to Read 1, R2 needs to be aligned using the option `--pbat`.

PE and SE data also needs to be methylation extracted in their respective modes. Once the methylation extraction is complete you can then combine the output together for the `bismark2bedGraph` step by simply giving it all the `CpG*` context calls from both the PE and SE runs. 
Assuming you have SE and PE alignments of only a single sample in a directory, the command for this would be:

```
bismark2bedGraph --buffer 10G -o output_file CpG*
```

You could alternatively also merge the two SE BAM files, and deduplicate and methylation extract them together.

Here are some comments for to your command lines:
```
bismark -n 1 --genome $GENODIR --multicore 28 -1 ${SAMPLE}_L001_R1_val_1.fq.gz   -2  ${SAMPLE}_L001_R2_val_2.fq.gz -q -N 1 -p 4  --bowtie2 --dovetail --maxins 500
```
- Which version of Bismark are you using (the current one is 0.22.3)? `-n 1` should not be a valid option anymore.
- `--bowtie2` is the default. So so are `-q`, `--dovetail` and `--maxins 500`
- I would normally advise against `-N 1` as it takes more resources and slows things down considerably. The default (`-N 0`) is norally fine.
- Bismark on its own uses 1 core for the methylation processing, plus 2x1 core for the Bowtie 2 alignments. Plus a few cores for processing gzip-streams. If we forget all those compression (Samtools) and unzipping processes for a moment, then a single Bismark will at least use 3 cores and say 12GB of RAM for a human genome alignment. By giving each Bowtie2 thread 4 cores, and using `--parallel 28` your resource requirement will be at the very least  (1 + (2 x 4) ) * 28 = **252 cores**, and **340GB** of RAM per file.
 I personally have never tried out such dimensions...

A somewhat toned down command that does the same (albeit a bit slower) would then look like this:
```
bismark --genome $GENODIR --multicore 2 -1 ${SAMPLE}_L001_R1_val_1.fq.gz   -2  ${SAMPLE}_L001_R2_val_2.fq.gz`
```

If you really wanted to do the PE/SE combination, you would need to run the Unpaired file 2 in --pbat mode, as it aligns to the CTOT and CTOB\ strands only. The command line would then be:

```
bismark --pbat --genome $GENODIR ${SAMPLE}_L001_R2_unpaired_2.fq.gz
```

To your question 2: I would probably generate individual coverage files for each sample in the first place, and then merge the coverage files into a larger group afterwards. This way you can choose whether you want to treat the samples individually or as pseudo-bulk.

**Comment by demis001** [comment]
@FelixKrueger 

Thank you for the detail explanation! I am using the current version (v0.22.3).  I found the process requirement after submitting many task to the same cluster two days ago and changed later to 10 instead of 28. I have a couple system with big memory above 500GB.  I have added the default parameters on purpose, probably read the wrong version manual from old install in different terminal and added the "-n" option. I tried bismark in 2015 and found it was much slower that time. Then, I decided to use BSMAP followed by MOABS. The reviewer asked me a lot of question about the application and these time decided to shift to Bismark, as it known well in the community. 

It looks like you are not checking all parameter passed. It disregarded and did the run with this:

` Bismark was run with Bowtie 2 against the bisulfite genome of /data1/genome/hg38_r87/bismarkindex/ with the specified options: -q -N 1 --score-min L,0,-0.2 -p 4 --reorder --ignore-quals --no-mixed --no-discordant --          dovetail --maxins 500`

I will adjust in the future, for now it is almost done and has no impact in the alignment.

**Comment by FelixKrueger** [comment]
That's true, it doesn't hurt to be explicit. I reckom `-n` gets treated as `-N`, but in theory that would have been the option for Bowtie1.

I hope Bismark will work for you this time, let me know if there is anything I can do to help.

Cheers, Felix

**Comment by demis001** [comment]
Sure do. I see I have to rerun the R2 unpaired with --pbat option

**Comment by demis001** [comment]
One more question. Are you suggesting to merge the R1 unpaired bam file and R2 unpaired bam with pbat  files -> dedup and extract CpG's? 

No dedup required for PE bam file right?

**Comment by FelixKrueger** [comment]
I would recommend:

- PE alignments, deduplication (it auto-detects the PE mode) methylation extraction (also auto-detects)
- you can either merge both SE BAM files, then deduplicate and extract, or run them each individiually. The latter just results in more files. (Unless there is really a substantial amount of singleton reads I would probably leave the SE out anyway, as it just makes things less straight forward).

Once all that is complete, you can run a single `bismark2bedGraph` on all `CpG*` output files.

**Comment by demis001** [comment]
Thanks! don't close this issue at least for a week. I may ask you other question down the line. I am processing more than 100 patient samples right now (tone of data).

**Comment by FelixKrueger** [comment]
A week has passed, I hope all has worked well? Stay safe!
