### ISSUE TITLE
How to understand --ignore --ignore_r2 --ignore_3prime  --ignore_3prime_r2

### ISSUE THREAD

**Issue by Shicheng-Guo** [FelixKrueger/Bismark#30]
Hi Felix, 

Supposing that, in the beginning, my raw read length is 90bp (Fastq). After trim_galore and quality trim, different reads will have different length (maybe from 50-90bp). In such situation, what does it mean for the following parameters: 
--ignore  5
--ignore_r2 5
--ignore_3prime 10
--ignore_3prime_r2  10

apply ignore operations to each reads in the input bam, isn't it? 

Best regards,

**Comment by FelixKrueger** [comment]
Yes, the ignore operations will still ignore bases from the start or end of the reads even if they have varying read lengths. 

For the future may I suggest you drop me a line directly (felix.krueger@babraham.ac.uk) if you just want to ask a question rather than opening a new issue here on Github? Cheers, Felix
