### ISSUE TITLE
OB strand and methylation call query

### ISSUE THREAD

**Issue by prasundutta87** [FelixKrueger/Bismark#307]
Hi,

I have understood how OT strand aligns to the C-T genome and how a methylated C is considered (based on the diagram in the paper). How to infer the OB alignment? I am somehow not able to wrap my head around the G-A conversion and alignment.

Furthermore, does bismark take depth and base qualities into consideration while performing the methylation calls? If yes, what is the threshold? I did not find these details anywhere.

Regards,
Prasun

**Comment by FelixKrueger** [comment]
OB alignments, and thus G-A conversions, are pretty much the same thing as for the top strand, just in a reverse complemented fashion. I am afraid I won't be able with the wrapping your head around it, this is something everyone has to experience themselves :) 

And no, there are no additional criteria for methylation calls. Calls are made for each read separately (thus no coverage depth thresholds), and since we expect users to feed in good quality data only, where adapter and quality trimming has been performed already, no further filters are applied

**Comment by prasundutta87** [comment]
Haha! I expected that reply, Felix. I understand. The strand stuff gets pretty confusing at times. Just wanted to confirm its again the C-C match thats seen, right?

Thanks for the information on the thresholds bit. :-)

**Comment by FelixKrueger** [comment]
Yes, C/T on the top strand, as well as C/T on the bottom strand (which is equivalent to treating the top strand in a G/A manner).

**Comment by prasundutta87** [comment]
Thanks a lot, Felix! It has been very helpful.
