### ISSUE TITLE
Identical read appears twice in bam file

### ISSUE THREAD

**Issue by HyunjunNam** [FelixKrueger/Bismark#309]
Hi Felix,

I am looking at bam file from bismark by using IGV.
I found that some of reads appear twice in exact same genomic position.

Please find attached screen shot below,
![image](https://user-images.githubusercontent.com/56126961/74061525-06bf8b00-49a1-11ea-94c8-4d32897402c5.png)

As you can see here, first and second read are exactly same, and they were from same read in original fastq file.

I've attached detail info of these two reads,

info of first read
```
Hap name: null
Dist: 0
Read name = NS500518:189:HK7K3AFXY:1:21204:13037:19141:UMI_AATG_GCCT_1:N:0:TAACTTGGGC+GTCGTGAATC:AATGGCCT
Read length = 133bp
----------------------
Mapping = Primary @ MAPQ 42
Reference span = chr3:37,034,461-37,034,593 (+) = 133bp
Cigar = 133M
Clipping = None
----------------------
Mate is mapped = yes
Mate start = chr3:37034460 (-)
Insert size = 133
Second in pair
Pair orientation = F2R1
----------------------
XG = GA
NM = 34
XM = ......z......zx.hh.................z..xhh.......zxh..zx.......h.h....z
..z...........h........hhh.z.............x.zxh.hh......h.h..xhh

XR = GA
Hidden tags: MD<hr>Location = chr3:37,034,511
Base = A @ QV 36

Alignment start position = chr3:37034461
CCCATCACCCTCCAAAAACTCCACCACCAAATAACACTAAATCCACTCAAACCAAAAAACTAAAACCTCATCAACTTCCATCTTACTTCTTTTAAACATCATCCACATTCTACAAAAAACCACAAAAACAAAA
......z......zx.hh.................z..xhh.......zxh..zx.......h.h....z..z...........h........hhh.z.............x.zxh.hh......h.h..xhh
```

info of second read
```
Hap name: null
Dist: 0
Read name = NS500518:189:HK7K3AFXY:1:21204:13037:19141:UMI_AATG_GCCT_1:N:0:TAACTTGGGC+GTCGTGAATC:AATGGCCT
Read length = 133bp
----------------------
Mapping = Primary @ MAPQ 42
Reference span = chr3:37,034,461-37,034,593 (-) = 133bp
Cigar = 133M
Clipping = None
----------------------
Mate is mapped = yes
Mate start = chr3:37034460 (+)
Insert size = -133
First in pair
Pair orientation = F2R1
----------------------
XG = GA
NM = 34
XM = ......z......zx.hh.................z..xhh.......zxh..zx.......h.h....z
..z...........h........hhh.z.............x.zxh.hh......h.h..xhh

XR = CT
Hidden tags: MD<hr>Location = chr3:37,034,512
Base = C @ QV 21

Alignment start position = chr3:37034461
CCCATCACCCTCCAAAAACTCCACCACCAAATAACACTAAATCCACTCAAACCAAAAAACTAAAACCTCATCAACTTCCATCTTACTTCTTTTAAACATCATCCACATTCTACAAAAAACCACAAAAACAAAA
......z......zx.hh.................z..xhh.......zxh..zx.......h.h....z..z...........h........hhh.z.............x.zxh.hh......h.h..xhh
```

The header of them is identical..

What is the difference between these two read? (I ran 'deduplication_bismakr' on this dataset)

Interestingly, these two read appeared as one read in other bismark outfile such as 'CpG_OT_XXXX.txt'.

**Comment by FelixKrueger** [comment]
Hi @HyunjunNam 

My guess would be that you are looking at both ends of a paired-end alignment, where the top read is `Second in pair`, and the second read is `First in pair`. Both reads are exactly 133bp long, which probably means that the fragment you are sequencing is 133bp long, so R1 and R2 are both of the very same length (and assuming that you were running 2x150bp paired-end sequencing I would also assume that both reads had 17bp removed by the trimming process).

I am not sure why IGV is displaying the reads two times, as R1 and R2 of a read pair actually report on only a single fragment. It wouldn't be the first time though that IGV is having trouble displaying bisulfite reads, because for some read/genome conversions it just doesn't know how to handle them.

If you continue to deduplicate and methylation extract your reads, the Bismark methylation extractor would take all methylation counts of R1, but discard all of the calls from R2 as they are 100% redundant, and would thus introduce an unfair coverage of the region (as IGV seems to be doing).

You should be able to look for the read in the Bismark BAM file by simply piping the read to grep. This should should you exactly 2 lines in the BAM file.

`samtools view yourfile.bam | grep NS500518:189:HK7K3AFXY:1:21204:13037:19141`

Let me know if you still have any questions.

**Comment by HyunjunNam** [comment]
Hi Felix,

You are correct. I was ruunging 2x150bp paired-end sequencing, and I found exact 2 lines in the BAM file, when I searched by 'samtools view yourfile.bam | grep NS500518:189:HK7K3AFXY:1:21204:13037:19141'

Here is those 2 line from Bam file below,

```
NS500518:189:HK7K3AFXY:1:21204:13037:19141:UMI_AATG_GCCT_1:N:0:TAACTTGGGC+GTCGTGAATC:AATGGCCT   83      3       37034461        42      133M    =       37034461        -133    CCCATCACCCTCCAAAAACTCCACCACCAAATAACACTAAATCCACTCAAACCAAAAAACTAAAACCTCATCAACTTCCATCTTACTTCTTTTAAACATCATCCACATTCTACAAAAAACCACAAAAACAAAA        AAAEAA<A<<A<AAEEEEAEEEEA/EEEEEEEEEA<EEEEEE6E<<EAEEE6EEEEEEEEEEEEA6EEEEEEEEEAEA6EEEEEEEEEEEEEEEEEEEEEEEEEEAEEE6EEEEEEEEEEEE6EEEE/EEE/A   NM:i:34 MD:Z:6G6G0G1G0G17G2G0G0G7G0G0G2G0G7G1G4G2G11G8G0G0G1G13G1G0G0G1G0G6G1G2G0G0G0        XM:Z:......z......zx.hh.................z..xhh.......zxh..zx.......h.h....z..z...........h........hhh.z.............x.zxh.hh......h.h..xhh      XR:Z:CT XG:Z:GA
NS500518:189:HK7K3AFXY:1:21204:13037:19141:UMI_AATG_GCCT_1:N:0:TAACTTGGGC+GTCGTGAATC:AATGGCCT   163     3       37034461        42      133M    =       37034461        133     CCCATCACCCTCCAAAAACTCCACCACCAAATAACACTAAATCCACTCAAACCAAAAAACTAAAACCTCATCAACTTCCATCTTACTTCTTTTAAACATCATCCACATTCTACAAAAAACCACAAAAACAAAA        EEEEEE/EAEEEEEEEEEEEAEEEEEEEEEEEEEEEE/EEEEEEEE/EEEEA<EEEEEE<<EEEAE<AE/E6EAE/AEEEEA/6<<6/<EA<EEEEAEEEE/6<<EEA<</EEEEEEEEE/EAEEEEE/EEEE   NM:i:34 MD:Z:6G6G0G1G0G17G2G0G0G7G0G0G2G0G7G1G4G2G11G8G0G0G1G13G1G0G0G1G0G6G1G2G0G0G0        XM:Z:......z......zx.hh.................z..xhh.......zxh..zx.......h.h....z..z...........h........hhh.z.............x.zxh.hh......h.h..xhh      XR:Z:GA XG:Z:GA
```





I tried to search these same reads in fastq file of R1 and R2. Here is the result below,

R1
```
grep 'NS500518:189:HK7K3AFXY:1:21204:13037:19141' 5XXX_S1_R1_001_umi_modified.fastq -A 3
@NS500518:189:HK7K3AFXY:1:21204:13037:19141:UMI_AATG_GCCT 1:N:0:TAACTTGGGC+GTCGTGAATC:AATGGCCT
TTTTGTTTTTGTGGTTTTTTGTAGAATGTGGATGATGTTTAAAAGAAGTAAGATGGAAGTTGATGAGGTTTTAGTTTTTTGGTTTGAGTGGATTTAGTGTTATTTGGTGGTGGAGTTTTTGGAGGGTGATGGG
+
A/EEE/EEEE6EEEEEEEEEEEE6EEEAEEEEEEEEEEEEEEEEEEEEEEEEEE6AEAEEEEEEEEE6AEEEEEEEEEEEE6EEEAE<<E6EEEEEE<AEEEEEEEEE/AEEEEAEEEEAA<A<<A<AAEAAA
```

R2
```
grep 'NS500518:189:HK7K3AFXY:1:21204:13037:19141' 5XXX_S1_R2_001_umi_modified.fastq -A 3
@NS500518:189:HK7K3AFXY:1:21204:13037:19141:UMI_AATG_GCCT 2:N:0:TAACTTGGGC+GTCGTGAATC:AATGGCCT
CCCATCACCCTCCAAAAACTCCACCACCAAATAACACTAAATCCACTCAAACCAAAAAACTAAAACCTCATCAACTTCCATCTTACTTCTTTTAAACATCATCCACATTCTACAAAAAACCACAAAAACAAAA
+
EEEEEE/EAEEEEEEEEEEEAEEEEEEEEEEEEEEEE/EEEEEEEE/EEEEA<EEEEEE<<EEEAE<AE/E6EAE/AEEEEA/6<<6/<EA<EEEEAEEEE/6<<EEA<</EEEEEEEEE/EAEEEEE/EEEE
```

As you can see here, it has identical sequence with R2 read not R1. So, I guess the read that we can see in Bam file came from only R2, not R1. Am I right?

I am thinking that one of the reason why same reads were displayed two time is that I ran the Bismark on 'directional' mode, even though my library contains OT,OB, CTOT, CTOB. 

Do you think that 'non-directional'/'directional' modes can affect to result of BAM file?

Hyunjun

**Comment by FelixKrueger** [comment]
Hi Hyunjun,

Thanks for the additional details. It seems to be indeed as I suspected, that the read pair is a perfectly overlapping 133bp long fragment for both R1 and R2. In SAM format (and thus also in BAM format), reads have to be displayed relative to the top strand, which is the reason why the sequences look perfectly identical even though they are reverse complements in the FastQ files. Don't worry, this is perfectly normal.

Whether or not you need to run your libraries as directional or non-directional depends entirely on your library preparation method. As rule of thumb: if your Red 1 files are low in C content and high in T there is a good chance that the library is directional. Only if the level of C and G are the same in either reads, chances are that your libraries are non-directional. The mapping efficiency should be another clue: if you get good alignment rates in default (=directional) mode (of 670,70 or 80%), then the libraries are probably directional. If you are not sure you could send me a FastQC report of one of your files and I'd be happy to take a look.

Just as a word of warning: I think IGV is particularly unsuited to visualise non-directional alignments :)

But from what I see here, it all looks perfectly normal (maybe with the exception of IGV).

**Comment by HyunjunNam** [comment]
Hi Felix, 

Thank you for the detail answer. 
I think I am still little bit confused. The strand orientation  flags for these duplicated reads in Bam file are 83 and 163 respectively (please find them in my first comment), which means that those reads are OB/CTOB, not OT/CTOT. Then, the ` first in pairs`  is OB(R1) and the `second in pair` is CTOB(R2), but both of them are displayed relative to the top strand.  Am I correct?

And it doesn't happen all the time, but some time identical read from R1 and R2 can appear in IGV. My understanding is right?

Based on your suggestion, I've check the frequency of C and T in read 1 by using fastp report. As you can see below, the frequency of C was extremely lower than T.

![image](https://user-images.githubusercontent.com/56126961/74193662-9c128780-4c0c-11ea-8372-f62c5b1a051d.png)

And mapping efficiency was 78.9% from Bismark result, when I ran Bismark on default mode.
![image](https://user-images.githubusercontent.com/56126961/74193768-cd8b5300-4c0c-11ea-8605-803381732a44.png)

Then, I can consider my data as directional?

Thanks.
Hyunjun

**Comment by FelixKrueger** [comment]
The quick one first: your data is definitely directional, so you have done the right thing!

For paired-end data you need to consider both R1 and R2 as one single entity, rather than looking at them individually. If you read pair aligns with FLAGS 83/163, the main finding is that the fragment you are looking at came from the reverse strand. Internally, this means that R1 would formally align to the OB strand, which by the way give the read pair its overall mapping orientation. Read 2 is merely a PCR generated reverse complement of R1, and would technically align to the CTOB strand (as it is per definition the reverse complement of the OB strand) if were to align it in single-end mode. In paired-end data however, the strand of R2 is already taken into account during the mapping step, and it reports methylation states to the OB strand as well as R1 (they are really just copies of the very same fragment). 

In my opinion the R1 and R2 should never be treated or appear as two individual reads, and to be honest I have no idea why IGV is showing them in the first place. We personally don't use IGV ourselves, so I can't really give you any further information of what it does exactly. I personally am quite convinced that Bismark is doing the right thing here, and that the information you are getting out in the coverage file is correct. I'd just accept that this is a particularity of IGV....

**Comment by HyunjunNam** [comment]
Thanks, Felix. 
Your very detail explanation is always very helpful to understand the results!

**Comment by xixueyu96** [comment]
Hi Felix,

sorry to bother that, I encounter similiar but a bit different problem, too. I noticed the read name can be resulted from R1 & R2, which can be distinguished by the flag, but in my situation, I seem do have two identical reads produced by bismark.

the result of `samtools view .bam | grep` below (the top two records)
![image](https://github.com/FelixKrueger/Bismark/assets/138994149/a97d4de5-9b3d-4d24-9bfe-0c5b7ddacc1a)

the result of IGV below (the left top one and left bottom one)
![image](https://github.com/FelixKrueger/Bismark/assets/138994149/89284aa5-4289-4e55-b536-89a17a07f910)

session info:  Bismark-v0.22.3, bowtie2-2.3.5

parameters: `bismark --local --fastq --bowtie2 --non_directional --unmapped --phred33-quals`

It would be very helpful if you give some clues.

Thx, 
sherry

**Comment by FelixKrueger** [comment]
Hmm, I have never seen this before to be honest. Can you please do the following two tests:
1. Grep for that read ID in the FastQ files (with `-A 3` to get the entire FastQ read). Is there a chance that the read occurred twice in the input files? 
2. In case the read is present only once, can you extract the record (as in 1.) and align just this single read pair?

**Comment by xixueyu96** [comment]
Sorry, my bad😅. I followed the first test, and there're indeed two same record in my FastQ file.

Thank you for your prompt and detailed response~

sherry

**Comment by FelixKrueger** [comment]
Not to worry, good luck!
