### ISSUE TITLE
Question: Many more reads mapping to complementary strands than to original ones

### ISSUE THREAD

**Issue by OnlyHigh** [FelixKrueger/Bismark#313]
Hey Felix, 
Analyzing four libraries of WGBS-seq made with EpiTect Fast DNA Bisulfite Kit followed by the QIAseq Methyl library kit. For the analysis with Bismark, we first used the ```--directional``` flag which resulted in very low mapping rates, we decided to map them as ```--non-directional```. 

The issue/question is raised when all the libraries (find below are the summaries for each library) apparently map more to the complementary strands than to the original ones:
1. Is this related to the library preparation, to the mapping commands or both?,
2. Is there a necessary bioinformatic previous step that we're forgeting maybe? 

```
Bismark report for: L1-M1-10-t1.fq.gz and L1-M1-10-t2.fq.gz (version: v0.22.3)
Bismark was run with Bowtie 2 against the bisulfite genome of /home/larteag7/practica/meths/illumina/longipes/ with the specified options: -q -L 15 --score-min L,0,-0.2 -p 4 --reorder --ignore-quals --no-mixed --no-discordant --dovetail --maxins 900
Option '--non_directional' specified: alignments to all strands were being performed (OT, OB, CTOT, CTOB)

Final Alignment report
======================
Sequence pairs analysed in total:       42173399
Number of paired-end alignments with a unique best hit: 16926122
Mapping efficiency:     40.1%
Sequence pairs with no alignments under any condition:  19974713
Sequence pairs did not map uniquely:    5272564
Sequence pairs which were discarded because genomic sequence could not be extracted:    8

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:       2689575 ((converted) top strand)
GA/CT/CT:       5946091 (complementary to (converted) top strand)
GA/CT/GA:       5712190 (complementary to (converted) bottom strand)
CT/GA/GA:       2578258 ((converted) bottom strand)

```
```
Bismark report for: L2-M3-10-t1.fq.gz and L2-M3-10-t2.fq.gz (version: v0.22.3)
Bismark was run with Bowtie 2 against the bisulfite genome of /home/larteag7/practica/meths/illumina/longipes/ with the specified options: -q -L 15 --score-min L,0,-0.2 -p 4 --reorder --ignore-quals --no-mixed --no-discordant --dovetail --maxins 900
Option '--non_directional' specified: alignments to all strands were being performed (OT, OB, CTOT, CTOB)

Final Alignment report
======================
Sequence pairs analysed in total:       38758801
Number of paired-end alignments with a unique best hit: 15268471
Mapping efficiency:     39.4%
Sequence pairs with no alignments under any condition:  18618466
Sequence pairs did not map uniquely:    4871864
Sequence pairs which were discarded because genomic sequence could not be extracted:    2

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:       2286569 ((converted) top strand)
GA/CT/CT:       5352805 (complementary to (converted) top strand)
GA/CT/GA:       5347043 (complementary to (converted) bottom strand)
CT/GA/GA:       2282052 ((converted) bottom strand)

```

```
Bismark report for: L3-M1-20-t1.fq.gz and L3-M1-20-t2.fq.gz (version: v0.22.3)
Bismark was run with Bowtie 2 against the bisulfite genome of /home/larteag7/practica/meths/illumina/longipes/ with the specified options: -q -L 15 --score-min L,0,-0.2 -p 4 --reorder --ignore-quals --no-mixed --no-discordant --dovetail --maxins 900
Option '--non_directional' specified: alignments to all strands were being performed (OT, OB, CTOT, CTOB)

Final Alignment report
======================
Sequence pairs analysed in total:       45822302
Number of paired-end alignments with a unique best hit: 16791054
Mapping efficiency:     36.6%
Sequence pairs with no alignments under any condition:  23840578
Sequence pairs did not map uniquely:    5190670
Sequence pairs which were discarded because genomic sequence could not be extracted:    6

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:       2511874 ((converted) top strand)
GA/CT/CT:       6058049 (complementary to (converted) top strand)
GA/CT/GA:       5810411 (complementary to (converted) bottom strand)
CT/GA/GA:       2410714 ((converted) bottom strand)

```

```
Bismark report for: L4-M3-20-t1.fq.gz and L4-M3-20-t2.fq.gz (version: v0.22.3)
Bismark was run with Bowtie 2 against the bisulfite genome of /home/larteag7/practica/meths/illumina/longipes/ with the specified options: -q -L 15 --score-min L,0,-0.2 -p 4 --reorder --ignore-quals --no-mixed --no-discordant --dovetail --maxins 900
Option '--non_directional' specified: alignments to all strands were being performed (OT, OB, CTOT, CTOB)

Final Alignment report
======================
Sequence pairs analysed in total:       47296751
Number of paired-end alignments with a unique best hit: 17052746
Mapping efficiency:     36.1%
Sequence pairs with no alignments under any condition:  24886831
Sequence pairs did not map uniquely:    5357174
Sequence pairs which were discarded because genomic sequence could not be extracted:    2

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:       2498454 ((converted) top strand)
GA/CT/CT:       6030894 (complementary to (converted) top strand)
GA/CT/GA:       6027157 (complementary to (converted) bottom strand)
CT/GA/GA:       2496239 ((converted) bottom strand)

```

Thanks, 
Luis Alfonso.

**Comment by FelixKrueger** [comment]
Hi Luis Alfonso,

The mapping efficiencies do indeed look like you are dealing with non-directional libraries. I don't think I know QIAseq Methyl library kit, but I just had a quick look at the QIAgen website, and they speak about using the CLC workbench for non-directional libraries. So let's just assume that this is the way libraries are constructed.

In terms of mapping it should really be only a matter of using the `--non_directional` flag in Bismark, all of the downstream steps should be the same.

The mapping efficiencies of ~40% are still not exactly great though, so I am wondering whether you have used Trim Galore for the trimming of the libraries before doing the alignments? Also, the pattern of the OT:CTOT:CTOB:OB strands look similar to non-directional strand proportions of our single-cell libraries, and those typically have a hefty nucleotide bias in the first 6 bp or so due to 6N oligo amplification. Did you look at the FastQC sequence profiles for the first positions, and did you trim them off (e.g. using `--clip_r1 6 --clip_r2 6` in Trim Galore)? 

Also, I'd be tempted to just try to align one single R1 (of only one sample, or maybe even just the first 1 million or so sequences using `-u 1000000`) in `--non_directional` mode to see if a single Read 1 aligns much better than in paired-end mode. I'd be happy to take a look at your FastQC profiles, or run a few tests over here if that helped at all (you could just email me a few hundred thousand sequences of one sample for a test). I am currently on holiday, so replies may take a little longer...

**Comment by OnlyHigh** [comment]
Hey Felix, 
Yes, I trimmed the sequences based in the Fastqc report, 10bps in 5' and 6 bps in the 3' (which is quite excessive but the sequences were really biased towards the ends) 

I tried to raise the mismatch value in the seed (to try to increase sensitivity), the final thing I wanted to try is to change the score function ```--score_min L,0,-0.6```, would you recommend it?

**Comment by FelixKrueger** [comment]
Relaxing the mapping criteria to `--score_min L,0,-0.6` could help, but this might also start getting you some additional unwanted alignments. Are you using a fairly polished genome like human or mouse, or is it still a bit rough? In that case, relaxing the params is certainly warranted. 
In my experience  the bases look quite biased towards the 3' end reads after trimming, but this is really only an adapter trimming effect that should not be worrying at all. We tend not to apply 3' end trimming over here.

In addition, I would probably try to: 

- run FastQ Screen with all the standard organisms used in your lab to identify contaminants (in --bisulfite mode)
- run a subset of R1 in single-end mode (possibly with slightly relaxed criteria as well)
- try to run a test (probably also in single-end mode) using `--local`. This will almost certainly increase the mapping efficiency somewhat (not sure the additional alignments will be the most trustworthy), but you might get an idea if there is something systematic inhibiting the alignments

**Comment by OnlyHigh** [comment]
Hey Felix, 
I tried the ```--score_min L,0,-0.6``` and the single-end mode and I'm running rn FastQ screen, apparently the problem lays in something related to the parity of the reads which inhibiting the alignments, 
So I'm considering running all the libraries in single end mode and then merging them, is possible to merge the R1 and R2 mappings, any advice for that? 
Cheers, 
Luis Alfonso.

**Comment by FelixKrueger** [comment]
So is it that you got a different number of trimmed R1 and R2 reads? In that case, a simple re-run of the adapter trimming process should fix your problem, e.g.:

```
trim_galore --paired --clip_r1 10 --clip_r2 10 file_R1.fastq.gz file_R2.fastq.gz
```
 
It would in theory be possible to run both R1 and R2 in separate runs, and then merge the results at any stage, i.e. you could merge the BAM files, or use `deduplicate_bismark` with the `--multiple` file option, or continue with deduplication separately, run the methylation extraction, and then use both CpG* files of both reads as the input for `bismark2bedGraph`. 

I would however advise that you should instead re-run the trimming process, and sort out the paired-end alignments instead, as using paired-end reads in single end mode will give you an apparent coverage depth increase, which is really only due to the paired-end nature of the files.

**Comment by OnlyHigh** [comment]
Hey Felix, 
I was sick so I couldn't answer before, sorry,

I'll take that advice to the letter, as it is,
Last question before closing the issue, this was the combination of parameters that led to the higher mapping rate: ``` --score_min L,0,-0.6 -L 15 -D 25 -R 5 ``` but I think that I might be loosing too much the parameters, what's more recommendable to loose a little bit the scoring function, having a small seed or increase the aligner effort? Should just use one of those modified parameters or combine them conservatively?

Cheers,
Luis Alfonso.

**Comment by FelixKrueger** [comment]
To be honest I don't think I have ever tampered with the `-L -D or -D`, and we arguably do this kind of stuff a fair bit... I would guess that if you have to play with effort options you are most likely only to achieve a higher mapping rate of something that is coming from rather dodgy areas of the genome anyway (and it is in the eye of the beholder if you think this will add any additional trustworthy data...).

I personally would probably stick to adjusting `--score_min`, and take it from there. (If you have some spare time you could of course take a more systematic approach and try to see what the differences are when you modify different parameters...).

**Comment by OnlyHigh** [comment]
Ok, that's what I thought, 
Thank you for answering all the questions! 
Cheers, 
Luis Alfonso.
