### ISSUE TITLE
Link OT and OB and orientation of genes

### ISSUE THREAD

**Issue by tmms1** [FelixKrueger/Bismark#314]
Hello

I am fairly new to the analysis of whole genome bisulfite data and I am struggling with the concept of strandness of DNA. 

I have paired end libraries. With the help of [these tips](http://seqanswers.com/forums/showthread.php?t=18908), I established that my libraries are directional. I followed all the steps that were described in the excellent Bismark manual and ended up with files:      
CpG_OB....     
CpG_OT....

I want to perform my subsequent analysis in R. I used BioMart to obtain the annotation of the genes. Is it correct that OT corresponds to strand equals + in BioMart and OB corresponds to strand equals - in BioMart? 

Thanks in advance.

--
With kind regards
Tim

**Comment by FelixKrueger** [comment]
Hi Tim,

Yes that is right, OT is informative for the top strand, and OB is informative for the bottom strand.

I would be a little careful about using this strand discrimination in that way though, as this most likely something you would only want to look at strand specific methylation events (and I am not sure there are many reasons for wanting to do that...).

Assuming you work in a mammalian system, you are probably going to look at CpG methylation only. A `CG` dinucleotide has one `C` at the top strand, and another `C` at the bottom strand, offset by 1 bp. The first `C` would end up in the `OT` file, the second one on the `OB` file. Now most people consider a `CpG` dinucleotide to be a single unit of methylation information, rather than two separate ones. So in practice I would recommend you go ahead and generate a coverage file from both `CpG*` context files (using `bismark2bedGraph`), and then continue to work any methylation data that overlaps your features of interest regardless of the strand it was found on. Does that make sense?

**Comment by tmms1** [comment]
Hi Felix

Thank you for your swift and elaborated answer. 

I am working with _Arabidopsis_ data. I read that CHG will probably be the relevant context. 

I want to identify differentially methylated promoters of genes. Because biomart returns information about the strandness of a gene (+ or -), I thought it would be relevant to look at the top and bottom strand separately, but I am not sure if that is the correct way to proceed...

--
With kind regards
Tim

**Comment by FelixKrueger** [comment]
I think if you are interested in the methylation state of promoters generally then you should use the merged information (e.g. in CHG context) of both strands over promoter regions. You could get `CHG` coverage files separately if you wish, with a command like this:

`bismark2bedGraph --CX --gzip -o CHG_output.cov.gz CHG*`

**Comment by tmms1** [comment]
Thank you for the suggestion. I will look at the merged data. 

Do you know when it would be useful to discriminate between the strands?

**Comment by FelixKrueger** [comment]
Hmm, there might be some special applications like hairpin-sequencing or similar that would allow you to investigate hemi-methylation. But this is very niche, and most likely also requires a special design of the experimental strategy...
