### ISSUE TITLE
Low mapping efficiency 

### ISSUE THREAD

**Issue by RubioB** [FelixKrueger/Bismark#317]
Hi Felix, 

After performing my alignements with bismark, I get mapping efficiencies around 25-30 %. 
I had read some post where you said that the error could come from the paired end library. So I did the alignment with only R1 and there I get a mapping efficiency of 46 %. 

I think that the fact of significantly improving the mapping percentage reflects that there is a technical problem due to the paired end mode of the library, right ? 

How can I get out of it then? Do I have to carry out the alignments R1 and R2 independently and after making a merge of the bam for the continuation of the analyzes?
You refer to trimming in some post but to tell the truth I did not quite understand the aim ?

What do you advise me to do in this situation?

Thank you very much for your help !

Bernadette

**Comment by FelixKrueger** [comment]
I have written up some thoughts on low mapping efficiencies in paired-end data here: https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#issue-2-low-mapping-effiency-of-paired-end-bisulfite-seq-sample.

Here is decribed how the mapping and merging of paired-end/single-end data would work. https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#mapping-strategies-for-paired-end-data

I could also offer that you send some reads (maybe 200,000?) as an email (if gzipped it fits as attachment), and I could take a quick look at your library over here.

**Comment by RubioB** [comment]
Thanks a lot for your answer ! I just launched the 'dirty harry' procedure to perform the mapping.

I still send you a subset of R1 and R2 files so that you give me your opinion and be sure that the problem is linked to paired end librairies.
Link to R1 file : https://filesender.renater.fr/?s=download&token=9471c58f-d9ea-f6d8-861c-4222593d6087
Link to R2 file : https://filesender.renater.fr/?s=download&token=9583ebe6-4e4e-ca3a-b707-457a4ecbd89c

Thanks again for your help !


________________________________
De : Felix Krueger <notifications@github.com>
Envoyé : lundi 2 mars 2020 10:16
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] Low mapping efficiency (#317)


I have written up some thoughts on low mapping efficiencies in paired-end data here: https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#issue-2-low-mapping-effiency-of-paired-end-bisulfite-seq-sample.

Here is decribed how the mapping and merging of paired-end/single-end data would work. https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#mapping-strategies-for-paired-end-data

I could also offer that you send some reads (maybe 200,000?) as an email (if gzipped it fits as attachment), and I could take a quick look at your library over here.

**Comment by FelixKrueger** [comment]
I have downloaded the files and took a quick look at the file QC, which looks fairly good really. Also FastQ screen didn't identify any obvious contaminants. Which genome are you actually working with?

**Comment by RubioB** [comment]
Yes the quality controls that I had realized were good, also the results of convertion bisulfite control (i used the chloroplastic génome)
Otherwise, i am working with oak, and i used the PM1N assembly :
 https://urgi.versailles.inra.fr/download/oak/Qrob_PM1N.fa.gz

Envoyé de mon iPhone

Le 2 mars 2020 à 18:02, Felix Krueger <notifications@github.com> a écrit :

﻿

I have downloaded the files and took a quick look at the file QC, which looks fairly good really. Also FastQ screen didn't identify any obvious contaminants. Which genome are you actually working with?

**Comment by FelixKrueger** [comment]
Thanks for the oak genome, I had never used that before...  

I just tried to align reads in single end mode with relaxing the stringency a little. With `--score_min` values of `-0.2`, `-0.4` or `-0.6` I got mapping efficiencies of 45%, 55% and 60% for Read 1, but only 28%, 40% and 49% for Read 2. I would agree that there seems to be something inhibitory within Read 2 that in turn brings down the mapping efficiency of paired-end alignments.

Given that the oak genome seems still consist of several scaffolds, it might make sense to allow a few more mismatches than to very polished genomes such as human or mouse. With mapping efficiencies of 55-60%, and another ~20% of reads aligning to repetitive regions (which are hence discarded), it appears that your libraries, or at least R1, is made up of least 80% oak sequence, which I find is a pretty good value.

I would therefore agree, that the Dirty Harry protocol (maybe with a `--score_min L,0,-04`) is likely going to give you a fairly good outcome in this particular case.

**Comment by RubioB** [comment]
It's clear for me now !

Thank you so much for your help and for the time you took to look to my data !

________________________________
De : Felix Krueger <notifications@github.com>
Envoyé : lundi 2 mars 2020 21:21
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] Low mapping efficiency (#317)


Thanks for the oak genome, I had never used that before...

I just tried to align reads in single end mode with relaxing the stringency a little. With --score_min values of -0.2, -0.4 or -0.6 I got mapping efficiencies of 45%, 55% and 60% for Read 1, but only 28%, 40% and 49% for Read 2. I would agree that there seems to be something inhibitory within Read 2 that in turn brings down the mapping efficiency of paired-end alignments.

Given that the oak genome seems still consist of several scaffolds, it might make sense to allow a few more mismatches than to very polished genomes such as human or mouse. With mapping efficiencies of 55-60%, and another ~20% of reads aligning to repetitive regions (which are hence discarded), it appears that your libraries, or at least R1, is made up of least 80% oak sequence, which I find is a pretty good value.

I would therefore agree, that the Dirty Harry protocol (maybe with a --score_min L,0,-04) is likely going to give you a fairly good outcome in this particular case.

**Comment by RubioB** [comment]
Hi Felix,

I come back to you because my analyzes have finished running on my first sample but i am a little puzzled about the results obtained. I made a first mapping with the R1 and R2 data using --score_min L,0,-0.4. I obtained a mapping efficiency of 37.9 %. Then I realized a mapping with the unmapped R1 (--pbat) and unmapped R2 files (directional mode) and I have obtained a mapping efficiency of  1.6% and 0.5 % respectively.

I m not very sure that these results are very optimal, what do you think ? Or do I have an error somewhere in the procedure ?

Thanks for your help,

Bernadette

________________________________
De : Felix Krueger <notifications@github.com>
Envoyé : lundi 2 mars 2020 21:21
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] Low mapping efficiency (#317)


Thanks for the oak genome, I had never used that before...

I just tried to align reads in single end mode with relaxing the stringency a little. With --score_min values of -0.2, -0.4 or -0.6 I got mapping efficiencies of 45%, 55% and 60% for Read 1, but only 28%, 40% and 49% for Read 2. I would agree that there seems to be something inhibitory within Read 2 that in turn brings down the mapping efficiency of paired-end alignments.

Given that the oak genome seems still consist of several scaffolds, it might make sense to allow a few more mismatches than to very polished genomes such as human or mouse. With mapping efficiencies of 55-60%, and another ~20% of reads aligning to repetitive regions (which are hence discarded), it appears that your libraries, or at least R1, is made up of least 80% oak sequence, which I find is a pretty good value.

I would therefore agree, that the Dirty Harry protocol (maybe with a --score_min L,0,-04) is likely going to give you a fairly good outcome in this particular case.

**Comment by FelixKrueger** [comment]
Hi Bernadette,

    Then I realized a mapping with the unmapped R1 (--pbat) and unmapped R2 files (directional mode) and I have obtained a mapping efficiency of  1.6% and 0.5 % respectively.

I think it should the other way round: Read 1 needs to be aligned in directional (default) mode, and Read 2 required `--pbat`.

**Comment by RubioB** [comment]
Thank you very much, it actually works much better in this sense !

I still have (a last one I hope) question : I took over the email where you give me the percentages obtained after mapping for R1 and R2 in single end. what's surprise me is that I find well around 45 % with R1 file but when i map R2 I do not only have 0.3 % of mapping efficeincy (while in your analysis it's 25 %). I can't understand where this difference comes from?  It seems more logical to have around 20 % of mapping efficiency, maybe I made a mistake somewhere ?

Thanks again and again for your help !

Bernadette



________________________________
De : Felix Krueger <notifications@github.com>
Envoyé : mardi 10 mars 2020 12:04
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] Low mapping efficiency (#317)


Hi Bernadette,

Then I realized a mapping with the unmapped R1 (--pbat) and unmapped R2 files (directional mode) and I have obtained a mapping efficiency of  1.6% and 0.5 % respectively.


I think it should the other way round: Read 1 needs to be aligned in directional (default) mode, and Read 2 required --pbat.

**Comment by FelixKrueger** [comment]
Hmm, I'm not quite sure I understand your question correctly. The commands I used were:

**Read 1 single-end:**
```
bismark --genome /bi/scratch/Genomes/Oak/ subset_QX_R1.fq.gz
```

**Read 2 single-end:**
```
bismark --genome /bi/scratch/Genomes/Oak/ --pbat subset_QX_R2.fq.gz
```

**And paired-end:**
```
bismark --genome /bi/scratch/Genomes/Oak/ -1 subset_QX_R1.fq.gz -2 subset_QX_R2.fq.gz
```


In single-end mode Read 1 needs alignment in directional mode, Read 2 in `--pbat` mode. Paired-end alignments can be started in directional (= default) mode, all the rest is taken care of in that mode. 

In theory, the alignment efficiencies of R1 and R2 in single end mode should be pretty much identical, and also very similar to the paired-end mapping rate (which unfortunately is not the case for your sample). Does that make sense?

**Comment by RubioB** [comment]
Thanks for your response !

Ok I see where the difference is, i didn't set the mode --pbat for R2 single end analysis. I launched my job with this mode so I should find results similar to those you found : "I just tried to align reads in single end mode with relaxing the stringency a little. With --score_min values of -0.2, -0.4 or -0.6 I got mapping efficiencies of 45%, 55% and 60% for Read 1, but only 28%, 40% and 49% for Read 2. I would agree that there seems to be something inhibitory within Read 2 that in turn brings down the mapping efficiency of paired-end alignments."
But I actually don't have the same alignment percentages between R1 and R2 in single end mode since the alignment with R2 is much lower than R1 alignment.

On the other hand, I would like to be sure that when I launch the "dirty harry" analysis, for the analysis of unmapped reads R1 I use the --pbat mode while for unmapped reads R2 I remain un directionnal mode (--> "Then I realized a mapping with the unmapped R1 (--pbat) and unmapped R2 files (directional mode) and I have obtained a mapping efficiency of 1.6% and 0.5 % respectively.

I think it should the other way round: Read 1 needs to be aligned in directional (default) mode, and Read 2 required --pbat")

________________________________
De : Felix Krueger <notifications@github.com>
Envoyé : vendredi 13 mars 2020 12:04
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] Low mapping efficiency (#317)


Hmm, I'm not quite sure I understand your question correctly. The commands I used were:

Read 1 single-end:

bismark --genome /bi/scratch/Genomes/Oak/ subset_QX_R1.fq.gz


Read 2 single-end:

bismark --genome /bi/scratch/Genomes/Oak/ --pbat subset_QX_R2.fq.gz


And paired-end:

bismark --genome /bi/scratch/Genomes/Oak/ -1 subset_QX_R1.fq.gz -2 subset_QX_R2.fq.gz


In single-end mode Read 1 needs alignment in directional mode, Read 2 in --pbat mode. Paired-end alignments can be started in directional (= default) mode, all the rest is taken care of in that mode.

In theory, the alignment efficiencies of R1 and R2 in single end mode should be pretty much identical, and also very similar to the paired-end mapping rate (which unfortunately is not the case for your sample). Does that make sense?

**Comment by FelixKrueger** [comment]
Yes the directionality of alignments is the same in the starting reads as well as in any unmapped reads.

**Comment by RubioB** [comment]
Ok, perfect ! I think is finally clear for me !
Thank you so much !

________________________________
De : Felix Krueger <notifications@github.com>
Envoyé : vendredi 13 mars 2020 13:49
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] Low mapping efficiency (#317)


Yes the directionality of alignments is the same in the starting reads as well as in any unmapped reads.

**Comment by franrodalg** [comment]
Hi @FelixKrueger,

Sorry for resuscitating this closed issue, but I have a similar question and I didn't want to open a new one unnecessarily. Using the "Dirty Harry" method for our samples, we seem to get roughly 50% PE alignment, and then from the unmapped reads we get 60-70% for R1 (no pbat mode) but below 10% for R2 (pbat) mode. Removing the pbat mode in R2 leads to 0% mapping efficiency. 

From the discussion above, I'm not sure whether this is expected and, if so, what could be the explanation for it. Do you have any insight?

Cheers,
- Fran

**Comment by FelixKrueger** [comment]
Hi Fran,

This sounds like a problem with the read quality of R2. If you wanted you could send me some sequences of R2 and I can take a look (or both the _unmapped R1 and R2), some 200K sequences or so.

**Comment by franrodalg** [comment]
Thanks so much, Felix. I have uploaded both [R1](https://collect.qmul.ac.uk/down?t=R8KFJV9V7FP86C2C/6TEJ18K164IFDFEVFMCN0L8) and [R2](https://collect.qmul.ac.uk/down?t=45VM2JFFTCHF787S/4PV1964RBVBBGSSHHVQ9MEG) unmapped reads from a single sample. I think the number of reads is roughly what you asked for.

Thanks so much again

**Comment by FelixKrueger** [comment]
Thanks for those. There are still a few more meetings this afternoon, but I'll try to take a look soon.

**Comment by FelixKrueger** [comment]
Right, if I am not mistaken then the fix here should be rather straight forward! 

Judging by the sequence composition of Read 2 I would think the library was generated using the Accel Swift kit, is that correct? We tend to suggest trimming the first 10bp of each read (https://github.com/FelixKrueger/Bismark/tree/master/Docs#ix-notes-about-different-library-types-and-commercial-kits), but in your case I would probably recommend running:

```
trim_galore --clip_r1 10 --clip_r2 20 --paired read1.fq.gz read2.fq.gz
```

I would expect that you will then have great mapping efficiency and don't even need the Dirty Harry approach. Let me know if something doesn't work out as expected.

**Comment by franrodalg** [comment]
Great! I just confirmed we used the kit you mention, so I will re-trim and re-align some of our pilot data as you suggest and let you know. Thanks!!!

**Comment by franrodalg** [comment]
Hi @FelixKrueger! I've done as you suggest and the alignment rates seem to improve, with values above 60% for all samples (red bar in the figure)

![image](https://user-images.githubusercontent.com/7487122/87870106-00482d00-c99d-11ea-99dd-a65fde2041f0.png)

Just for curiosity, I also realigned the unmapped reds following the Dirty Harry method, and there are some further improvements (green and blue bars). Do you think the downsides of the single end alignments might outweigh the benefits of increased alignment rates in this case?

Thanks so much for your help

**Comment by FelixKrueger** [comment]
Hi Francisco,

Now that looks much improved indeed, efficiencies of 65-75% are really quite nice for mouse data. The single-end seem to add some 5% or so (as they provide only ~ half of the calls of paired-end data. If it was me personally, I would probably not go the extra length and complication of including these few extra calls, considering that you would have to proceed differently for PE and SE data until you reach the coverage file step. And it would be at least another sentence in a materials & methods section of a paper/thesis...But that's up to you, I guess :)

**Comment by franrodalg** [comment]
I agree. I think it should be fine with the paired end alone. Just FYI, these alignments have been done against a MM10 + rDNA reference, so efficiencies should be a bit higher than usual, and the single ended alignments have already been adjusted for the "half of paired-end data" you mention (i.e., we don't need to halve the rates that appear there, they do increase roughly a 10% overall)

**Comment by sunsong95** [comment]
Hi Felix,

Sorry to open this question again, my data is paired-end sequencing data with an Mapping efficiency of 8.2%. In order to find the reason for the low Mapping efficiency, I deliberately ran the data in single-ended mode, and the results showed that the R1 Mapping efficiency was 70.5%, and the R2 Mapping efficiency was 31.4%. The following example is how I used the command：

```
bismark --genome /ref/human/ -1 fastq_R1.fq.gz -2 fastq_R2.fq.gz
bismark --genome /ref/human/ fastq_R1.fq.gz
bismark --genome /ref/human/ --pbat fastq_R2.fq.gz
```

At the same time, I also performed a check on FastQ_screen, and the results of R1 and R2 are as follows：
![image](https://user-images.githubusercontent.com/55424135/209781877-ba11a0d2-2652-49a2-948b-27fda7998797.png)
![image](https://user-images.githubusercontent.com/55424135/209781940-89e9e2f9-21cd-44df-a96e-8f3cfce89807.png)

I would like to know what is causing the low Mapping efficiency and how can I get the most methylation information. 

Look forward to your reply, thanks!

**Comment by FelixKrueger** [comment]
Hi Neon, 
Happy New Year and apologies for the slow reply. You are probably already aware of the tips for low mapping efficiency i have [written up here](http://felixkrueger.github.io/Bismark/faq/low_mapping/), they were also mentioned earlier in this post.

From what you are describing it certainly looks like Read 2 is alignment substantially worse than Read 1, and this is most likely also the cause for the low mapping efficiency in paired-end mode. The difference between the stats you are referring to and FastQ Screen is that the latter uses `--score_min L,0,-0.6` by default, so it simply allows 3-times as many mismatches and/or InDels. 

If you are getting alignment rates to human (even if it is only for R1) north of 80%, external contamination doesn't appear to be a major contributing factor.

My first guesses would be:
- maybe there is a systematic bias in R2 that prevents mapping? Which kit did you use, and which trimming steps did you employ?
- there could be something wrong with R2 on a technical level (e.g. flowcell or laser/focussing fail?). Could you attach, or send via email the FastQC html file?
- Maybe increasing `-X`, or relaxing the mapping stringency can alleviate the issue `--score_min`)?

**Comment by FelixKrueger** [comment]
So the only measure with a notable effect is using local alignments... The issue with these is that they appear to magically increase the mapping efficiency, but it leaves you none the wiser what the actual cause for the poor mapping efficiency was. I would go ahead using this data, but ideally would aim to understand what went wrong as well.. 

I don't think I got any email with FastQC profiles, did you send it to my [current address](mailto:fkrueger@altoslabs.com)?

**Comment by sunsong95** [comment]
Hi Felix, @FelixKrueger 

Yeah, I also think it's best to find the actual reason. 

I sent an email titled "Low mapping efficiency" to the address you provided via gmail, but I don't know if it was automatically blocked or in the spam box.

**Comment by FelixKrueger** [comment]
Hi Neon,

The email did indeed find its way into the spam folder... (where I also found some other interesting messages...).

The data looks fine from a technical point of view, but there are significant base-composition issues at the start of both Read 1 and 3. The first 4bp of each read appear to make up the UMI sequence, and base 5 should be a T in all cases? Even if these 5 bp had been (re-)moved from the reads and transferred to the readIDs, I would still be concerned that the following 10bp or so still show a pronounced bias (you could run FastQC with `--nogroup` to stop it from aggregating information over several bp). From [this experience](https://sequencing.qcfail.com/articles/mispriming-in-pbat-libraries-causes-methylation-bias-and-poor-mapping-efficiencies/) we know that biased sequences can sometimes prevent reads from mapping properly (because of a much increased mutation and InDel load). Which library prep kit did you use for this (or is it a custom method)? In any case, you could try to clip off the first 10bp or so to see if that restores the mapping efficiency? In Trim Galore, this would be `--clip_r1 10 --clip_r2 10`.

**Comment by sunsong95** [comment]
Hi Felix, @FelixKrueger

I used the `--nogroup` parameter of fastqc to test on the fastq file after extracting the UMI, and there is indeed a bias in the first 10bp. But when I use `--clip_r1 10 --clip_r2 10`, the mapping efficiency is still only **11.3%**, so I think this is not the main reason for the low mapping efficiency. Anyway, I'll continue to use the results of `--local` PE mode.

I used the targeted methyl-seq library, to be honest I don't know whether bismark is suitable for my data analysis.

If you have any ideas, please feel free to contact me, thanks!

**Comment by zhen-fu** [comment]
Hi all, 

Can anyone explain the Dirty Harry method, I can not open the link on Mar 2, 2020. Thank you all!

**Comment by FelixKrueger** [comment]
I found this in a different thread:

"...

the library contained chimeric reads (e.g. here: https://sequencing.qcfail.com/articles/pbat-libraries-may-generate-chimaeric-read-pairs/)

As mentioned in the QC Fail article, we then follow a combination of PE and SE alignments in this case:

To rescue as much data from a paired-end PBAT library with low mapping efficiency as possible we sometimes perform the following method (affectionately termed “Dirty Harry” because it is not the most straight forward or cleanest approach):

Paired-end alignments to start while writing out the unmapped R1 and R2 reads using the option `--unmapped`. Properly aligned PE reads should be methylation extracted while counting overlapping reads only once (which is the default).

- unmapped R1 is then mapped in single-end mode (in default = directional mode)
- unmapped R2 is then mapped in single-end mode (in `--pbat` mode)

Single-end aligned R1 and R2 can then be methylation extracted normally as they should in theory map to different places in the genome anyway so don’t require attention to overlapping reads. Finally, the methylation calls from the PE and SE alignments can merged together before proceeding to the `bismark2bedGraph` or further downstream steps. The command for this is this one:

```
bismark2bedGraph -o PE_and_SE_merged.cov CpG*single-end* CpG*paired-end*
```

**Comment by JorgeCortes-M** [comment]
Hi Felix,

I hope you are doing well, I've been using Bismark with pair-end methylRAD data of Basilichthys microlepidotus (a silverside). As a reference I've been using a closely related species genome (Odontesthes bonariensis). When I perform the pair-end alignment it only gives me a 3% of mapping efficiency, so I tried to align the R1 and R2 independently with different values of `--score_min` (the default, `L,0,-0.4 and L,0,-0.6`) and in each case always get a better mapping efficiency for the R1, ranging from around 30% (default) to 58% (`L,0,-0.6`) in contrast with R2 ranging from 20% (default) to 45% (`L,0,-0.6`). I still didn't apply the Dirty Harry method because I am not sure about what cause this difference between R1 and R2. I know that the mapping efficiency shouldn't be very high taking in consideration that I am using a genome of a related species, but I am not sure if this mapping percentages are good enought to proceed. What do you think about it?

Thank you in advance and have a nice week!

**Comment by FelixKrueger** [comment]
Hi Jorge,

I am afraid I am not familiar with the the methylRAD technology, so I am not sure I can give great advice. I just looked at the methylRAD publication where I found an example of an enzyme assisted assay that produces 32bp long fragments with 4bp overhangs on either side. If this is also true in your case I wonder if paired-end sequencing is the best choice here...

Some things you definitely need to get right is:
- understand the library structure, and apply correct trimming on both sides of the reads. If the 5' has a very biased composition, maybe it needs some additional trimming? Could you link the FastQC profiles for both reads, or send them over via email?
- Initially I thought you might have very long fragment sizes that require increasing the `-X` parameter beyond 500bp which is the default, but maybe your situation is very different and your fragments are all super short?
- Chances are that mismatches of biased positions in paired-end sequencing add up, resulting in non-aligning samples. You could at least test the option `--local` to se if the paired-end efficiency goes up?

Can you maybe try out these things, and send over a small sample of the files as well as a link to the genome you have been using? Cheers, Felix

**Comment by JorgeCortes-M** [comment]
Hi Felix,

Thank you for your help, I already send you the files and some information that I am going to write here also.
The methylRAD technology is also used by Floragenex inc. In this case they sequenced 150bp in pair-end mode, and an enzyme was used to transform the methylated cytosines. 
In relationship with the points that you mentioned:

- When I checked the R2 reads quality, it looks a little bit low in comparison with R1, that could be a reason why the mapping efficiency was too low in the first try with bismark. (I sent you the FastQC files).
- In this case I am not sure, but I run it again with the default 500bp and the --local option and the alignment rate is better.
- As I mentioned the mapping efficiency rise up to 57.1% (I sent you the report).

Also I sent you an small subsample of 200K reads and the link to the genome of _Odonthestes _bonariensis__, in any case I let the link here too: [genome](https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_027942865.1/).

Thank you again for your time!

**Comment by FelixKrueger** [comment]
I have now had a look at your samples, here are my observations as bullet points:

- the data is complementary to the original strands, so requires the option `--pbat` for alignment
- Read 1 starts with almost 100% of the same sequence
![Screenshot 2024-08-06 at 08 53 06](https://github.com/user-attachments/assets/48f918ed-6a34-4539-a84f-73f4052f6dfc)
As this is a PBAT-style library, 4 out of 6 bases in the first biased 6bp are `A`s and would be called un-methylated. If this is a remnant of a restriction enzyme or experimental procedure you should probably remove this portion of the reads
- Read 2 also has some strong bias at the 5' end, not exactly sure why this is. In all likelihood this will also be detrimental for alignments. The bias here extends to at least around 10bp.
![Screenshot 2024-08-06 at 08 53 25](https://github.com/user-attachments/assets/71744940-d881-4af1-b655-64c161345008)

- the libraries are very duplicated, with an estimate of ~95% coming from the same positions. If methylRAD is similar to RRBS then you may only expect a small part of the genome to be present in the results. If this was the case then you may not wish to perform deduplication later on as it would remove a lot the results
- Read 2 contains ~10% of poly-G, and up to 10% of poly-T sequences. As these sequences will probably not align (uniquely), you need to adjust your expectations (80% would is the new 100%...) 

I tried clipping the data with the following command:
```
trim_galore --paired *fastq --clip_r1 10 --clip_r2 10 --three_prime_clip_r1 10 --three_prime_clip_r2 10
```

followed by alignments like so:

```
 bismark  --pbat --genome GCA_027942865.1/ -1 subPEL1.1_val_1.fq -2 subPEL1.2_val_2.fq --score_min L,0,-0.6
```
which results in 30.3% unique alignments with non-CG methylation levels. I find this a good start, given the circumstances and the fact that we are not aligning to the correct genome...

Using local alignments the efficiency can indeed be brought up to 57% for paired-end alignments. You might want to compare the end-to-end and local alignments to understand better where these 'extra' alignments are coming from.

- Increasing the allowed fragment length (to `-X 2000`) increased the mapping efficiency by ~5% to 35% in end-to-end mode, indicating that there are at least some longer fragments in the library

- increasing the fragment length together with `--local` mode leads to a whopping 69% alignment efficiency

- On top of that, taken on its own Read 1 aligns with 57% (end-to-end, like above), and 79% in `--local --pbat` mode. This is very high indeed.

- Read 2 on the other hand doesn't align that well (44% end-to-end and 75% local mode), but this seems almost negligible compared to the gains to be had with a combination of trimming, `-X 2000` and `--local` mode.

I hope this helps!

**Comment by aniruddha2** [comment]
Hi Fellix, Hope you are good. More recently, we are trying to assess the two modes of alignment in bismark for cell free DNA methylation data from RRBS.  Standard vs Local mode. These are single-ended RRBS data. 
 
In Local mode, we get more CpGs (with a coverage filter of 10). However, we also get increased % of methylation in unknown context. The correlation of replicates is similar in both mode. 
 
In general, I am keen to to know your thoughts about these modes for RRBS data about the accuracy of methylation calls.
Cheers,
Aniruddha

**Comment by FelixKrueger** [comment]
The cytosine context is generally called `unknown` whenever the C is immediately followed by ambiguous nucleotides in the genome (e.g. `N`) or, and that is more likely, when there is an insertion immediately downstream of the C (i.e. 1 or 2 bp away) (the decision has been made not to base the methylation call on insertions as this might be error prone, hence call the context `unknown` and ignore it for downstream analyses).

My guess is that local alignments will simply allow more poor alignments to get through, which are more likely to have more of the insertions in proximity mentioned above. If you see a dramatic increase in the level of methylation in Unknown context this could be an indication that the alignments are incorrect (at which point you get more arbitrary methylation calls).

Since `Unknown` context is ignored for the methylation extraction anyway, and you are applying a fairly strict 10-fold coverage filter on top of that, I doubt that the exercise will have a dramatic effect on your downstream analyses in either case.

**Comment by aniruddha2** [comment]
Dear Felix,

Thanks for that. Much appreciated.

We were thinking in the same lines that we are eventually studying CpG methylation only and in addition we are taking the Dyads with 10 or more reads for analysis and correlation of those are very similar in standard vs local so doesn't seem like it will have a dramatic effect.

Thanks again for your thoughts.

Kind regards,
Aniruddha


From: Felix Krueger ***@***.***>
Date: Tuesday, 10 September 2024 at 8:34 PM
To: FelixKrueger/Bismark ***@***.***>
Cc: Aniruddha Chatterjee ***@***.***>, Comment ***@***.***>
Subject: Re: [FelixKrueger/Bismark] Low mapping efficiency (#317)

The cytosine context is generally called unknown whenever the C is immediately followed by ambiguous nucleotides in the genome (e.g. N) or, and that is more likely, when there is an insertion immediately downstream of the C (i.e. 1 or 2 bp away) (the decision has been made not to base the methylation call on insertions as this might be error prone, hence call the context unknown and ignore it for downstream analyses).

My guess is that local alignments will simply allow more poor alignments to get through, which are more likely to have more of the insertions in proximity mentioned above. If you see a dramatic increase in the level of methylation in Unknown context this could be an indication that the alignments are incorrect (at which point you get more arbitrary methylation calls).

Since Unknown context is ignored for the methylation extraction anyway, and you are applying a fairly strict 10-fold coverage filter on top of that, I doubt that the exercise will have a dramatic effect on your downstream analyses in either case.
