### ISSUE TITLE
Mapping report disagrees with number of reads in bam

### ISSUE THREAD

**Issue by rsbrennan** [FelixKrueger/Bismark#322]
After mapping my paired end RRBS reads with bismark, my alignment report states the following:

Number of paired-end alignments with a unique best hit:	6208595

Which corresponds to 12,417,190 total reads

However, if I count the number of reads in the bam with samtools view -c, I find 12,189,858 reads. This is a consistent pattern; I always have bismark report a few hundred thousand more reads than I find in the actual bam. In the bam, there are equal numbers of forward and reverse reads. I can't reconcile these differences. Any thoughts about what is going on here?

I should note that this is consistent across all my samples. using v0.22.1

**Comment by FelixKrueger** [comment]
Hi Reid,

If I remember correctly then the number of unique alignments really counts whether there is either a single best alignment, or a best alignment spread over the different alignment threads. 

There may however be instances where e.g. the genomic sequence for these alignments (or rather the genomic sequence +/- 2bp down-/upstream (depending on the alignment strand)) cannot be extracted. In such cases, the sequences are reported as having a unique alignment, but also reported as `Sequences which were discarded because genomic sequence could not be extracted:`. Would that explain what you are seeing?

**Comment by rsbrennan** [comment]
Hi Felix,

Thanks for the quick response- you've made bismark a really great resource. 

`Sequences which were discarded because genomic sequence could not be extracted:` is exactly what it is. I didn't realize those where the sequence couldn't be extracted were also being counted in the unique alignment score. 

Thanks for the clarification. Hopefully this helps others who may have the same question.

Reid
