### ISSUE TITLE
Bismark running error

### ISSUE THREAD

**Issue by etarisal** [FelixKrueger/Bismark#349]
Hello!,

I am running bismark with the following command:

`bismark --output_dir $output_path/44_test -u 100 --multicore 4 --genome_folder /home/vopazo/Data/anotacion/ -1 $input_path/Out_44_1_test.fastq -2 $input_path/Out_44_2_test.fastq`

During Bowtie 2 paired-end alignment for CTread1GAread2CTgenome, I got the following error:

"Can't open pipe to bowtie: Cannot allocate memory at /usr/local/bin/bismark line 6331, <__ANONIO__> line 643."

I don't think that I am running out of memory, I am using a computer with 128Gb RAM and a processor intel xeon W-2175 2.5-4.3Gz turbo 14 cores and 28 threads. This run was a test and I select only 100 reads to be aligned. The reads are 50bp

I will be grateful to get any help with this error,

Best

Estefanía

**Comment by FelixKrueger** [comment]
Hi Estefania,

please forgive me, but `Can't open pipe to bowtie: Cannot allocate memory at ...` 

and `I don't think that I am running out of memory`: Are you a politician? :)

Joking aside, the amount of memory required for your process depends almost entirely on the genome build you are using for your run. As an example, for a typical (default, directional) run against the human genome Bismark will require roughly 4GB of RAM to hold the entire genome sequence in memory, and then 2 additional times this amount for 2 instances of Bowtie 2, so around 12-13GB in total. This is just for the chromosomal sequences. 

If you've got a genome with non-chromsomal or even patch regions etc, I have seen or heard of much higher memory usage, above 20GB for a single instance of Bismark. Since you used `--parallel 4`, you need to multiply this value by 4.

Are there any other processes on your machine consuming memory at the time you are trying to run Bismark? I would suggest you open a second terminal and run `top` in it. In another shell you can run Bismark in its default mode (which by the way should finish your test alignments in 1 second or so), or with increasing values for `--parallel/--multicore`).

Let me know how you get on.

Cheers, Felix

**Comment by etarisal** [comment]
Hello Felix!,

You are right! I sound pretty much as a politician (jajajaja). But, on my
defense, it didn't make sense (to me) that Bismark runs out of memory
having more than 90Gb available XP (I didn't think on non-chromosomal
sequences :(, I was expecting a 12Gb memory usage)
As you mention, the problem is on the genome annotation. I was using the
human Ensembl annotation including non-chromosomal sequence, so I checked
memory usage (using the same script) and confirmed that all 90Gb were used
while reading the genome... now, I can fix the problem :D :D

Thanks a lot for your quick response and very useful advice!

Have a nice day
:D
Estefanía
___________________
*Estefania Tarifeño,* *PhD.*
Assistant professor
Department of Biochemistry and Molecular Biology
Faculty of Biological Sciences
University of Concepción, Concepción, Chile
(+56)(41)2203784

**Comment by FelixKrueger** [comment]
Excellent, all the best for the real run(s)!
