### ISSUE TITLE
chromosomal sequence could not be extracted error

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#35]
Chromosomal sequence could not be extracted for	M02800:55:000000000-AMN7M:1:1116:14322:13406_1:N:0:1:TTTTAAAACT	chrUn_JTFH01001319v1_decoy	2196
Mar 17, 2016 11:33 AM

This is with 0.14.5 and using a genome reference with decoys and alt haps. Any ideas?

**Comment by FelixKrueger** [comment]
This may happen when a reads aligns to the very edge of a chromosome. Bismark needs to extract 2 additional bp downstream (or sometimes upstream depending on the mapping strand and conversion state) in order to determine the sequence context, but at the very edge of chromosomes this is obviously not possible. This normally occurs mainly on the MT chromosome, but if you've got lots of tiny little scaffolds in the assembly it may occur a bit more often. The overall number this occurs should still be negligible though.

**Comment by avilella** [comment]
Ok, this is reassuring. This is a short decoy sequence anyway, so if the read went there, we don't want it downstream anyway.

Cheerio!
