### ISSUE TITLE
sort: stray character in field spec: invalid field specification `3,3V'

### ISSUE THREAD

**Issue by laurahspencer** [FelixKrueger/Bismark#358]
When running `bismark2bedGraph` (Bismark-0.22.3) I run into the following error: 

```
sort: stray character in field spec: invalid field specification `3,3V'
Died at <path-to-bismark>/bismark2bedGraph line 486
```

The only option I'm using is --scaffolds. In the `bismark2bedGraph` code there are 2 comments related to the "3,3V" sort option. One specifies that `k3,3V` is critical, the other says it is not necessary. Here is an excerpt from lines 433 to 443: 

```
	    open $ifh, "gunzip -c $in | sort -S $sort_size -T $sort_dir -k3,3V -k4,4n |" or die "Input file could not be sorted. $!\n";
	}
	else{ 
	    open $ifh, "sort -S $sort_size -T $sort_dir -k3,3V -k4,4n $in |" or die "Input file could not be sorted. $!\n";
	}
	### Comment by Volker Brendel, Indiana University
	### "The -k3,3V sort option is critical when the sequence names are numbered scaffolds (without left-buffering of zeros).  Omit the V, and things go very wrong in the tallying of reads."
    }
    else{
	### this sort command was used previously and sorts according to chromosome in addition to position. Since the files are being sorted according to chromosomes anyway,
	### we may drop the -k3,3V option. It has been reported that this will result in a dramatic speed increase
```

Just for kicks, I removed the `-k3,3V` options and the script is currently running without error, but given that it might be critical, I don't know if I should trust the results. Any suggestions as to how to address this issue? 

Here's the format of my input data: 

```
Bismark methylation extractor version v0.22.3
K00337:331:HF2KVBBXY:3:1101:1052:1244_1:N:0:NGATGT	+	contig_4632_pilon	227710	Z
K00337:331:HF2KVBBXY:3:1101:1052:1244_1:N:0:NGATGT	-	contig_4632_pilon	227733	z
K00337:331:HF2KVBBXY:3:1101:1824:1244_1:N:0:NGATGT	-	contig_35_pilon	112538	z
K00337:331:HF2KVBBXY:3:1101:1824:1244_1:N:0:NGATGT	-	contig_35_pilon	112509	z
K00337:331:HF2KVBBXY:3:1101:2199:1226_1:N:0:NGATGT	-	contig_7404_pilon	94720	z
K00337:331:HF2KVBBXY:3:1101:2199:1226_1:N:0:NGATGT	-	contig_7404_pilon	94716	z
K00337:331:HF2KVBBXY:3:1101:2473:1244_1:N:0:NGATGT	-	contig_1939_pilon	629	z
K00337:331:HF2KVBBXY:3:1101:2199:1226_1:N:0:NGATGT	-	contig_7404_pilon	94710	z
K00337:331:HF2KVBBXY:3:1101:2473:1244_1:N:0:NGATGT	-	contig_1939_pilon	606	z
```

**Comment by FelixKrueger** [comment]
Hi Laura,

This comes down to the intricacies of the Linux `sort` command, and I have to say I never felt very knowledgeable about it... To understand the issue a bit more I would have to have a closer look at this (ideally with some of your input data to replicate the issue), but here are two quick thoughts: 
1. removing `-k3,3` entirely is almost certainly going to go wrong a lot, as you are more or less removing the scaffold from the sort completely, and simply sort by position over all scaffolds. If anything I would probably try to remove the `V` from the sort, maybe our OS is using a `sort` that doesn't allow the `V`?

Quickly searching for the error message I found e.g. this:
```
The two fields in -k arg are the START AND END fields. You can specify -k ANY NUMBER OF TIMES, to sort on multiple keys. So, -k 1,1 -k 2,2 -k 3,3 will sort first on field 1, then field 2 then field 3.
```

(here: https://stackoverflow.com/questions/38221364/gnu-sort-stray-characters-in-field-specification)

2. I don't really have a solution at hand that will 'test' whether your own modifications will do the right thing, but I could share with you code that will sort internal methylation calls and write out a new sorted coverage file form calls that are held in memory. All you would need is an option to read the CpG* input file into a data structure first. 

**This is the Python version:**
```python
with gzip.open("merged_coverage_files.cov.gz","wt") as out:
   
    for chrom in sorted(allcov.keys()):
        
        print (f"Now sorting positions on chromosome: {chrom}")
        for pos in sorted(allcov[chrom].keys()):
            perc = ''
            if (allcov[chrom][pos]['meth'] + allcov[chrom][pos]['unmeth'] == 0):
                # This should not happen in real data, as coverage files by definition only show covered positions
                print ("Both methylated and unmethylated positions were 0. Dying now...")
                sys.exit()
            else:
                perc = allcov[chrom][pos]['meth'] / (allcov[chrom][pos]['meth'] + allcov[chrom][pos]['unmeth']) * 100
            
            # percentage is displayed with 2 decimals with f-string formatting
            out.write(f"{chrom}\t{pos}\t{pos}\t{perc:.2f}\t{allcov[chrom][pos]['meth']}\t{allcov[chrom][pos]['unmeth']}\n")
```

**This is the Perl version:**
```perl
open (OUT,"| gzip -c > $outfile") or die $!;
 
warn "Now printing a new, merged coverage file\n";
foreach my $chr(sort keys %cov){
    foreach my $pos(sort {$a<=>$b} keys %{$cov{$chr}}){
	my $perc = sprintf ("%.2f", $cov{$chr}->{$pos}->{m} / ($cov{$chr}->{$pos}->{m} + $cov{$chr}->{$pos}->{u}) *100 );
	print OUT "$chr\t$pos\t$pos\t$perc\t$cov{$chr}->{$pos}->{m}\t$cov{$chr}->{$pos}->{u}\n";
    }
}
close OUT or die $!;

```

I should probably mention that both these options require sorting in memory, so if you have large input files you will also need sufficient system resources (`sort` on the other hand will cache out to the hard-disk instead which is why we are using it in the first place).

Let me know if I can be of further assistance.

**Comment by laurahspencer** [comment]
Thanks so much for the detailed response, Felix. The problem turned out to be an outdated `sort` function in the GNU coreutils suite on my computer. The old `sort` did not include the -V option, which sorts chromosomes by "version" as opposed to alphabetical/numerical. After updating from coreutils v5.93 to v8.32 I no longer got the error, and `bismark2bedGraph` worked as anticipated.

**Comment by FelixKrueger** [comment]
Excellent, I'm glad that this got >sorted< [see what I did there]?!? 😺  Thanks also for the feedback, it might prove useful for future users. All the best
