### ISSUE TITLE
C methylated in unknown context (CN or CHN)

### ISSUE THREAD

**Issue by Yuxinagli** [FelixKrueger/Bismark#380]
Hi Felix,
I am comparing the results of two WGBS kits. There is an obvious difference between the results of the two kits on "C methylated in unknown context (CN or CHN)". one is 5.9% , 6.2% while another is 2.2%, 1.3%(two replicates for each kit). Could you please help me understand how this category originates and the possible reason for this discrepancy?  

Thanks,
Yuxiang

**Comment by FelixKrueger** [comment]
Hi Yuxiang,

the category `Unknown context` arises whenever you either see alignments to a genome where any of the following two bases is and N or an otherwise non-DNA base, such as the one we are using to fill in for insertions right next to the C in question. 

As an example, let's say you've got a C  in the CG context, but the read aligns with an insertion right next to the C, say the insertion is `AGA`. In such a case the original context `CG` would be treated as `CXXXG`, where `XXX` stands for the insertion `AGA`. So yea, it such a case it is pretty much impossible to accurately determine the sequence context as it differs between the read and the genome. Hence, such cases are treated as `Unknown context`. 

I cannot exactly say whether there is a significance in methylation or the introduction of insertions between the two kits, but in effect Unknown calls will simply be ignored in every downstream step as you cannot really trust them (and on top of that the number of those calls should be negligibly low compared to the other calls).

Does that  make sense?

**Comment by Yuxinagli** [comment]
thank you for your reply. yes, the total number of C in Unkown context is really low comparing to other three. 

But I still  don't understand " the one we are using to fill in for insertions right next to the C in question".
In your example, do you mean indel in the genome of my sample or any artificial insertion during library preparation  by the "insertion AGA "?  Could you please share more about this?
-Yuxiang

**Comment by FelixKrueger** [comment]
In the example above we would have the situation that the genomic sequence context for the C in question is `CG`, however, due to the insertion in the read sequence, the read now has a different sequence context:

```
read:    CAGAG
genome:  C---G
```

We could now take 2 different approaches.
1. We could simply take the sequence context from the read (here `CAG` would be CHG-context, and no longer the genomic CG context). This would however mean that any sequencing error, or potential insertion might result in a different sequence context. Given the number of potential errors, this would very quickly result in a huge mess (where any C might occur in any context).
2.  The more robust approach is a reference genome centric approach, where we normally only consider the genomic sequence to determine the sequence context. If we take the example again, then we simply do not have an equivalent for inserted bases in the genome, so we cannot accurately determine the sequence context for the read. Therefore, reads that are inserted in the read are being filled in the reference genome with spaceholders, `X`:

```
read:    CAGAG
genome:  CXXXG
```

If we now try to determine the sequence context of a C in `CXX` sequence, the C gets assigned Unknown context as we simply cannot be sure what the context is. If we assume that CGs in a mammalian genome are normally highly methylated, but if the read sequence shows non-CG context (`CAG`), which is typically universally un-methylated then you can immediately see that treating the sequence either in a strictly read or genome-based manner would most likely result in incorrect methylation calls. Giving the C in question an Unknown context, we sort of eliminate this position from the results, but at least we are not adding spurious calls. Does this clear things up?

**Comment by Yuxinagli** [comment]
I got it, thank you very much for your kind help. 
-Yuxiang
