### ISSUE TITLE
Understanding coverage reported by methylation_extractor .cov output

### ISSUE THREAD

**Issue by NomiCentarix** [FelixKrueger/Bismark#385]
Hello Felix,

I have the following [.bam file](https://centarix-my.sharepoint.com/:u:/g/personal/nomi_centarix_biz/EWtOPeLjvRVMrptPb2h3qqoBV8VNCx9Xn_dsWgWNiq6B5w?e=5nwrTJ) created by Bismark (alignment step). 
I used paired reads, after applying _Trim Galore_, and a Lambda genome as a reference.
```bismark --bowtie2 --bam --fastq --phred33 --genome genome_lambda/ -1 BSLFT-1_S7_L001_R1_001_val_1.fq -2 BSLFT-1_S7_L001_R2_001_val_2.fq_```

Then, I did the methylation extractor step, and got the following [.cov file](https://centarix-my.sharepoint.com/:u:/g/personal/nomi_centarix_biz/EUtWLxKElLdMuIBCx7Y_HwMBVu9e3CLeI8mlBQEC0bnoUA?e=2Poqwf).
`bismark_methylation_extractor --comprehensive --bedGraph --CX BSLFT-1_S7_L001_R1_001_val_1_bismark_bt2_pe.bam`

Now, let's focus on one position, say, **position 136**. According to the .cov file, it is covered by **4 reads**. 
![image](https://user-images.githubusercontent.com/70898836/96422477-ba4f6f00-1200-11eb-8d9b-f260de9b3463.png)

To verify coverage, I counted the number of reads which cover position 136.
I did this by converting the .bam file into a [.bed file](https://centarix-my.sharepoint.com/:u:/g/personal/nomi_centarix_biz/EY3NXq2HChRKi1oMvZXeSccBfDT-BOpH_kyswogPcyM8HQ?e=eenSAZ) (using _bamtobed_), and then counting reads which their mapping range include position 136.
The number of reads I got is **1046** (if ignoring the 1/2 read), or  **2078** (otherwise). 

My question is: 
How do I explain the gap between these coverages (4 reads VS 1046 reads)?

Thank you very much,
Nomi

**Comment by FelixKrueger** [comment]
Hi Nomi,

I am not exactly sure what is going on, but my guess is that it is a mix of things:
- Position 135 is a C on the top strand, with a coverage of 702 methylation calls.
- Position 136 is a C on the bottom strand, with a coverage of 4 calls

This looks like for whatever reason there is an enormous difference in the number of reads against the top vs the bottom strand. This could be a consequence of the kit used, of the lambda base compositions (some strands get selectively degraded, e.g. also the MT bottom strand). 

Regarding the discrepancy with `bamtobed`:

If you assume paired-end sequencing, let's assume a read starts at base 1, and ends at base 300. The read length is 100bp. In this case, read 1 would cover bases 1-100, read 2 would cover bases 200-300. Since no portion of the read covers either position 135 nor 136, you would not get a methylation call. `bam2bed` on the other hand would tell you that both positions had been covered with coverage of 1. This example illustrates that this tool (`bam2bed`) is not doing the right thing for bisulfite-seq data, as:

1.  paired-end BAM files don't mind whether a regions is really covered by a read - missing regions are simply inferred
2. It also does not account for the fact that bisulfite sequencing coverage the top strand **OR** the bottom strand, but not both

A solution to this might be to use just Read 1 for single-end alignments to Lambda, I guess you want to use it as a control for the bisulfite conversion only anyway? Oh and yea, don't use `bam2bed` here. I hope this helps?

**Comment by NomiCentarix** [comment]
This answer was very helpful to me.
The explanation about the discrepancy with `bamtobed` was especially important - I didn't think in this direction.
Regarding the first part of your answer - I am still thinking about this (and will check it).
For now I think this issue can be closed.
Thank you very much!
Nomi

**Comment by FelixKrueger** [comment]
Excellent, let me know if further questions arise.
