### ISSUE TITLE
merging samples from different runs

### ISSUE THREAD

**Issue by newwbeee** [FelixKrueger/Bismark#389]
Hi Felix,
I have a sample set that was twice. What is the best way to combine the data from both runs ?
do you suggest bismark2bedgraph to combine ? or is there a better way? I have them in two separate folders as below.
I want to make sure I dm doing it right.
I tried this: 
bismark2bedGraph   --buffer 40G --dir  ez_met_merged -o oga2set1set2.bedGraph.gz /methylextract_step5/CpG_context_oga2-ez_R1_val_1_bismark_bt2_pe.deduplicated.txt.gz step3_bismark/methylextract/CpG_context_oga2-ez_R1_val_1_bismark_bt2_pe.deduplicated.txt.gz

When I combine them The file size is not doubled. this is what I got when I used ls -l in command line
file merged after bismark2bedgraph: 259886961 :   oga2set1set2.bedGraph.gz. (combined file size)
                                           input file 1: 222670285 :  oga2-ez_R1_val_1_bismark_bt2_pe.deduplicated.bedGraph
                                         Input file 2  : 219226259 : oga2-ez_R1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz

**Comment by FelixKrueger** [comment]
Hi @newwbeee 

If this is the same library and you simply want to merge the same technical replicate you have three options here:
1. you could merge the initial FastQ files, and then repeat the repeat the entire procedure 
2. You could merge the BAM files, or even use multiple files for `deduplicate_bismark`. This would leave you with a single deduplicated BAM file that could then be extracted and transformed to a merged coverage file.
3. Or indeed - as you did -  simply use the CpG* calls from both technical replicates as the input for the coverage file generation.

In theory they should all lead to the same outcome. If I had to choose I would opt for option 1., simply because it leaves you with fewer files to deal with. 

By the way, coverages files are not expected to double in file size as for some positions you just add a few more counts which should compress well. The file content in terms of methylation calls should of course reflect the merged count. 

I hope this helps.

**Comment by newwbeee** [comment]
Thank you very much Felix,
Indeed very helpful.
