### ISSUE TITLE
Bismark output: M-bias plots not horiontal lines

### ISSUE THREAD

**Issue by ceciliaRR63** [FelixKrueger/Bismark#390]
Hi,
I'm trying to find the parameters that would work best for my analysis but it seems like something is wrong because my M-bias plots are anything but almost-horizontal lines. Trying to address the problem, I trimmed my raw data using the "--clip_R1" and "--clip_R2" options but the plots look even worse. Any ideas?
![JBE6_ADN_R1_fastq gz_val_1_bismark_bt2_pe M-bias_R1](https://user-images.githubusercontent.com/73841654/97892503-5e243900-1d30-11eb-88db-a1a43e858250.png)
![JBE6_ADN_R1_fastq gz_val_1_bismark_bt2_pe M-bias_R2](https://user-images.githubusercontent.com/73841654/97892510-61b7c000-1d30-11eb-87c5-9f831bdd3e1b.png)

**Comment by FelixKrueger** [comment]
Hi @ceciliaRR63 

Before we start: if you type `bismark2report` you should get a nicer HTML report of the M-bias, that will also allow you to mouse-over to see the actual positions and values.

Let's start with the good news:  both the CHG and CHH methylation levels seem to be very low, and are (almost) flay lines, indicating good bisulfite conversion efficiency. 
Read 2 has two exceptions to this: position 23 appear methylated a bit more: not sure why this is, but my guess is that there is a specific sequence that is causing this. Secondly, the last position of R2 appears fully methylated. This is a consequence of adapter trimming (the adapter starts with AGATC, so Read 2 never ends in A, or AG, or AGA etc), but this is fine.

The number of methylation calls is well as the CpG methylation curve appear somewhat spiky. My guess would be that this is a consequence of reads that come from, or align to the exact same position in the genome. Which type of library was this, and what exactly did you specify for trimming from the 5' ends?

All in all the CpG methylation is kind of hovering around 30%, my guess is that the spiky-ness is caused by a relatively small amount of 'contaminating', or hight copy number sequences.

**Comment by ceciliaRR63** [comment]
Hi @FelixKrueger
Thank you so much for your prompt response. 
The bismark2report command worked perfectly and it is very helpful. As for the problem concerning the last position of R2, I don’t really understand why because I did “--clip_R1 5 --clip_R2 5 --rrbs --paired --retain_unpaired” on the trimming option, thinking this would help to reduce bias, but if this isn’t that important. Ok. 
I used a RRBS library performed with the MspI restriction enzyme and Illumina sequenced. When I first trimmed my raw data without clipping the last 5 bp from the 5’end, the M-bias plots were pretty flat, with only one position having a spiky look. Maybe it’d be better to leave as it is without any initial clipping?
And one last question (attached file): I am comparing my results with those of a track hub containing methylation results for ESC on UCSC. And I’ve noticed that for some CpG I have two results (on the C and on the G). Is there any way, using bismark, to  have the methylation of the CpGs by calculating the “mean” between the C (forward strand) and the G (reverse strand)? Thank you so much!
![rrbs_ucsc_sample](https://user-images.githubusercontent.com/73841654/98004838-b1f65700-1df0-11eb-820f-d1b25431db87.jpg)

**Comment by FelixKrueger** [comment]
OK that's interesting, doing RRBS would certainly help explain the spikyness you are seeing. The reason for this is that there are only so many MspI fragments in the genome, and it is well known that some of these fragments turn up thousands of times (they might even get picked up in the FastQC Overrepresented Sequences table). I am sure they will be the reason for most effects you are seeing.

Next up, RRBS data should should not be trimmed on the 5' ends as the reads should all start at the `CGG` sequence motif. Using `--clip_R1 5 --clip_R2 5` would effectively remove a lot of methylation calls that are completely valid. 
Also, trimming 5bp from the 5' end of reads has no influence on the last position on the 3' end in the read (the one furthest to the right). The rate of hight methylation at this point is something that you have will have to accept as an effect of adapter trimming (it only means that if the very last position in the read happens to be a `C` it is allowed to stay, but a last position `A` will be removed. This doesn't mean that the `C` at the position is wrong, but for reads that all end in exactly that position you might indeed see a methylation bias. Since the number of times and positions at which this phenomenon will occur is probably negligibly low, I would simply forget about it. If you are still concerned you could use the option `--ignore_three_prime_r2 1` during the methylation extraction to simply ignore 1bp -  but then again I wouldn't bother.

The option `--rrbs` is the one that removes 2 bp from read 1s which are affected by adapter contamination, and also removes 2bp from the start of R2. These positions are affected by artificially low methylation that is introduced during the fill-in procedure (see here for further details: https://github.com/FelixKrueger/TrimGalore/tree/master/Docs).

I am not exactly sure that I understand the last question, but I think the answer is: yes. While the Bismark coverage file is at single-C resolution (i.e. you see calls for Cs, as well as for Gs (which are in turn Cs on the reverse strand)), you do have the option to process the coverage files further using `coverage2cytosine`. This script will relate the methylation calls back to the genomic reference sequence, and it also has an option `--merge_CpG` to merge the calls of two consecutive Cs into a CpG dinucleotide entity (some also call this dyads). It even has the option to specify a level of discordance that is tolterated for this merging process. Just type `coverage2cytosine --help` for further, more detailed information.

I hope this helps?

**Comment by ceciliaRR63** [comment]
Hi Felix! I followed your suggestion and it all works fine now. And, yes,  coverage2cytosine was exactly what I needed. Thank you so much for your time and your extended explanations! Keep the good work!

**Comment by FelixKrueger** [comment]
Thanks very much for the kind words, all the best with your experiments!
