### ISSUE TITLE
How to get methylation analysis for specific region in BAM file

### ISSUE THREAD

**Issue by devenderarora** [FelixKrueger/Bismark#391]
Dear Sir,
I am trying to get allele specific methylation analysis from BAM file. I tried calling 

bismark_methylation_extractor -p --gzip --bedGraph --comprehensive sample1.bam

and it gave output successfully. 

I am particularly interested in getting allele specific methylation output and extracted region of interest from BAM file and re-run the bismark_methylation_extractor gene1.bam with and w/o -p flag but it ended up with an error:
Now testing Bismark result file test.bam for positional sorting (which would be bad...) The id for read1 and read2 are not same. This might be the result of sorting the paired-end SAM/BAM files by chromosomal position which is not compatible with correct methylation extraction. Please use an unsorted file instead or sort the file using 'samtools sort -n' (by read name). This may also occur using samtools merge as it does not guarantee the read order. To properly merge files please use 'samtools merge -n' or 'samtools cat' .

Please share How can I get allele specific methylation. We have identified certain genes using RNAseq data and wants to check if methylation is the reason for such changes. I tried different ways but not able to get any positive lead.

Thanks 
Devender Arora

**Comment by FelixKrueger** [comment]
Hi Devender,

For paired-end methylation extraction it is imperative that you keep the 2 files of a read pair together in the BAM file, like so:

```
Read1_1 ...
Read2_1 ...
Read1_2 ...
Read2_2 ...
...
```

Depending on how you extract records from the BAM files, paired-end alignments may be split up, which will then in turn render the methylation extractor unable to find proper pairs (and rightly so). Here is an example:   

```
                                 |         gene of interest                 | 

R1: ------------->
R2:                                              <--------------

```

 `samtools view` would in this case remove R1 (as it does not overlap your gene of interest), but keep R2 (which does overlap the gene of interest).

There are a number of options for you here:

- I don't quite understand why you need to filter your file at all. Why can't you just import the methylation calls into e.g. SeqMonk, and then go to your gene of interest and take a look? This would only take a few seconds, and is just the thing you should be doing. More information on how to this can be done may be found here: https://www.bioinformatics.babraham.ac.uk/training.html#bsseq.  

- you could write a quick script that makes sure that the filtered BAM file only contains proper paired-end records, and no single reads of a read pair.

- Alternatively, instead of filtering on the BAM level, you could filter on the coverage file level (`cov.gz`). This file does contain all the methylation information of all reads, so you can simply use a subset of it.

Finally, I think there is slight mis-conception with the term "allele-specific" here. For normal methylation analyses it is not possible to assign reads to one allele or the other without specific methodology, e.g. using [SNPsplit](https://github.com/FelixKrueger/SNPsplit). You probably want to use "locus specific", am I right?

I hope this helps,
Best, Felix

**Comment by devenderarora** [comment]
Thankyou so much. This really helps in a big way.
