### ISSUE TITLE
Bismark Mapping issues for Amplicon sequencing dataset

### ISSUE THREAD

**Issue by aayushraman** [FelixKrueger/Bismark#392]
Hi @FelixKrueger  

I hope you are doing well. I am trying to map the 150 bp paired-end dataset to the amplicon (region of interest from the human genome). The mapping efficiency is below 1% for most of the dataset. However, when I align the R1 and R2 reads separately, the alignment seems to > 70%. I am confused about why this is the case. I tried aligning R1 + R2 reads to the human genome, then also, my mapping efficiency is low. I have run bismark across different settings described below.

I have attached a sample dataset and the amplicon reference seq and bismark index files for your reference. The R1 and R2 fastq **files contain one read-only.** I used Bismark (ver 0.22.3), bowtie2 (ver 2.4.1), and samtools (ver 1.10) for the analysis of the dataset. 

**Run 1: --non_directional for paired-end read**

`bismark --genome amplicon -1 4Post1101520_S10_L001_R1_001.fastq.gz -2 4Post1101520_S10_L001_R2_001.fastq.gz --non_directional -p 2 -B 4Post1101520
`
The Mapping efficiency is 0% for this run.

**Run 2: --non_directional for R1**

`bismark --genome amplicon 4Post1101520_S10_L001_R1_001.fastq.gz --non_directional -p 2 -B 4Post1101520_1
`

The Mapping efficiency is 100% for this run with the starting position of the alignment at 428bp of the amplicon. The match is an exact match of 151 bp (the fourth column of the bam file has the value as 151M).

**Run 3: --non_directional for R2**

`bismark --genome amplicon 4Post1101520_S10_L001_R2_001.fastq.gz --non_directional -p 2 -B 4Post1101520_2
`

The Mapping efficiency is 100% for this run with the starting position of the alignment at 15bp of the amplicon. The match is an exact match of 151 bp (the fourth column of the bam file has the value as 151M).

**Run 4: --non_directional for paired-end read + low min score**

`bismark --genome amplicon -1 4Post1101520_S10_L001_R1_001.fastq.gz -2 4Post1101520_S10_L001_R2_001.fastq.gz --score-min L,0,-2.5 --non_directional -p 2 -B 4Post1101520_low
`

The Mapping efficiency is 100% for this run (_--score-min L,0,-2.5_). However, when I inspect the mapping, it seems that R1 read maps perfectly, whereas the other reads map at a different position with a lot of mismatches and indels (_Cigar Code: 40M4I20M3I4M1I5M8I9M7I1M3I8M1D1M2I20M2I13M_). Therefore, I have the following questions:

1. I cannot understand why inconsistencies in my alignment when I align the R1 & R2 read separately compared to R1+R2 together? Any advice to improve the mapping efficiency of the paired-end reads?

2. Can you please explain the arguments --score-min L,0, -0.2 (default) in detail?

Thanks a lot. Looking forward to your comments.

Best,
-Ar 

[sample.zip](https://github.com/FelixKrueger/Bismark/files/5528708/sample.zip)

**Comment by FelixKrueger** [comment]
Hi -Ar,

After some initial head-scratching I determined that the solution to this has a fairly trivial solution:

Both reads align well within that fragment, one to the CTOT, the next the OT strands. So the reason why a paired-end alignment gets rejected can really only be that there is something that makes the PE alignment discordant.
As an example, reads might not be oriented in a proper paired-end fashion, e.g.: `<------    -------->` or `------>.   --------->`, or - and this was indeed the case here, the read insert size was longer than the default cutoff of 500bp. 

If you increase the maximum fragment size to e.g. `-X 1000`, the fragment aligns perfectly well with a fragment length of 564bp. So this is what you want to be doing.

Briefly regarding the score min function, this funtion determines how many penalties a read is allowed to have before it get's tossed out. For end-to-end alignments, this value has to be negative. A mismatch 'costs' a penalty of -6, an insertion or deletion costs -5 to open the gap, and a further -2 for each basepair inserted or deleted. So a 3bp insertion would cost (-5 + -6) = -11.

`L,0,-0.2` is a **L**inear function, starting counting with an offset of **0**. The final number, **-0.2** is allowed penalty score per bp of read, so it scales with the read length. In your specific example, the allowed penalty score per read would be:

0 + (-0.2 * 151) = -30.2

Since a mismatch costs -6, you would tolerate up to 5 mismatches per read before tossing it out, or any combination of mismatches/insertion/deletion up to this score.

Lastly, in your example with `L,0,-2.5` you would have a maximum tolerated error rate of 

0 + (-2.5 * 151) = -377.5

Which is equivalent of tolerating ~62 errors in the read to produce a 'valid' alignment. Clearly this is **not** what you wan to be doing here (or at any point really).

I hope this clears things up? Good luck with your results!

**Comment by aayushraman** [comment]
Hi @FelixKrueger,

Thanks a lot for the detailed reply. It is very helpful and clears a lot of my questions. I appreciate it.

1. Does a mismatch include only non-bs mismatches or includes C to T or G to A conversion?

2. I have a question regarding -N (number of mismatches) and -L (length of the seed substring) arguments. If I provide -N 1 -L 10 in my bismark run and my read length is 150 bp per R(1|2) read (i.e., 300 bp R1+R2), does it mean that the total number of mismatches it can tolerate would be 30?

Thanks,
-Ar

**Comment by FelixKrueger** [comment]
To 1: Mismatches here are indeed only non-bisulfite mismatches, the methylation states are taken care of by using a 3-letter alignment approach.

To 2: The short answer is: the `--score_min` function governs the total number of penalties per read. So the total score for the default mode is ~ -30, or roughly 5 non-bisulfite mismatches, and this is **per read**.

The options `-N` and `-L` merely govern the length and mismatches of the sequences used for the multi-seeding of a read. In short, a longer read will be chopped into several little subreads (for which the aforementioned options apply), and as long as one of these shorter reads aligns to the genome the alignments will get extended to the entire read length. I don't think I have ever changed these options in the last 10 years to be honest....

**Comment by aayushraman** [comment]
When you say **per read**, you mean R1+R2 read in a paired-end context.

**Comment by FelixKrueger** [comment]
With per read I mean up to 5 mismatches for R1, and 5 for R2. So up to 10 mismatches for a pair of 2x151bp (which seems fair). Makes sense?

**Comment by aayushraman** [comment]
Thanks a lot for answering all my questions. Much appreciated!

**Comment by FelixKrueger** [comment]
You are very welcome!
