### ISSUE TITLE
Deduplication step and Bisulfite conversion for RRBS dataset

### ISSUE THREAD

**Issue by aayushraman** [FelixKrueger/Bismark#399]
Hi Felix, 

I hope you are doing well. I have a couple of more questions regarding the analysis of the RRBS dataset. 

1. In one of your tutorials, I saw that you recommend that we not perform de-duplication for the RRBS dataset. Can you explain why that is the case? Moreover, I saw you refer to your paper: "Quality Control, trimming and alignment of Bisulfite-Seq data" (http://www.epigenesys.eu/en/protocols/bio-informatics/483-quality-control-trimming-and-alignment-of-bisulfite-seq-data-prot-57). For some odd reason, I am NOT able to access it. Can you please share your paper? Thanks.

2. I would like to know what is the accepted method or metric for the calculation of BS conversion rates/efficiency? In some literature, I saw researchers calculating C to T conversion at unmethylated non-CpG dinucleotides (i.e. 1 - ((CHH_meth + CHG_meth)/(CHH_meth + CHH_unmeth + CHG_meth + CHG_unmeth)) ) or C to T conversion at unmethylated CpC dinucleotides (i.e. 1-((CCH_meth)/(CCH_meth + CCH_unmeth)) ). I am interested to know which one is preferred and why?

Thanks,
-Ar

**Comment by FelixKrueger** [comment]
Hi -Ar,

To 1): We tend to make it very clear that RRBS data should **NOT** be deduplicated as a matter of course because this could easily eliminate >90% of all the data (see slide 32 here: https://www.bioinformatics.babraham.ac.uk/training/Methylation_Course/BS-Seq%20theory%20and%20QC%20lecture.pdf). 

RRBS data can only be-duplicated if a UMI (unique molecular identifier) tag has been used to discriminate individual fragments. 
The protocol at the Epigenesys website is really nothing we host, so you might want to contact them about the dead link. The protocol was really just a step-by-step description of the individual steps involved, which would by now probably be a little outdated anyway...

To 2):
 
I have tried to write up a few points about [bisulfite conversion efficiency](https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#bisulfite-conversion-rate---considerations) in the FAQ section, let me know if you have any further questions.

**Comment by aayushraman** [comment]
Thanks a lot for a quick reply. Appreciate it!
