### ISSUE TITLE
Change of FLAG values in v0.14.4

### ISSUE THREAD

**Issue by PeteHaitch** [FelixKrueger/Bismark#41]
Hi Felix,

I'm a little confused re the change in v0.14.4 noted in the release notes:

> Changed the FLAG values of paired-end alignments to the CTOT or CTOB strands so that reads can
be properly displayed in SeqMonk when imported as BAM files. This change affects only paired-end
alignments in --pbat or --non_directional mode. In detail we simply swapped the Read 1 and Read 2
FLAG values round so reads now resemble exactly concordant read pairs to the OT and OB strands. 
Note that results produced by the methylation extractor or further downstream of that are not
affected by this change. FLAG values now look like this:

                                      Read 1       Read 2

                              OT:         99          147

                              OB:         83          163

                              CTOT:      147           99

                              CTOB:      163           83

When a read1 is aligned to CTOT or CTOB its FLAG is set that the read is "second in pair" when it is really the first in the pair. Similarly, when read2 is aligned to CTOT or CTOB its FLAG is set that the read is "first in pair" when it is really the second the pair. Is my understanding correct? 

Is the change then just a workaround so Seqmonk can display these in the expected visual orientation or is it something more to do with the definition of first read vs. second read in PBAT data? I'm a little worried that it means I can no longer simply parse the FLAG to infer whether it is read1 or read2 (e.g., will I have to additionally parse the XR/XG tags to infer this information?)

**Comment by FelixKrueger** [comment]
Hi Pete. If I remember correctly SeqMonk determines paired-end alignments by looking for the 'I am Read1' FLAG, and then adds the length given by the TLEN field. Now as you said, for PBAT alignments Read 1 would be the first in the pair but align more 3' in the genome, which would result in the starting position of R1 minus the fragment length (because it is negative) that Bismark determined in the TLEN field, which means that the read pairs start, end and orientation would be wrong.

So it is a bit quirky either way, because I felt that Bismark's way of giving the TLEN field is fine (or correct in the way you described), but Simon also has a point in saying reads that where R1 is more 3' in the genome are considered discordant and there has been a change in SeqMonk along the way that would now ignore these reads and no longer import them. So from our point of view the swapping of read FLAGs is more SeqMonk cosmetics because the methylation extractor uses the XR/XG tags and not the FLAGs anyway. The SAM format just never expected there to be four strands... Hope this doesn't break to much on your end. Cheers, Felix

**Comment by PeteHaitch** [comment]
Thanks for the explanation, Felix. I like to work directly with whatever Bismark produces, so I'll grab some PBAT data to test out and adjust my code accordingly.
