### ISSUE TITLE
bismark_methylation_extractor output

### ISSUE THREAD

**Issue by zhangaicen** [FelixKrueger/Bismark#413]
Dear sir,
  Recently I tried to treat plant methlation data using bismark followed up by cgmap. My bismark version is v0.19.0, and the command is below: 
bismark_methylation_extractor -p --no_overlap --bedGraph --CX --cutoff 5 --comprehensive --counts --buffer_size 20G --gzip --cytosine_report --genome_folder /gss1/home/zqq20190923/user/zac/index/nip/meth_rice7.0/ --multicore 10 8n-1M-LDA3003_combined_R1_bismark_bt2_pe.deduplicated.bam 

I want to obtain relative information about CG, CHH, CHG methytion, but when looking into the log document, I find that when 
generating the bedGraph file  and the coverage file, it only indicates sort the CpG context, and final get one  bedGraph file and one coverage file, so why couldn't I get the files of CHH and CHG? 
![QQ图片20210206162852](https://user-images.githubusercontent.com/67790480/107113206-6c867180-6898-11eb-980c-9960d3a59744.png)

**Comment by FelixKrueger** [comment]
I believe if you scroll a bit further up in the log you would see that all context files are temporarily written into the a temporary file before sorting, and that file is probably named after the first file it encountered. So most likely, that file contains all cytosine contexts, despite being named `CpG.....tmp`.

You should be able to easily check if it was done correctly: if you count the number of line (which is equivalent to the number of Cs found in the experiment) you would expect up to ~45 million (for the human or mouse genome), but up to ~1.1 billion if you include non-CG context. If rice is much bigger than the human or mouse genome the numbers would be higher, but I suppose the idea would still be the same. A command for this could be:

```
zcat 8n-1M-LDA3003_combined_R1_bismark_bt2_pe.deduplicated.cov.gz | wc -l
```

Or, since you generated the genome-wide cytosine reports as well you could simply look at the first few lanes of the output to see if all contexts are there:

```
zcat 8n-1M-LDA3003_combined_R1_bismark_bt2_pe.deduplicated_CX_report.txt | less
```

Having said all that, I would highly recommend you upgrade to the latest version as v0.19.0 is already more than 3 years out-of-date.

**Comment by zhangaicen** [comment]
Thanks for your prompt answer, and if I update the version now ,  should I map the fastq files again? or I can use the previous bam files from the old-version bismark for methylation extractor? And I also want to know if the  *_CX_report.txt can be used as input file of cgmaptools convert bismark2cgmap directly?
 
Thanks. AicenZhang

**Comment by FelixKrueger** [comment]
I don't think you will need to re-map the data, I only thought there were some changes with some of the downstream scripts since then (mostly usability things though, just check the release notes if you think there might be something that could affect you). I personally have never used cgmaptools myself, so you would have to ask those authors more directly I am afraid.

Best, Felix

**Comment by zhangaicen** [comment]
OK, I just begin to learn something about methylation, and spend many time to search the answers about these issues,  so thank you very much for your patient.
