### ISSUE TITLE
how Bismark to determinate  the OT/CTOT/OB/CTOB  strand at 0% methylated region 

### ISSUE THREAD

**Issue by biofmzhang** [FelixKrueger/Bismark#416]
hello!
When the C isn't methylated in a sequence, so how Bismark to determinate  the OT/CTOT/OB/CTOB  strand in non-directional libraries data? because they are exactly the same after C->T or G->A conversion.

In my test data(0% methylated region of human sapiens), I found Bismark can do it(determinate  the OT/CTOT/OB/CTOB  strand )

Thanks!

**Comment by FelixKrueger** [comment]
The alignment strand is decided for an entire sequence, and isn't decided for each C on their own. As an example, if you get a good alignment for the C > T converted sequence sequence against the C > T converted genome, the alignment strand is `OT`. Consequently, the methylation call at all positions that are a cytosine in the genome (top strand sequence) are done as `C/T` calls.

Very occasionally, there are sequences that are very special (maybe it is those you are referring to for non-directional data? An example are telomeric reads which are hexamers looking like this: `(TTAGGG)n`, e.g.:

```
TTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGG
```

In standard directional or PBAT data, this wouldn't be a problem: as the sequence doesn't contain any Cs, all methylation calls would be simply a `.`. In non-directional however, the sequence could either align to that sequence strand, but also align equally well to the sequence:

```
AATCCCAATCCCAATCCCAATCCCAATCCCAATCCC
``` 

Under these circumstances, some very specific sequences may occasionally be assigned to the wrong strands indeed. 'Luckily', this is increasingly rare as this only affects sequnces which:
- do not contain any Cs
- would are 100% methylated 
- are so short that this effect occurs, a single base that breaks the above rules would allow the unique assignment. This occasionally was a problem back in the days when sequences were 28 or 36bp long, but nowadays sequencing typically goes up to 2x150bp, where unique assignments are nearly always possible
- the above telomeric sequence is a bit special still, because the sequences are multi-hexamers of varying length, so most likely the sequence would align to several places, and therefore get kicked out and not ever appear in the final BAM file anyway

I hope this answered your questions, and didn't pose too many new ones :)

**Comment by biofmzhang** [comment]
Thanks!  
In my non-directional libraries data, a region sequence(all Cs with 0% methylated ), Bismark can determinate the OT/CTOT/OB/CTOB strand  in the output file(bam) . theoretically,It can't be sure that and drop it?  or Bismark determinate the OT/CTOT/OB/CTOB strand in a random way?

**Comment by biofmzhang** [comment]
Thanks!
In my non-directional libraries data, a region sequence(all Cs with 0% methylated ), Bismark can determinate the OT/CTOT/OB/CTOB strand in the output file(bam) . theoretically,It can't be sure that and drop it? or Bismark determinate the OT/CTOT/OB/CTOB strand in a random way under these circumstances?

**Comment by FelixKrueger** [comment]
I think if a region has several Cs, and they are found converted (i.e. unmethylated), then the strand assignment works fine. Issues may arise only in sequences with no Cs at all, or 100% methylation for the entire region.

**Comment by biofmzhang** [comment]
sorry,I have a problem with my expression.

I express the issue : in a  reigon ( all C with unmethylated ), Can  Bismark determinate the OT/CTOT/OB/CTOB strand of non-directional libraries data?
or, to put it another way ,if bismark handle the general sequencing data (eg,WGS),Can  Bismark determinate the OT/CTOT/OB/CTOB strand?

Thanks!

**Comment by FelixKrueger** [comment]
Not exactly sure if I understand the exact issue, but I am pretty sure that the answer is: yes, that's what Bismark is made to do.

**Comment by FelixKrueger** [comment]
haven't heard back from this for a while, so I assume all is working well.
