### ISSUE TITLE
Sequential mapping strategy

### ISSUE THREAD

**Issue by Am3Lie** [FelixKrueger/Bismark#430]
Hi Felix,

I encounter some issues concerning DNA methylation analyses with Bismark because of the reference genome I use. Sorry in advance if I’m not very clear, I’m brand new in bioinformatics analyses.
I work on a plant genome whose assembly is no totally finished (the genome is not phased) so the FASTA file contain both haplotype 1 and haplotype 2 sequences as well as unplaced sequences.  Consequently, there is redundancy between both haplotypes. If I well understand how Bismark works, it only map a read if the algorithm can assign it to a unique position. In the case of my reference genome, I think that a proportion of my reads map with the same score to common positions in haplotype 1 and haplotype 2 and consequently I lost them for the following steps.

To deal with it and keep the information of allelic origin, I tried to map sequentially on haplotype 1, haplotype 2 and unplaced sequences by recovering each step unmapped reads (first I mapped on haplotype 1, recovered the unmapped reads, mapped them on haplotype 2 and I started again with unplaced sequences). 

Here are the mapping results I obtained:
-	Analysis 1 = For the mapping on the complete reference genome (hap1+hap2+unplaced sequences): 55%
-	Analysis 2  = For the sequential mapping: 79%
-	Analysis 3 = Mapping only on haplotype 1: 62%
Surprisingly, the mapping % is quite high with the sequential strategy and I wondering if it generate some mistakes by acting like this.

To compare the results between sequential and complete genome strategies, I continued until the bismark methylation extractor step.
In the end, If I compare the content of the cytosine report, I have 15 179 750 commons sites between analysis 1 and 2. But, I also have 3 402 962 specific sites linked to analysis 1 and 2 637 382 specific sites linked to analysis 2. If I understand correctly, these different sites correspond to sites which were covered at least once in one analysis but not in the other. The mapping must therefore have an impact on this, but I can’t understand how? Could you give me some explanation on what could happen in my sequential strategies and witch could explain why I lost information? 
I addition, I was wondering if working on only one haplotype can be a solution in my situation despite the loss of allelic origin information or if it exists another solution.

Thanks in advance,

Amélie

**Comment by FelixKrueger** [comment]
Hi Amélie,

This is indeed a somewhat tricky situation - also a situation I have never dealt with I should mention. 

Having several haplotypes which overlap in large parts is indeed not what Bismark is particularly made or suited for, because as you say, similar regions may be removed from the mapping results entirely. 

I am note sure if I understood you correctly: do you have a genome with a common reference sequence as well as some additional haplotypes added on top, or is it really more that you've got two sub-species of the same plant that were crossed, and you have rough but independent genome assemblies for each of the different haplotypes?

If you have a common reference sequence for most parts, you could indeed map to the entire genome while specifying `--ambiguous` as well as `--unmapped`. Reads that are in common should count towards both genomes. Reads that were classified as ambiguous might then need another round of mapping to each the hap1 and hap2 genomes. I would then probably need to add these calls to the calls from the alignments that are in common between the haplotypes, and proceed with these merged sets (the merging can pretty much be done at any stage, but before using `bismark2bedGraph` to generate a coverage file). 

In case you have two more or less separate genomes, comparisons will be harder (and I have never done this myself). You might probably be better off aligning to each of the haplotypes and unplaced sequences on their own, and take it from there. It will get tricky to make comparisons on a local level if the genomes are not completely equivalent, but you should be able to make comparisons on a global level... Sorry if I can't be more helpful.

**Comment by Am3Lie** [comment]
Hi Felix,

Thank you for your answer.

Actually, most of the sequence is common between hap1 and hap2 except for heterozygous parts.
If I understand well your proposition, we need to map the ambiguous reads to both hap1 and hap2 FASTA files separately. However, by mapping on both haplotypes with the ambiguous reads arising for the first mapping, are we not artificially increasing the coverage (or is it negligible)? In contrast, if we choose to map the ambiguous reads only on hap1 (to be closer to the real coverage), don’t we lose for hap2 overlapping DMRs between hap1 and hap2?

Otherwise, for curiosity, I am wondering what went wrong in the sequential mapping strategy I used. Have you an idea of what could happened during mapping that generates mistakes?

Best,

Amélie

**Comment by FelixKrueger** [comment]
Hi Amelie,

I went back to your first note to understand the mapping strategy a bit better, but I am not sure I get it exactly right. I am sure it's me though. These allele-specific strategies can quickly get quite confusing, and it might really help to sketch out the strategy in addition to text.

To avoid the confusion with several reference genome sequences we have so far resorted to simply N-masking only the positions in the genome where we know SNVs exist (see here for the approach taken by [SNPsplit](https://github.com/FelixKrueger/SNPsplit)). So if I shy away from giving you any how-to tips, it is really because it probably involves a more thoughtful approach, and I don't really want to lead you in the wrong direction.

Thinking about it again, I am getting confused myself. If we assume that some of your haplotype reference sequences are present more than once, but with a slight difference in sequence, chances are that the reads will map to one or the other haplotype better than to the other. These reads would thus map allelically, and they would be kept. If the haplotypes differed in bases concerning C/Ts in the genome (and most normally occurring SNVs are C>T transitions), you wouldn't see these difference as the genome and read C>T conversion would make it impossible to determine whether you are looking at a SNV position or a change in the methylation state. 

I guess what you would have to do probably is to post-process the results of the mapping of the second round of alignments, and determine whether a given read aligns to equivalent positions for both haplotypes, and then decide on a case by case basis whether you would like to keep the read or not. Apologies again for not being able to offer any helpful solution right away. 

Maybe as an idea, couldn't you go the other way and determine the differences between your haplotypes, and then generate a unified reference genome that has the regions or positions of difference masked out by Ns? In that case, you might even be able to use SNPsplit for the allele-specific processing...

**Comment by Am3Lie** [comment]
Hi Felix,

thank you for your time and your answer.
For now, I’m trying the proposition you previously suggest, that is mapping the ambiguous reads to each hap1 and hap2. I will pursue in this way to compare the cytosine report I will obtained to my previous results. 

Concerning the N-masking, I already red your paper about SNPsplit approach, but I’m not sure I can apply it to my case (and there is not VCF file available for my reference genome). For now, generate a N-masked unified genome is out of my competences, but maybe I will look for this if I can’t find another alternative.

Otherwise, the C/T issue that you suggest could actually explained why my sequential mapping % is such high and this may generate mistakes. In this case, my sequential strategy doesn’t seem appropriate here. I attached a slide which sums up the sequential strategy I tried.

Thanks for your help, I’ll be pleased if you have any other suggestions.


[sequential_strategy.pdf](https://github.com/FelixKrueger/Bismark/files/6392617/sequential_strategy.pdf)
