### ISSUE TITLE
Error in alignment/'[W::bam_hdr_read] EOF marker is absent. The input is probably truncated'

### ISSUE THREAD

**Issue by hchetia** [FelixKrueger/Bismark#439]
I keep getting these errors while running Bismark alignments-
**Parameters used-
bismark -n 1 -p 24 --bam**

**Chromosomal sequence could not be extracted for NB500961:994:H5TYMBGXF:2:22107:24573:1
Chromosomal sequence could not be extracted for	NB500961:994:H5TYMBGXF:3:12604:14738:11193_1:N:0:ATCGTCTC**
*Chromosomal sequence could not be extracted for	NB500961:994:H5TYMBGXF:3:12604:14738:11193_1:N:0:ATCGTCTC*

Once the runs are over, I keep getting error when deduplicating using bismark-
'[W::bam_hdr_read] EOF marker is absent. The input is probably truncated'

 Bismark Version: v0.22.3
bowtie2-align-s version 2.4.1
samtools 1.12
Using htslib 1.12
Genome used GRChm39

![image](https://user-images.githubusercontent.com/64626735/120408365-e2698980-c31c-11eb-834b-66cde1d95b69.png)

**Comment by FelixKrueger** [comment]
Hi @hchetia

first of all apologies for the late response, but I was travelling in the Scottish highlands with no power or internet connection...

Statements like `Chromosomal sequence could not be extracted ...` may occur whenever the alignment falls to the very edge of a chromosome, so that the downstream sequence of the last two bases can't be extracted. This is normally an extremely rare event, and can safely be ignored (it sometimes occurs more frequently for unpolished genomes with lots of (small) contigs or scaffolds, or when the data is aligned to a reduced version of the genome, e.g. in-silico RRBS fragments). The overall number for this is reported in the Bismark report, and it is typically much smaller than 0.1%.

Regarding the error message you are getting, I have to admit I don't exactly know why you are seeing this. If I were you I would not use `-N 1` as it makes the alignments much more time-consuming, and `-p 24` is almost certainly not advised as you will need >50 cores for 2 alignment threads (as at least two alignments are running in parallel). If you want to speed things up, I would probably use `--parallel 2` instead.

Did your run finish successfully? Did you get a Bismark report? Did you see any error messages on the screen during the run, or could you email me the log file? Thanks, Felix

**Comment by hchetia** [comment]
Hi @FelixKrueger  I did finish my run successfully. The error reported above is generated when I try deduplicating the alignment output.
I have emailed you the report and the log file.
Sorry for a late response!
Yes, I have now modified my script to use --parallel 2, thanks. My data is from a WGBS expeirment.

**Comment by FelixKrueger** [comment]
Hi @hchetia 

From the files you sent through it looks like Bismark did not finish, the report file does not contain the final mapping stats, and the log file is truncated at ~23M reads. While I can't say with certainty what happened, my guess would be that you ran either out of memory, or out of disk space. 

The reason for me assuming this is because you seem to have opted for SAM output instead of BAM output, the default. This is not only ~10 times larger in size, but I think `--parallel 2` also requires BAM files to start.

So the reason why the deduplication is complaining about a truncated file might be just that - a truncated file.

You said that you succeeded in the meantime, did everything run to completion (including a complete mapping report?)

**Comment by hchetia** [comment]
Sorry there has been some mix up. Let me rerun with the following params- --parallel 2 --bam and reshare the logs.

In the meanwhile, I am not sure about running out of disk space or memory though. Here is the output for ulimit -a. Please let me know if that could really be the case.
![image](https://user-images.githubusercontent.com/64626735/122110946-26649000-cded-11eb-884b-4281fa2b161f.png)

**Comment by hchetia** [comment]
Hi Felix, The rerun worked and I am not getting any errors now. 
Do you have an idea about why I was getting the error earlier with the old -p24 and N-1 params?
Thanks for the help.
Hasna

**Comment by FelixKrueger** [comment]
Hi Hasna,

No I am afraid I don't know the reason. `-p 24 -N 1` will take hugely more cores and memory while probably being slower as well, so one reason might be that the process got killed by your system for using too many resources - but why only 22 million alignments in?! Let's just agree that it all works now if you continue with sensible parameters, shall we? Good luck!
