### ISSUE TITLE
Parameters for PE RRBS data processing

### ISSUE THREAD

**Issue by samschaf** [FelixKrueger/Bismark#444]
Hello! I have matched bisulfite and oxidative bisulfite paired-end RRBS data from mouse brain which I have processed with TrimGalore and Bismark. The intention was to be able to calculate DNA hydroxymethylation levels by subtracting the oxBS from the BS signal. However, I am questioning whether I've processed my data correctly since I am getting a very high amount of noise (negative values) from this subtraction. I also see some discordance when comparing beta values I generated with Bismark to betas generated with BSMAP, which I previously used to process the same data. I was wondering if you could weigh in on whether my parameters in TrimGalore and Bismark seem correct? 

Here is the workflow I used:

trim_galore --paired --rrbs file.fastq.gz --clip_R1 5 --clip_R2 5 --fastqc

bismark_genome_preparation--verbose /home/samschaf/scratch/A30P/hippocampus/trimmed_data/oxBS/PX1068/ --path-to-bowtie /home/samschaf/projects/def-koborlab/koborlab/tools/bowtie2-2.3.4.1-linux-x86_64 --yes

bismark --genome /home/samschaf/scratch/A30P/hippocampus/trimmed_data/oxBS/PX1068 -1 file1.fq.gz -2 file2.fq.gz -q -o /home/samschaf/scratch/A30P/hippocampus/aligned/oxBS/PX1068 --multicore 3

bismark_methylation_extractor --paired-end file.bam --no_overlap --report --bedGraph --cutoff 5 --CX --counts --genome_folder /home/samschaf/scratch/A30P/hippocampus/trimmed_data/oxBS/PX1068 -o /home/samschaf/scratch/A30P/hippocampus/meth_ext/oxBS/PX1068 --comprehensive

Thank you!

**Comment by samschaf** [comment]
Just to add, the library was prepared with Illumina adapters, and I'm interested in looking at both CpG and non-CpG methylation levels, which is why I chose --CX and --comprehensive in the methylation extractor

**Comment by FelixKrueger** [comment]
HI @samschaf

It's been a looong time since we processed (ox)RRBS data ourselves... We have had a few projects with oxBS in the past (genome-wide, not RRBS), and I remember that we also often struggled with negative values... Here are my comments regarding your commands.

**Trim Galore**
We would not recommend using `--clip_R1 5 --clip_R2 5` for RRBS data for the following reasons: 
- RRBS data is guaranteed to start with a (C)CGG position, which `--clip_R1 5` will remove. Since the 5' of Read1 should carry the genomic methylation status, you will essentially remove valuable data.
- the option `--rrbs` will in effect already specifies `--clip_R1 2` internally, as the first 2 bases of R2 carry an artificial methylation state (see the RRBS Guide here: https://github.com/FelixKrueger/TrimGalore/tree/master/Docs). I suppose using `--clip_R1 5` in addition to that will again remove a fairly large proportion of your data, without any need for it.

If I were you I would simply use this command:
```
trim_galore --paired --rrbs --fastqc file_R1.fastq.gz file_R2.fastq.gz 
```


**bismark_genome_preparation**: fine

**bismark_methylation_extractor**: Fine, a bog-standard command should work fine here (assuming you used the trimmed files as input)  

**bismark_methylation_extractor**: 
Most options you specified are fine (and are already on by default, e.g. `--no_overlap --report --counts`)

If it was me I would definitely not use a cutoff of 5 at this stage, because it will simply swallow all positions below this threshold and there is no going back. We would recommend to report everything first, as you can always apply depth filters afterwards as you see fit. The results you get downstream, especially the BS-oxBS subtraction, might be sensitive to how you apply thresholds and how you quantitate the methylation, e.g. at single C resolution, over larger regions such as 100 CpG windows etc. I am convinced that it is also at this stage that you will introduce the discrepancies...
 
I would probably simplify the command to something like this in the first instance (the coverage file generation does not require a genome folder):

**CpG context only:**
```
bismark_methylation_extractor --bed --comprehensive  file.bam
```

If you want to look at non-CG context as well, you can simply generate another non-CG coverage file:
```
bismark2bedGraph -o nonCG_output.cov.gz --CX CH*
```

This command would use the CHH_* and CHG_* context files from the methylation as input files for a new bedGraph/coverage file generation. If you wanted to generate CpG/nonCG files as well to relate the calls back to the genome sequence you could simply run `coverage2cytosine` using the CpG or nonCG coverage files as input.

This would definitely be a set of commands we would use to process data. Regarding noise, negative values and other downstream issues you need to look carefully at what you do downstream with the data. I hope this helps?

**Comment by samschaf** [comment]
Hi @FelixKrueger, thank you so much for your reply and recommendations! I'll try processing my data without the --clip and read cutoff options and see if this improves things.

**Comment by FelixKrueger** [comment]
I hope this has all worked well?!
