### ISSUE TITLE
Failed to close filehandle Input/output error

### ISSUE THREAD

**Issue by DLGisch** [FelixKrueger/Bismark#456]
Hello,
I have this error with --parallel and without too.

>>> Writing bisulfite mapping results to S15_R1_001.fastq.gz.temp.1_bismark_bt2_pe.bam <<<

Reading in the sequence files /N/slate/dg/ILMN_678/S15_R1_001.fastq.gz.temp.1 and /N/slate/dg/ILMN_678/S15_R2_001.fastq.gz.temp.1

Created C -> T as well as G -> A converted versions of the FastQ file S15_R2_001.fastq.gz.temp.3 (83911887 sequences in total)

Failed to close filehandle Input/output error

Created C -> T as well as G -> A converted versions of the FastQ file S15_R2_001.fastq.gz.temp.4 (83911887 sequences in total)

Failed to close filehandle Input/output error

Command without --parallel 4

Bismark-0.23.1/bismark --genome genomes_homo_sapiens_GRCh38 -q --non_directional -o ILMN_678 --temp_dir ILMN_678 --nucleotide_coverage \
-1 /N/project/hongao_transfer/ILMN_678/S15_R1_001.fastq.gz -2 /N/project/hongao_transfer/ILMN_678/S15_R2_001.fastq.gz

When I receive this error WITHOUT --parallel 4 command  I just resubmitted  the then the  program run, but very slow  run 60h and Processed  190000000 sequence pairs so far.

When I received this error WITH --parallel 4 I try to run again, but received the same error again.

Can you help me understand this error?

Thank you,
Debora

**Comment by FelixKrueger** [comment]
Hi Debora,

This is somewhat odd. This `die` statement should come directly after the sequences were C>T transformed, and closing the filehandles is required to ensure that the transcribed files are not truncated.

A couple of things I have noticed:
- is there a chance that you don't have enough disk space? Maybe you can lose the `--temp_dir` so that the temp files are (temporarily) written to the output file (where tehy will be removed by the end of the run)?
- aligning to the human genome in non-directional mode probably takes ~5 cores, and 20GB of RAM for a single thread, so `--parallel 4` will take at least 20 cores and >80GB of RAM. Is there chance that the job scheduler is unhappy about that and kills it?
- the file names do not look like they have beend trimmed. it is almost never a good idea to align reads without and trimming, I can only recommend you your Trim Galore for this purpose. Also, if the data is non-directional there is a good chance the data will need additional trimming on the 5' ends (e.g. ~10-20bp for the Zymo Pico-Methyl kit... see here for recommendations: https://github.com/FelixKrueger/Bismark/tree/master/Docs#ix-notes-about-different-library-types-and-commercial-kits)

**Comment by FelixKrueger** [comment]
Haven't heard back, so assuming all is well?

**Comment by DLGisch** [comment]
Sorry for the delay in answering. The cluster was having problems, but I tested it and now it works.

**Comment by FelixKrueger** [comment]
Excellent, I'm glad it's now all working well.
