### ISSUE TITLE
Bismark non-directional mapping

### ISSUE THREAD

**Issue by bigbangbalance** [FelixKrueger/Bismark#461]
Hi Felix,

Forgive me if it was posted elsewhere, but I am just confused about the non-directional mapping results in a very specific scenario. 

My sample is fully methylated at all Cs. I used paired-end BS sequencing to check the methylation status. So I just want to know what is the difference between R1 mapped to CTOT and R1 mapped to OB. How can you separate them? Because in this scenario, CTOT and OB are just the same, right?

Thanks,
Larry

**Comment by FelixKrueger** [comment]
Hi Larry, 

This is indeed a very special case (and so are sequences that do not contain any Cs at all (e.g. telomeric hexamer repeats (TTAGGG)n ).

I think the short answer to your question is: in such cases, CTOT and OB (and CTOB and OT) can indeed not be discriminated.  This is in fact a problem because normally, sequences that produce several equally good alignments, either on the same strand or against a different strand/in a different conversion state), are getting removed as count as ambiguous alignments. Since these sequence do not only align equally well, but also to the same position in the genome, Bismark takes the active decision not to discard these reads, but preferentially sort them to the OT and OB strands.

This appeared to be a sensible solution most of the time - but it can also go wrong, as we experienced ourselves with telomeric sequences. If you imagine a read consisting of (TTAGGG)n repeats, it might look like this:

```
TTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGG
```

Apart from the fact that such a repetitive read will almost certainly get removed as it can't be aligned uniquely, you will see that the read does not contain any Cs whatsoever (we used just telomeric sequences as the genome in this case). If I remember correctly, however, the preferential strand assignment rule described above may very well result in alignments that look fully methylated (just like (AATCCC)n ). This is undoubtedly a special case which gets increasingly unlikely as reads get longer, it is a issue nevertheless.

**Comment by bigbangbalance** [comment]
Hi Felix, thank you so much for your detailed explanation!

**Comment by shounak-lanl** [comment]
Hi Felix,
I determined that my library is non-directional  (Mapping efficiency 54.1 %) by running your diagnostic posted on another discussion forum.
However, when I run deduplicate_bismark and then, bismark_methyl_extractor, the number of called C's (rather the number of lines in the ".bismark.cov" file is is about 4-fold lower than if I run the same deduplication and methylation calling steps on alignments assuming a directional library (mapping efficiency ~30%).

I am using the latest version of bismark available on anaconda (0.23.1).

Greatly appreciate your help on this!
Thank you!
Shounak
