### ISSUE TITLE
Difference between the average coverage of extractor report and mapped reads

### ISSUE THREAD

**Issue by salehsereshki** [FelixKrueger/Bismark#466]
Hi,

Thank you for your great tool. I have several WGBS data. After aligning them against the corresponding reference genomes I got the alignment output report. There is a percent called "Mapping efficiency". I assume this number is the percent of all reads which had a unique map. Based on this number I Calculated the average coverage of reads based on this formula: 

average coverage = (_mapping efficiency_*total number of reads )*(2*read length)/(genome size)

For further analysis, I have run the extractor part of Bismark. Then based on the genome-wide Cytosine report(.CX_report) I calculated the average coverage. This time I got the average of the (count methylated) + (count unmethylated) of all Cytonsines.

There is a huge difference between these two numbers for all of my samples. For example for one of the samples, the first computation shows an average coverage of 12 while the second computation gives me only 1.2 average coverage.

Can you guide me on why I get this difference?

**Comment by FelixKrueger** [comment]
I think the first formula to calculate a genome coverage is pretty good:

`average coverage = (mapping efficiency total number of reads )(2*read length)/(genome size)`

A small caveat here might be that in BS-seq, the average fragment size often is rather short, most likely because of the bisulfite treatment itself. So even if you have say 2x 125bp paired-end libraries that would nominally add up to 250bp, in reality you might see that the majority of all fragments is between 80 and and 150bp long. So I suppose a better measure than 2x starting read length might be the paired-end fragment length of aligned read pairs, a measure that would probably bring down the number by a fair amount (30-50%?).

Next, you will probably see that that reads overlap substantially, especially for long reads lengths. During the methylation extraction, methylation from Read 2 are completely ignored as soon as R1 and R2 overlap, to avoid introducing a coverage bias for overlapping calls. This will almost certainly also reduce the number of calls markedly. 

Then you might also lose some calls due to adapter trimming and quality trimming, and you may end up sequencing regions that that are simply not very C-rich, so even though you may have a certain coverage, it doesn't necessarily mean that the underlying number of cytosines is proportional.

These are just a few points I could just think of... In the end, you might just have to accept it as it is, and work with what you've got.
