### ISSUE TITLE
Trouble with the Bismark coverage file

### ISSUE THREAD

**Issue by VikArz02** [FelixKrueger/Bismark#467]
Hello! I have trouble with the Bismark coverage file. When combining promote and methylate sites, I found an error in the Bismark coverage file. Chromosomes do not match the reference genome (only one reference is used). What could be the mistake?

**Comment by FelixKrueger** [comment]
I'm sorry but that isn't exactly giving me anything to work with. Can you provide examples, commands, version and specify what you think the 'error' is? Cheers!

**Comment by VikArz02** [comment]
Of course, I'm sorry I didn't think about it right away!
I used hg38. Aligned according to the bismarck protocol with changes (--non_directional --score_min L,0,-0.2)
`#load cov file
cov_report=read.table("/mnt/lapd/Vika_data/RNF_raw/meth/.../*.cov.gz", sep="\t", fill=FALSE, strip.white=TRUE)
#name column
colnames(cov_report)=c("chr", "start", 'end', 'per', 'meth',  'unmeth')
#filter file
cov_report=cov_report[cov_report$per > 10, ]

#load  promoter sites 
library(biomaRt)
library(GenomicFeatures)
require(TxDb.Hsapiens.UCSC.hg38.knownGene)

txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
genes <- genes(TxDb.Hsapiens.UCSC.hg38.knownGene)
mart <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
bm <- getBM(attributes = c("ensembl_gene_id",'entrezgene_id'),  mart = mart)
names(genes) <- bm$ensembl_gene_id[match(genes$gene_id,bm$entrezgene_id)]
#promoters 
prom=promoters(genes,downstream=0)

#merge cov_report  and promoter  data frame by range start and end position
 setkey(prom, start,end)
map_t_cpg=foverlaps(cov_report,prom, type="within",nomatch=0L)`

And after this code, I get a file where the chromosome on which the gene is located does not match the chromosome in the cov file.

But if I use promoter  file  with  chromosomes and mapped files like that:
`#merge cov_report  and promoter  data frame by range start and end position
 setkey(prom, **CHR**, start,end)
map_t_cpg=foverlaps(cov_report,prom, type="within",nomatch=0L)`

I can find the correct positions, but I know that some of them are not. And with bedGraph file is the same situation.

**Comment by FelixKrueger** [comment]
Hmm, it looks more like you've got a problem with your R script rather than the coverage file. I'm afraid I can't help you with debugging your R script, but the most obvious source of collision is that genome version. 

The R script seems to use a genome from UCSC (UCSC.hg38.), was the genome you used also the UCSC genome? Ensembl uses numbers 1, 2, ... X, Y, MT, whereas UCSC/NCBI use chr1, chr2, ..., chrX, chrY, chrM. Also, I guess random and unplaced scaffolds might be different. This is where I would start...

**Comment by VikArz02** [comment]
I did it! But the problem is that references cannot be that different. There were genes that are on chromosome 15 but connect to the 1. So I don't think this is a problem in the script.

**Comment by FelixKrueger** [comment]
Hmm, well from my side the problem is fairly simple: the genome you used for the alignments will have certain IDs for each chromosome in the FastA file, e.g. `>15` (Ensembl) or `>chr15` (NCBI/UCSC). Both the BAM and coverage file will use exactly that name as well.

If you now load some kind of annotation via Biomart, UCSC, TxDb, and manipulate things in R, this really has nothing to do with the coverage file as such, wouldn't you agree? 

You are probably right that the genome references are not that different (as in the sequence is the same). With the annotations, I am afraid this is not so straight forward, as exemplified by the infamous difference already in the name of chromosomes...

**Comment by VikArz02** [comment]
If everything were in "chr"... the position in the chromosome in the cov file differs from the reference one. And not by a couple of orders of magnitude (with the same reference). But again, only a few are different, could these just be misleading methylation sites?

**Comment by FelixKrueger** [comment]
I'm really sorry but I still don't quite understand the issue here. How would you define, or create, misleading methylation sites? Are you saying that most of the time everything works just as expected, but that there are a few positions that come up in the annotation that are missing from the data, or the other way round?
