### ISSUE TITLE
Best practices for NEB EM-seq trimming & analysis?

### ISSUE THREAD

**Issue by semenko** [FelixKrueger/Bismark#509]
I'm performing sequencing with the NEB's Enzymatic Methyl-seq Kit -- which performs adapter ligation (with 5mC adapters) then enzymatic methylation conversion of reads.

I'm processing data with trim_galore then Bismark -- but wasn't quite sure the best practice for trimming data.

R1 trim_galore run with `--illumina --paired`:
![image](https://user-images.githubusercontent.com/167135/179284575-f8970811-4789-4ccd-8474-34ec5622db89.png)

R2 trim_galore run with `--illumina --paired`:
![image](https://user-images.githubusercontent.com/167135/179284548-1c86d80d-2469-4c55-92ca-16b34ad7b7ed.png)

Q: Is there a best-practice for trimming EM-seq data? From the above plots, I'm tempted to `--clip_R1 10 --clip_R2 10` (I understand there's some end-repair bias, so I should at least set `--ignore_r2 2` -- but I wasn't sure beyond that, with the noise for those first 10 bp.)

Q: Is there any benefit to clipping versus just `--ignore 10 --ignore_r2 10` in bismark? (I suspect clipping speeds up alignment, but beyond that?)

**Comment by FelixKrueger** [comment]
Hi NIck,

To be perfectly honest I don't exactly know the answer to what the best practices for EM-seq sequencing is (I am assuming you are using Illumina data?).

I have once been linked the protocol for the library preparation (https://www.neb.com/protocols/2019/03/28/protocol-for-use-with-large-insert-libraries-470-520-bp-e7120), but I think this is very much for the lab procedure only.
The library structure was supposed to look like this:
```
[P5]-[EM-seq adaptor]-[Insert]-[EM-seq adaptor]-[P7] 
```

Given this structure I would assume that reads will actually start reading parts of the EM-seq adapter first, and will also end in EM-seq adapter before reaching the Illumina P7 adapter. So my initial thoughts would be that default Trim Galore trimming (maybe even leave out `--illumina` to allow auto-detection) would not hurt, but it might leave in some of the EM-seq adapter data - which is almost certainly also the reason for the biases you are seeing at the 5'-end. These biases are potentially also present at the 3' ends, but are more difficult to spot due to varying fragment lengths.

With regard to your first question:

I suppose it would actually be a great idea to find the documentation about the EM-seq adapters and/or best practices from NEB of what their recommendations are (document it here, and also add it to the table of kit-recommendations within the Bismark docs). In the meantime, I would agree that removing 10-20bp from the start (and ends?) of reads would probably be the safest options (`--clip_R1 15 --clip_R2 15 --three_clip_R1 15 --three_prime_clip_R2 15`).

Q: Is there any benefit to clipping versus just --ignore 10 --ignore_r2 10 in bismark? (I suspect clipping speeds up alignment, but beyond that?)

 The thing is, if the sequence at the start is correct, as in is exactly like the genomic sequences (or its bisulfite converted form), clipping and ignoring should be equivalent. However, if the sequence bias at the start brings in any form of artificial sequence that is not present in the (bisulfite-converted) genome, sequences will get have errors (mismatches of InDels) and thus get removed from the dataset altogether. So in these cases, trimming is definitely the preferred option.

Yet another method would be to use local alignments, as this should just soft-clip reads on the ends if they do not align well to the genome. The problem with this is though that some methods look like genomic sequence but contain long stretches of artificial methylation states (e.g. the Accel Swift kit produced Reads2 with 10-20bp of 100 methylated Cs at the 5' ends). In these cases, soft-clipping does not trim and leaves in tons of spurious methylation calls, something you really don't want to have.

The best option indeed would be to understand what the EM-seq does exactly, and then take deliberate action.

**Comment by semenko** [comment]
Thanks for the detailed reply! I've reached out to NEB for more guidance -- some of their papers suggest they just use the default trim_galore settings.


EM-seq uses the Illumina adapters, 5mC protected so they aren't EM-seq converted. The sequences are buried in [NEB's paper here](https://genome.cshlp.org/content/31/7/1280.full):
`A5mCA5mCT5mCTTT5mC5mC5mCTA5mCA5mCGA5mCG5mCT5mCTT5mC5mCGAT5mC*T` and `[Phos]GAT5mCGGAAGAG5mCA5mCA5mCGT5mCTGAA5mCT5mC5mCAGT5mCA`  (which if you remove the 5mC just become the Illumina adapter sequences `ACACTCTTTCCCTACACGACGCTCTTCCGATC*T and [Phos]GATCGGAAGAGCACACGTCTGAACTCCAGTCA`)

**Comment by semenko** [comment]
NEB passed along two bits of info:

Some of their analyses are this Nextflow pipeline: https://github.com/nebiolabs/EM-seq/blob/master/em-seq.nf -- it dosn't do any trimming, just fastp with ~default settings.

In private correspondance, they passed along:
"""
We trim 5 bases from the 5’ end of Read 1 and Read 2 to remove any cytosines with an incorrect methylation status. We see no benefit if we trim beyond that, for example up to 10 bases, as there is really no shift in overall methylation status of the control DNA (lambda and pUC19) or NA12878 (our standard test DNA).
"""

From our own EM-seq runs, we see bias for the first 10 bp of 5'.

**I'll update the docs to suggest recommended conservative parameters of `--clip_R1 10 --clip_R2 10 --three_clip_R1 10 --three_prime_clip_R2 10` and with a comment about only cutting 5bp.**

**Comment by bhanratt** [comment]
`--clip_R1 10 --clip_R2 10 --three_clip_R1 10 --three_prime_clip_R2 10` throws error `Unknown option: three_clip_r1`
I think it should be `--clip_R1 10 --clip_R2 10 --three_prime_clip_R1 10 --three_prime_clip_R2 10` @FelixKrueger

**Comment by FelixKrueger** [comment]
Thanks, that's now fixed. The changes should soon appear on the new docs: http://felixkrueger.github.io/Bismark/bismark/library_types/#em-seq-neb
