### ISSUE TITLE
Confusing methylation statistics in alignment step

### ISSUE THREAD

**Issue by wenzelm** [FelixKrueger/Bismark#514]
Hi Felix,

I have recently started using Bismark (version 0.23.0) and have compared the output to another pipeline (BSMAP+MethylDackel). I get very different results between the two pipelines and I am very confused by the methylation statistics in the Bismark alignment output. I fear something went badly wrong, but can't work out what...

My genome is 426 Mbp long, of which c. 100 Mbp are Cs and c. 100 Mbp are Gs. Here are some Bismark alignment statistics (from PE_report.txt)

```
read pairs  	efficiency	 Meth. CpG 	 Meth. CHG 	 Meth. CHH 	 Total C 
36,147,322 	70.00%	 	 322,945	 246,420 	 738,630 	 1,701,432,111 
42,225,492 	71.30%	 	 382,543 	 291,342 	 870,962 	 2,024,196,743 
32,511,056 	69.10%	 	 282,382 	 216,853 	 648,615 	 1,508,903,284 
43,383,499 	67.90%	 	 373,912 	 289,927 	 864,268 	 1,981,610,939
```
These stats translate into c. 0.1% methylation in each of the three contexts. This is very low and it makes no sense to me why Bismark thinks that there are up to 2 billion Cs in the reference genome (shouldn't this be 100 million?). I've checked the numbers of methylated cytosines in the bedGraph output from the later steps of the Bismark pipeline and they are consistent with the above (a bit lower, but same ballpark). After feeding the bedGraph files into Metilene I get no differentially methylated Cs or DMRs at all.

In contrast, BSMAP and MethylDackel paint a much more reasonable picture of the data:

```
read pairs	aligned	 Meth. CpG 	 Meth. CHG 	 Meth. CHH 
36,147,322 	85.3%	 3,898,462 	 3,026,591 	 8,538,422 
42,225,492 	85.9%	 4,554,909 	 3,536,444 	 9,940,357 
32,511,056 	85.2%	 3,496,030 	 2,710,770 	 7,697,273 
43,383,499 	83.7%	 4,689,894 	 3,640,628 	 10,257,733 
```

That's a lot more methylation; using my 100 million Cs as a reference, these stats translate to 3%-10% methylation, and Metilene identifies thousands of DMRs, which is great.

What is going on with Bismark? Here is my code (file names removed for simplicity):

` bismark_genome_preparation --parallel 4 genome/`
This makes two bowtie2 indices and I can see no issues (bowtie2-inspect looks fine).

`bismark -o --temp_dir -p 8 genome/ -1 -2`
`deduplicate_bismark --bam -p -o --output_dir`
`bismark_methylation_extractor --parallel 3 --gzip --bedGraph --cytosine_report --genome_folder genome/ -o -p`
All these commands ran fine and produced the expected output files.

I would be grateful if you had any ideas. Currently, I'm trusting the BSMAP+MethylDackel pipeline, but I really would like to work out what is going on with my Bismark results...

Thanks and best wishes,
Marius

**Comment by FelixKrueger** [comment]
Hi Marius,

I wonder if there is some kind of misunderstanding. The number of methylation calls you show above are the total calls measured in your data, it has - at this point - nothing to do with the total number of Cs in the genome. The values which should be comparable are the % methylation values reported - are they similar at all? I'd be very happy to have a closer look at this, if you could provide some details of the kit you used for the library prep, and maybe share some of the FastQC reports?

Cheers, Felix

**Comment by FelixKrueger** [comment]
Hi Marius, 

Thanks for the details. I would agree, the QC metrics for the run are looking nice. For EM-seq, we have recently determined that it is a good idea to do trimming of the reads on their 5' ends by 10bp from either side (see the [recommendations](https://github.com/FelixKrueger/Bismark/tree/dev/Docs#ix-notes-about-different-library-types-and-commercial-kits) or [in this thread](https://github.com/FelixKrueger/Bismark/issues/509). You samples are more or less not methylated at all (0.1% methylation in any context), so there is a chance that you would not really see a bias in the methylation at all - because it practically cannot go down any further. In the interest of best practices, you should probably still consider re-doing the trimming and re-run the alignments afterwards.

Regarding the way the methylation of the overall Bismark alignment report, it is calculated like so: 
- for each read, a number of methylation calls is performed - namely whenever a C in the genome was covered by a read. The methylation call can be methylated or unmethylated, and the numbers are tallied up. This gives a final number for each cytosine context, for CpG context in your example above this would be:

```
Total CpG methylated: 322,945
Total CpG unmethylated: 413,783,886
```
This results in an average methylation in CpG context of:
```
322945 / (322945 + 413783886) * 100 = 0.077985914702286, rounded to 0.1%
```

This number is not per position, or for any individual position, but really just a grand total of *anything* that has happened during the alignment and methylation calling process.

If you wanted to get the % methylation values per position, you should run the methylation extractor, followed by bismark2bedGraph (this can be achieved using the option `--bedGraph` during the `bismark_methylation_extractor` step.

Bismark does by default consider any position this at least 1 call. If MethylDackel applies a filter for 5X coverage at this step, I am pretty sure that this step introduces the bias in the results you are seeing. If you wanted to re-capitulate this with Bismark you could specify the option `--cutoff 5` - however I wouldn't recommend doing this as you might lose a lot of data - and introduce biases!

I hope this clears a few things up, and hopefully shows that the coverage filter applied by MethylDackel is the step that causes the differences you see between the two different workstreams.

**Comment by wenzelm** [comment]
Hi Felix,

Thank you for the suggestion to clip the reads - I hadn't spotted that, but it turns out to make little difference to the results. Disabling the 5X methylation filter also did not resolve the discrepancy between the two pipelines. 

I've now tried some other aligners, and it turns out that BSMAPZ is the outlier. BWA-meth (3-letter aligner) and GSNAP (wildcard aligner) result in methylation calls similar to what bismark gives me (though bismark gives me by far the lowest evidence of methylation). Here is a table summarising the CpG bedGraph files from MethylDackel (default settings) run on the BAM files generated by the four aligners (counting entries in the bedGraph files with >0 %methylation frequency):

```
		Total CpG	methCpG		%methCpG
bismark		44755745	107045		0.2%
bsmapz		47800168	4140904		8.7%
bwa-meth	47762686	301367		0.6%
gsnap		47880468	330040		0.7%

```

Very interesting, but no idea where BSMAPZ pulls out all these extra methylated Cs. That's a problem for another day. Thank you for helping me understand the workings of Bismark better!
