### ISSUE TITLE
sort CpG report

### ISSUE THREAD

**Issue by igordot** [FelixKrueger/Bismark#55]
I just discovered that the cytosine report (*.CpG_report.txt.gz) is not sorted. It seems to be sorted by position, but not by chromosome. Is there a reason for that? Can they be sorted in the future?

**Comment by FelixKrueger** [comment]
Hi Igor, there is indeed a reason for that. The cytosine report is in the same order as the coverage file, and potentially not covered chromosomes (or contigs) are appended at the end. The coverage files themselves are sorted by chromomal position but there is no clear order of the chromosomes because it is not a given that all chromosomes were covered in the experiment.
If we were to write the reports sorted by chromosomes we would either have to read the entire coverage file into memory (which could be huge for non-CG context) or use a multiple-pass strategy. I think it would be easier if you just ran a `sort` command on the coverage file instead if that is really desired.

**Comment by igordot** [comment]
Thanks for clarification. I wasn't sure if it was just an oversight.
