### ISSUE TITLE
Bismark report and M-bias plot

### ISSUE THREAD

**Issue by msierk** [FelixKrueger/Bismark#566]
I ran Bismark on some RRBS single reads generated by a collaborator.  I'm new to bisulfite analysis so I'm unsure how to interpret the results.  An example SE report is below.  Most of the mapping efficiencies were in the low 60's percent, which seems low.  I've also attached an M-bias plot.  I haven't found anything online that describes an upward slope like I see in all these samples, or the peak at ~70 nt.  Any suggestions for what is going on here or different Bismark parameters I should try?

`Bismark report for: ../trimmed/MDA_MB_468_NO_b_5mC_GTGATCCA_L002_R1_001_trimmed.fq.gz (version: v0.23.0)
Option '--directional' specified (default mode): alignments to complementary strands (CTOT, CTOB) were ignored (i.e. not performed)
Bismark was run with Bowtie 2 against the bisulfite genome of /vf/db/bismark/hg38/ with the specified options: -q --score-min L,0,-0.2 -p 2 --reorder --ignore-quals

Final Alignment report
======================
Sequences analysed in total:	45692857
Number of alignments with a unique best hit from the different alignments:	27477560
Mapping efficiency:	60.1%
Sequences with no alignments under any condition:	9947086
Sequences did not map uniquely:	8268211
Sequences which were discarded because genomic sequence could not be extracted:	0

Number of sequences with unique best (first) alignment came from the bowtie output:
CT/CT:	13740442	((converted) top strand)
CT/GA:	13737118	((converted) bottom strand)
GA/CT:	0	(complementary to (converted) top strand)
GA/GA:	0	(complementary to (converted) bottom strand)

Number of alignments to (merely theoretical) complementary strands being rejected in total:	0

Final Cytosine Methylation Report
=================================
Total number of C's analysed:	674041286

Total methylated C's in CpG context:	67329573
Total methylated C's in CHG context:	2049839
Total methylated C's in CHH context:	3262042
Total methylated C's in Unknown context:	5079

Total unmethylated C's in CpG context:	62620041
Total unmethylated C's in CHG context:	174813806
Total unmethylated C's in CHH context:	363965985
Total unmethylated C's in Unknown context:	165866

C methylated in CpG context:	51.8%
C methylated in CHG context:	1.2%
C methylated in CHH context:	0.9%
C methylated in Unknown context (CN or CHN):	3.0%
![MDA_MB_468_NO_b_5mC_GTGATCCA_L002_R1_001_trimmed_bismark_bt2 M-bias_R1](https://user-images.githubusercontent.com/56087985/217910428-b4d654df-c496-45f1-9913-efb8a1b1a04b.png)
`

**Comment by FelixKrueger** [comment]
Hi @msierk 

First, a word about mapping efficiency. You seem to be getting ~60% uniquely placeable reads, and almost another 20% or that aligns ambiguously (equally well to several places in the genome). This could be caused by the fact that you are enriching for similar regions (via the MspI digestion), and could also be caused by using single-end reads. Generally, longer reads align a little better (as in more uniquely), and paired-end reads align a bit better than single-end reads, even though for RRBS paired-end data has diminishing returns since the fragments are often quite short.

If you see distinctive peaks in the data, e.g. at 70bp, I would probably guess that these come from a single location where you have (for whatever reason) a lot of reads accumulated at the the very same position (such as a typical number of 10 reads per position, but one or a few locations with 1000 reads +. This should be enough to push the M-bias curve into a noticeable deviation from a straight line.

The upward slope could in theory be caused by artificial methylation caused by filling-in reactions (more [here](https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/RRBS_Guide.pdf)). This could be ameliorated by using the option `--rrbs` in Trim Galore ([see here](https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md#rrbs-specific-options-mspi-digested-material)), did you use that already?

**Comment by msierk** [comment]
Thanks very much Felix.  I did find a reference referring to the 70bp peak possibly being due to MspI producing a bunch of 70bp fragments, I think in repetitive regions.  (Can't find it right now, but I'll post here when I find it.) I will try out the --rrbs flag, thanks.

**Comment by msierk** [comment]
Just to close out this issue, [here](https://biologicalproceduresonline.biomedcentral.com/articles/10.1186/s12575-017-0054-5) is the article showing a peak at 74 bp for MspI fragments (in pigs).  (Figure 1) 

Also, [here](https://www.nature.com/articles/s41587-022-01336-9) is an article analyzing 5 different bisulfite sequencing platforms.  In Extended Data Figure 1 you can see the upwards drift in the M-bias plots for both NuGen and Diagenode.  I contacted the authors and their response was that it is probably related to the fact that many RRBS reads come from microsatellites which are highly methylated and longer than the read length (150), so they are enriched.  They didn't think it was something that needed to be corrected for in downstream analyses.
