### ISSUE TITLE
ONT amplicon bisulfite seq not working

### ISSUE THREAD

**Issue by fbustosf** [FelixKrueger/Bismark#569]
Hey, new here 
Ive been trying to use the new mm2 function to align my ONT amplicon seq reads. 
I built the genome with a fast amplicon, works fine
then when trying to run the fastq files I keep getting 

>>> Writing bisulfite mapping results to test2_bismark_mm2.bam <<<

Reading in the sequence file test2.fastq
[ERROR] failed to write the results: Broken pipe

any idea why this could be happening?

thanks!

**Comment by FelixKrueger** [comment]
Hmm, that doesn't really give me a lot of information to work with. Did Bismark start alright? Did it produce some alignments? Did you run out of resources, are there any alignment in the BAM file, or is it failing straight away?

**Comment by fbustosf** [comment]
Thanks for getting back so fast!

It did start. Attaching a txt with the run 

[error.txt](https://github.com/FelixKrueger/Bismark/files/10866216/error.txt)

**Comment by FelixKrueger** [comment]
I finally got the chance to look at the log you sent - and I am afraid I can't say. what exactly went wrong...

Bismark appears to start fine, minimap2 is found and also reports alignments, e.g. this is the first sequence:

```
d48e4aca-2a4f-4514-95c3-8a2159fc8dc9_runid=f0f7887b4bd4e707cb2a1e1f94bf25eac8972c48_read=24_ch=39_start_time=2023-02-24T16:56:06.723105+00:00_flow_cell_id=AOI020_protocol_group_id=bspkcc2ivan_sample_id=bspkcc_barcode=barcode74_barcode_alias=barcode74_parent_read_id=d48e4aca-2a4f-4514-95c3-8a2159fc8dc9_basecall_model_version_id=2021-05-17_dna_r9.4.1_minion_384_d37a2ab9`	16	Slc12a5_CT_converted ...
```

(as a side note: this probably wins the prize for the longest read-ID I have ever seen, I hope it doesn't break things downstream...)

The process then seems to move on past the find-initial-alignments-phase, but then shows the `Broken pipe` errors. I wonder if this maybe a MacBook issue? Which specs does your machine have, and which genome did you use, or was it just a single gene sequence? Do you have the option to test the same command on a Linux machine, e.g. an EC2 instance? Could you send me a handful of reads for testing on my end (via email?).

**Comment by FelixKrueger** [comment]
Hi Fernando,

I have found a fix for your issue, but I can safely say this is the weirdest thing I have ever seen!

I have tried many different things, and generally the alignments seemed to work well for a subset of 1, 2, 3..., 10 etc sequences - until they didn't. It really seemed to fail at non-reproducible points within your input file!?

Since it just returns to the command prompt, it must mean that not only all 4 instances of minimap2 get terminated, also Bismark exits without a further die message, or log entry (something seems to sends out the equivalent of a Linux `kill -9` command to Bismark itself...)

The only thing I could imagine could cause such a weird behaviour would be something equally weird - so I had a go at replacing suuuuper long readIDs in your sample with incrementing read IDs, e.g.: `@read_777`, @read_778`. And guess what: it worked! 

```
Final Alignment report
======================
Sequences analysed in total:	1000
Number of alignments with a unique best hit from the different alignments:	949
Mapping efficiency:	94.9%

Sequences with no alignments under any condition:	51
Sequences did not map uniquely:	0
Sequences which were discarded because genomic sequence could not be extracted:	0

Number of sequences with unique best (first) alignment came from the bowtie output:
CT/CT:	423	((converted) top strand)
CT/GA:	1	((converted) bottom strand)
GA/CT:	524	(complementary to (converted) top strand)
GA/GA:	1	(complementary to (converted) bottom strand)

Final Cytosine Methylation Report
=================================
Total number of C's analysed:	143431

Total methylated C's in CpG context:	1619
Total methylated C's in CHG context:	1528
Total methylated C's in CHH context:	2054
Total methylated C's in Unknown context:	165

Total unmethylated C's in CpG context:	30651
Total unmethylated C's in CHG context:	33133
Total unmethylated C's in CHH context:	74446
Total unmethylated C's in Unknown context:	3490

C methylated in CpG context:	5.0%
C methylated in CHG context:	4.4%
C methylated in CHH context:	2.7%
C methylated in Unknown context (CN or CHN):	4.5%


Bismark completed in 0d 0h 0m 10s
```

While I don't really have a great explanation for you why this happens exactly, I am pretty confident that we've got a fix for the issue nevertheless!

**Comment by fbustosf** [comment]
Thank you so much !
Hope this help other people here

**Comment by FelixKrueger** [comment]
All the best with your data!
