### ISSUE TITLE
[Question]: EM-Seq - Deduplication at Step 1 much before alignment

### ISSUE THREAD

**Issue by tamuanand** [FelixKrueger/Bismark#584]
Hi @FelixKrueger 

I had a question - more of a thought process - regarding deduping the fastq sequences before it reaches the aligner. 

http://felixkrueger.github.io/Bismark/bismark/library_types/ 
- `deduplication after alignment is recommended for EM-Seq`

http://felixkrueger.github.io/Bismark/bismark/deduplication/
- `The script deduplicate_bismark is supposed to remove alignments to the same position in the genome from the Bismark mapping output (both single and paired-end SAM/BAM files), which can arise by e.g. excessive PCR amplification.`

My thought process (and I want to know your opinion) - **_would I be missing out on something major if I go down this path_** 

- why not use something like `clumpify.sh` at Step 1 - dedupe the sequences - https://www.biostars.org/p/483594/ 
- the flag "dedupe" will remove PCR, tile-edge, and optical duplicates. All copies except one are removed for each duplicate

```
- Using clumpify.sh will allow you to do duplicate removal in an alignment independent manner.
- It will also make the size of the input files smaller thus reducing time required for alignment
- clumpify does NOT require alignments so it should prove more useful compared to Picard MarkDuplicates. 
```

Thanks

**Comment by FelixKrueger** [comment]
Hi Anand,

To be honest I have never used clumpify before, so I don't really have a very strong opinion. I can see that it might seem an attractive idea to reduce the size of the input files even before alignments; I would however be somewhat cautious because bisulfite-sequencing can theoretically lead to 4 different strands to get sequenced, and also the methylation states are encoded as differences in sequence. I am not sure a k-mer based approach would in this case be a advisable, but if you have time - why not try it out?
