### ISSUE TITLE
M-bias shows high drop of methylation at specific position

### ISSUE THREAD

**Issue by Rudern09** [FelixKrueger/Bismark#594]
Hello Felix,

I have RRBS data, 2x150bp, from human that show a strange pattern in the M-bias plots. There is a more or less dramatic drop of methylation levels at the fifth last position of R2.  In another issue, you suggested that this can come from a lot of reads accumulating at the the very same position. However, in my case, I am not sure it might come from any experimental biases as it is close to the end of the reads. Save option is to just cut the last 5 bases, but I am losing a bit of information by that. And also I would like to understand where this bias comes from.

To shortly explain the data and processing

trimming with: trim_galore --quality 20 --illumina --stringency 1 --rrbs --length 50 --paired
mapping with: bismark --bowtie2 ...
extraction with: bismark_methylation_extractor --paired-end 

After running this, the M-bias plot looked like this.

![F_11_FKDN230142689-1A_HNY7VDSX5_L2_1_val_1_bismark_bt2_pe nonCG_filtered M-bias_R1](https://github.com/FelixKrueger/Bismark/assets/135838817/4d20cf86-99fd-40da-8253-b885e2445800)
![F_11_FKDN230142689-1A_HNY7VDSX5_L2_1_val_1_bismark_bt2_pe nonCG_filtered M-bias_R2](https://github.com/FelixKrueger/Bismark/assets/135838817/e8f946c9-32e3-4e87-a56d-e34c78fd267a)

Accordingly, I set the parameters '--ignore_3prime 2' '--ignore_r2 2' and '--ignore_3prime_r2 1' to remove the biases from the ends.
Would you have concerns to go on with the data still having this drop at the last 5th. position? I am having 72 samples, for some the drop is larger, for some it is milder. 

Thank you!

**Comment by FelixKrueger** [comment]
I would recommend you use `bismark2report` as this generates a nicer HTML report that will allow you to hover over individual positions. For a nice summary of several files I would recommend to run `multiqc` in your processing folder to get all information (FastQC, trimming and Bismark) within a single, pretty report.

Regarding the spiky-ness of your M-bias plots I am pretty convinced that that this comes from individual loci that can explain the phenomenon.

One thing you should definitely keep in mind is the total number of methylation calls performed. I'll use CHH calls as an example, because calls in CpG are only 10-20% of that (number are a lot easier to gauge in the HTML report). You see around 2 million methylation calls on average across all of Read 1, with a marked reduction at higher value because RRBS reads are mostly shorter than 150bp in total. In contrast, for Read 2 you only have 400,000 calls at the very start of read 1, and have more or less no more signal beyond 50bp in Read 2. The reason for this is the overlap detection and removal whenever R2 starts overlapping R1. Since most reads are shorter than 150bp, and practically all reads are shorter than 200bp, using a 2x150bp paired-end run in RRBS is more or less completely wasting the information contained within R2, as the information is contained within R1 already (this is also mentioned in this [RRBS Guide](https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/RRBS_Guide.pdf).

Since the M-bias plot shows percentage methylation it may look very dramatic, but the underlying number of reads might be tiny (theoretically you only need 1 call across your sample to get a value of 0 or 100% methylation. This might look dramatic, but the consequence in comparison to the millions of calls elsewhere in all reads will almost certainly be negligible.

If I were you I would just myself the trouble, and just continue with a methylation extraction without any --ignore options set. Does this make sense?

**Comment by Rudern09** [comment]
Thank you very much Felix! In fact, I did not even consider the absolute numbers of the counts, but doing so it looks like this spiky-ness of the M-bias plot is really neglectable here. In that light it makes sense to me not to use any --ignore options, at least not for R2.

Thanks also for the hint with the visualisation. The bismark2report output looks nicer indeed.

May I ask you what sequencing metrics you would recommend for RRBS or what are you usually seeing/using? It seems that we waste a lot with this 2x150bp (which btw. was recommended by the sequencing company). So 1x100 bases (if available) would be maybe enough?
