### ISSUE TITLE
mbias plot methylation rate fluctuations

### ISSUE THREAD

**Issue by ertiaM** [FelixKrueger/Bismark#664]
![Bismark M-bias Read 1 (1)](https://github.com/FelixKrueger/Bismark/assets/72677277/7e518eeb-2392-4174-a7eb-4f2a36789c84)
![Bismark M-bias Read 2 (1)](https://github.com/FelixKrueger/Bismark/assets/72677277/4cd0ff9c-5563-4419-abab-236123948741)

The data I used has been processed by [fastqc](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/) and [Trimmomatic](http://www.usadellab.org/cms/?page=trimmomatic). Then the data has been processed by `bismark`, `deduplicate_bismark` and `bismark_methylation_extractor` as the manual told. 
As the mbias plots show, the methylation level in read 1 seems to be stable. However, the methylation read 2 is very volatile. May I ask the possible reasons for this fluctuations appears in this read 2 plot.

**Comment by FelixKrueger** [comment]
The steep drop at the beginning of Read 2 is almost certainly a consequence of a bias brought in by the end-repair of fragments, as discussed in this [QCFail article](https://sequencing.qcfail.com/articles/library-end-repair-reaction-introduces-methylation-biases-in-paired-end-pe-bisulfite-seq-applications/). Ignoring the first 2-4bp will alleviate this. I don't really know the reason why the levels are a meandering around the 80% mark in Read 2, and only reach the Read 1 levels ~100bp into the read - there clearly seems to be some technical reason. Maybe it has to do the sequencing run as such?

**Comment by FelixKrueger** [comment]
I don't think this has anything to do with the 3' trimming of low qualities, especially since the more variable part is at the 5' end. I personally would re-run the methylation extraction while using `--ignore_r2 4` or so (mouse over the curve to see when the levels are back to ~70-80%, and then go ahead and use the results.

You will also notice that the total number of calls in Read 2 goes down with increased length as a function of the overlap detection and removal, so all in all Read 1 will get some more weight anyways.
