### ISSUE TITLE
Very low mapping efficiency

### ISSUE THREAD

**Issue by gevro** [FelixKrueger/Bismark#674]
Hi,
I'm running bismark aligner / bowtie on samples prepared with IDT methylseq (used to be from Swift adaptase). These samples were prepared in the same way as prior samples that had good mapping efficiency, but this time they have low mapping efficiency (< 1%).

Because nothing changed for these samples relative to prior in term sof library prep, the recommendations for figuring out the reasons for low mapping efficiency don't apply: https://felixkrueger.github.io/Bismark/faq/low_mapping/

FASTQ analysis shows I'm correctly trimming the noisy parts of the reads. It is possible to share a subset of reads in case you can help figure out the issue?

Thanks!

**Comment by FelixKrueger** [comment]
I just had a look at your samples, and quality wise they look fine. In contrast to the Accel Swift kit, in this case Read 1 appeared to be G-poor, while Read 2 was C-poor. This would be the reason main why you are observing a low mapping efficiency. Indeed, adding the parameter `--pbat` which instructs Bismark to align to the CTOT and CTOB strands instead of the normal directional mode brought the mapping efficiency up to ~65%. Additionally, increasing the maximum fragment length to 1000 bp (up from the 500bp default), increased it further to ~75%.

So the good news is that all is fine, you just need to adapt the parameters a little. This is the command I used:

```
bismark --genome ~/GRCh38/ --pbat  -X 1000 --score_min L,0,-0.4 -1 P3L.R1.trimmed.fq.gz -2 P3L.R2.trimmed.fq.gz
```

**Comment by gevro** [comment]
Thanks so much!

We used the IDT/Swift single-cell methyl-seq kit: https://sfvideo.blob.core.windows.net/sitefinity/docs/default-source/protocol/xgen-adaptase-module-protocol.pdf?sfvrsn=a5a7e007_10
 -> See appendix A, page 9. Given the diagram on that page, does it make sense that these are appearing like --pbat libraries?

**Comment by FelixKrueger** [comment]
Yes this looks like a standard PBAT-style library prep. In addition, they mention this:

<img width="711" alt="Screenshot 2024-06-15 at 13 09 52" src="https://github.com/FelixKrueger/Bismark/assets/5870509/0a0c6183-f627-47bb-951e-f7c263b75790">

If the fragment length is generally quite short, you may want to consider trimming 10bp from the 3' end as well as from the 5' end. 

All the best!

**Comment by gevro** [comment]
Thanks!
