### ISSUE TITLE
directional and nondirectional 

### ISSUE THREAD

**Issue by iranianuser** [FelixKrueger/Bismark#694]
Hi Felix
I finished bismark alignment and extraction to the end. and I got the results 
but I didn't know anything about directional and nondirectional so I set the default option (directional) for bismark alignment.
My data was bisulfite-seq (WGBS) and now I read somewhere that bisulfite-seq libraries are non-directional. Is it true?
and should I do my analysis again? does it affect the results???

**Comment by iranianuser** [comment]
I want to do DMR analysis next....

**Comment by FelixKrueger** [comment]
Generally, it is very important to know they kind of sequencing and appropriate trimming. Here are some recommendations. If you can link the FastQC HTML reports, your trimming command and the Bismark mapping result stats I can probably help you a bit more.

**Comment by iranianuser** [comment]
Hi
I sent an email and attached what you mentioned.

thanks a lot

**Comment by iranianuser** [comment]
to this
fkrueger@altoslabs.com‬

**Comment by FelixKrueger** [comment]
apologies, the email got stuck in the spam folder...

The data is definitely directional, as R1 is C-low and G-rich. Also, you've got a mapping efficiency of nearly 80%. If the data was non-directional, the expected maximum mapping efficiency would be 50% tops. Since there is a bias at the start of reads you may want to include some clipping there, using a command like:

```
trim_galore --paired --clip_r1 5 --clip_r2 5 *_1.fastq *_2.fastq
```
Other than that you should be good to go!

**Comment by iranianuser** [comment]
OK, it's great ... 
Your answers always make me happy
I will try your suggestion
