### ISSUE TITLE
The feature to output all the multiple alignments

### ISSUE THREAD

**Issue by xie186** [FelixKrueger/Bismark#72]
Hi Felix, I'm wondering whether it's possible to add the feature to output all the multiple alignments (at least top 20 or 50?) in '.ambiguous.bam'. This feature will help me in two ways: 1) I'd like to develop a tool to determine the sources of reads using non-redundant nucleotide database. This feature can help me to do this. 2) I'm interested in how the BS-seq read mapping looks like in species like strawberry which is an octoploid species. The feature will help me. Thanks. 
Shaojun Xie

**Comment by FelixKrueger** [comment]
Hi Shaojun,

Thanks for your request. While I can see that such an option might be useful in your case I am afraid I have to say that Bismark in its current implementation is not geared towards producing this kind of output. 

The reason for this is mainly that we only ever report a single alignment in Bowtie 2 mode (or up to 2 alignments in Bowtie 1 mode) and base all decisions about the uniqueness of the alignment on this (or these) alignment(s) and/or the extra tags reported such as the `AS:` tags. To produce that kind of output you were thinking of, one would have to run the Bowties in `-a` mode (= all alignments for a given read) which would be a) incredibly slow and b) require a different handling logic than what Bismark is currently doing. 

So while the code is basically all there it would require a complete re-write of the internal logic which is not something that normal users would ever need I am afraid. You could of course fork the code, change the Bowtie2 alignment options to `-a`and fix the problems the occur because of this and run this as an extra project that would help you answer your questions!? 

I hope this helps,
Best wishes, Felix

**Comment by xie186** [comment]
Hi Felix, 
Thanks for your help. You mentioned I need a "a different handling logic than what Bismark is currently doing." Could you give me some explanation to help me? I'm going to try to change the options to "-a" and fix the problem. For the detection of the sources of reads, I think maybe I only need part of reads (i.e. 1000 reads) to do the alignment. So I think even it should be fine for such a small dataset. 
Thanks.
Best,
Shaojun

**Comment by FelixKrueger** [comment]
Hmm, it looks like you are serious about it :smh! So are you really only interested in the mapping locations without any methylation specific processing? Is it paired-end or single-end only (which would be much easier)?

If you wanted me to I could potentially have a little go tomorrow to see how difficult it would be to just pass the mapping on to an output file while skipping all the Bismark specific sections... Could you maybe email me a few sample sequences (and mention the genome)? [felix.krueger@babraham.ac.uk]

**Comment by xie186** [comment]
Yes. I'm serious about this :).
I'm only interested in the mapping location. I don't need any methylation specific processing. 
I think single-end first. Even I encounter PE-reads, I can treated as SE reads. 
I'm glad you can help me on this. Thanks. 
Previously I was simulating BS-seq data on Strawberry genome using Sherman, but I got some errors when I tried to do alignments on the simulated reads. So for test, probably we can use data from Arabidopsis which has a small genome. 
Here is the link for the reads: ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByExp/sra/SRX/SRX101/SRX101583/SRR353936/ . 
Here you can get the reference genome:
ftp://ftp.ensemblgenomes.org/pub/plants/release-32/fasta/arabidopsis_thaliana/dna/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa.gz 
Thanks,
Shaojun

**Comment by FelixKrueger** [comment]
Right, I'm getting a test file, got a copy of TAIR10 indexed anyway. Just out of curiosity, which part of simulating with Sherman failed, maybe it needs fixing? (just put it in as an issue over here: https://github.com/FelixKrueger/Sherman).
I'll report back on my progress, Cheers, Felix

**Comment by readbio** [comment]
Thank you so much for kindly help. 
I already posted my problem when using Sherman and Bismark as an issue. 
Best,
Shaojun

**Comment by xie186** [comment]
Thank you so much for kindly help. 
I already posted my problem when using Sherman and Bismark as an issue. 
Best,
Shaojun

**Comment by FelixKrueger** [comment]
Hi Shaun,

I had a go at implementing your multi-mapping request seems to work just fine in the tests I ran. Feel free to clone a copy from https://github.com/FelixKrueger/BismarkMultimappingLocations.

Here is a rough description:

### BismarkMultimappingLocations
This is a side-project of Bismark whose aim is to output multiply mapping read positions without any of the methylation specific features. I have included a new option call `--limit_multimapping` which se
ts the maxiumum number of alignments per thread, so the `--limit 20` would print up to 40 alignments in total, 20 for OT and 20 for OB for a default run. The option `--ambig_bam` is set by default. 

This script is highly experimental and works only for Bowtie2, single-end alignments for which we have set the parameter `-a`. Good luck!


An example USAGE is:

./bismarkMultimappingPositions --genome /bi/scratch/Genomes/Arabidopsis/TAIR10/ test.fq.gz --limit 20
