### ISSUE TITLE
coverage2cytosine error regarding strand of line 1 and line 2

### ISSUE THREAD

**Issue by kdkorthauer** [FelixKrueger/Bismark#89]
Hi Felix,

I'm getting an error when running ```coverage2cytosine --merge_CpG``` on a Bismark coverage file (to collapse over strands).  One example of the error message is:

>The strand of line 1 and line 2 were not + and -:
>line1:	KI270310.1	1201	-	2	0	CG	CGG
>line2:	KI270739.1	7	+	0	0	CG	CGT

Additional information: I am using a reference genome with many unlocalized contigs (human GRCh38), which it seems that Bismark interprets as separate chromosomes (e.g. KI270310.1).  I'm not not sure if the issue is related to these contigs, but I've run several samples and the error message always refers to one of these types of positions (as opposed to positions on a canonical chromosome).

Any insight you can provide into the nature of this error message would be greatly appreciated. 

Best,
Keegan

**Comment by FelixKrueger** [comment]
Hi Keegan,

Would you be able to provide me with on the the offending coverage files and ideally a link to the Genome you are using (e.g. is it the UCSC or Goldenpath one or the Ensembl GRCh38?). I can send you a link to a temporary FTP site if that helps. Just send me an email (felix.krueger@babraham.ac.uk) for the details.

Thanks, Felix

**Comment by kdkorthauer** [comment]
Hi Felix,

Sure thing; I'll shoot you an email shortly regarding file transfer. 

I'm using the Ensembl GRCh38 primary assembly (Homo_sapiens.GRCh38.dna.primary_assembly.fa, specifically from Ensembl Release 85).  Here's a link to the location of that file: [ftp://ftp.ensembl.org/pub/release-85/fasta/homo_sapiens/dna/](ftp://ftp.ensembl.org/pub/release-85/fasta/homo_sapiens/dna/)

Best,
Keegan

**Comment by FelixKrueger** [comment]
Hi Keegan,

Many thanks for providing the example file and the genome build.

I have tracked down this behaviour to chromosomes that end in CG. For these, the top strand information for the second last position was not printed into the CpG report because the tri-nucleotide context cannot be detected. The C at the very last position on the bottom strand was printed into the CpG report however because the tri-nucleotide context could be determined (as it is facing the other way). This would then lead to the error message you saw at transitions of scaffolds. 

I have now addressed this by introducing a length check for the end of chromosomes so that a CG at the very end is ignored for both strands. Could you clone the latest version and see if it also works in your hands? 

Best wishes, Felix

Fixed in f879b2cff602039d596de6e8f6b005065dd9ea12.

**Comment by kdkorthauer** [comment]
Hi Felix,

I cloned the latest version and ```coverage2cytosine  --merge_CpG``` runs successfully now!  Thanks so much for tracking down and fixing the issue so quickly.  Much appreciated!

Best,
Keegan

**Comment by FelixKrueger** [comment]
Thanks for the feedback! Cheers, Felix
