### ISSUE TITLE
Request: Support for bz2 compressed input files

### ISSUE THREAD

**Issue by steveb-cirina** [FelixKrueger/Bismark#95]
Hi

I am using `bismark` for PE alignment and I noticed in the code that it supports gzip compressed input files for mate1 and mate2.  Could support be added for bzip2 compression (and potentially "fqz_comp" compression) ?

I can do a pull request if that would help.  However, I suspect this would be an easy addition.

Thanks,
-Steve

**Comment by FelixKrueger** [comment]
Hi Steve,

If reading from `.bz2` files would only be a matter of changing how the files are read from `gunzip -c $file` to `bunzip2 -c $file` it does indeed sound like a rather trivial thing. 

I suspect however that there might be a number of other issues arising mainly concerning how additional file names are derived (especially with regard to a combination of all sorts of options/temp dirs/output dirs etc.), how files are fed into the alignment threads and the multicore mode... 
So given these potential complications, and the fact that `bzip2` is also a lot slower than `gzip` makes me somewhat reluctant to add this. If you would have a fully tested pull request however... :)

**Comment by steveb-cirina** [comment]
Hi Felix

I am new to doing GitHub PRs, but I have to start somewhere :-)  Do you have any unit or regression tests you run, I didn't see any ?  If not, can you give some guidance on what you would find a good set of tests to best ensure nothing has been broken (I don't want to miss testing any functionality).

**Comment by FelixKrueger** [comment]
I'm afraid I don't (yet) run any automated testing even though I have been thinking about it for a long time. 

For a case like yours I suppose you will have to change how the files are read from for a) the in-silico conversion of the files, b) when the original files are re-read for the alignment/methylation calling process, and possibly c) if and how the files are handed over to the Bowties. Seeing that there can be FastA and FastQ files, SE and PE files, and Bowtie and Bowtie2 alignments there might be a few options. Also the temporary compression option `--gzip` might have to be handled differently.

And finally, you would need to make sure that all file names that are derived from the input files would work with .bz2 instead of .gz (which might be a git of a pain for the multi-core mode...).

The options that traditionally result in a lot of mishaps are `--temp_dir`, `--output_dir`, and when the filenames are given with absolute/relative/no path information and ideally a wild mix of all of them. 

I would totally understand if you would just re-compress your files with `gzip` by the way :P.

**Comment by steveb-cirina** [comment]
I will look closer when I have a few cycles to see what is involved.  As you know, you don't always get the data the way you want, so if it is relatively easy, then it might be worth me making a PR; I was hoping to avoid re-compressing.  It seems bzip2 compresses smaller that gzip, but a slower as you said (In a small test, I did find when using the --best option on both, compression was faster with bzip2, however, it is slower than basic compression).

I will let you know what I find.
