### ISSUE TITLE
Does .cov file include  non-CpG Cs when  --CX not sepecified

### ISSUE THREAD

**Issue by hongenxu** [FelixKrueger/Bismark#99]
Hi Felix,

I want to make sure that .cov file include non-CpG Cs when running bismark_methylation_extractor without specifying --CX. I checked my results, it did include. 

Best regards,
Hongen

**Comment by FelixKrueger** [comment]
If `--CX` is not specified there it is a still possible to get coverage files that seemingly contain non-CGs if there is a deletion in the read right adjacent to the C in question, e.g.:

```
CGTAAT (genomic context)
C-TAAT (read context)
```
In this case the C would be reported as CHH context (because its context changed from CG to CTA). Would this explain what you are seeing?

**Comment by hongenxu** [comment]
Probably I was wrong. I double checked first 1000 positions from .cov file and extracted the sequence context (+_2bp). Most of them have NN**C**GN or NC**G**NN context with a few exceptions (see below) can be explained by your example. If I should include non-CpG in .cov output (working on organisms with unfinished genome, so using --scaffolds), how can I speed up since specifying --CX takes several days with 20 cores for a single sample?  Which step is speed-limiting, .cov generation or bedgraph file sorting? 
Do you have any recommendations ?

```
      1 AAGGG
      1 ACCAG
      1 AGGAA
      5 CAGAA
      3 CAGAG
      2 CAGGA
      3 CAGGG
      1 TTGTT
```

**Comment by FelixKrueger** [comment]
I am not quite sure if you are really interested in non-CG methylation or not? The bedGraph sorting is running on a single core and is using the operating system's sort command, this is certainly the rate limiting step. If you wanted to just use CpG positions then you should run `coverage2cytosine` afterwards; this step is reference sequence-based and should remove all calls that had their context changed due to deletions nearby.

**Comment by hongenxu** [comment]
Hi Felix,
thanks for your reply. I am interested in non-CpG methylation for my research question as suggested in a previous study. I will remove reads mapped to unplaced contigs in BAM file and  avoid to use "--scaffolds".

**Comment by FelixKrueger** [comment]
As long as you don't have more contigs than your operating system can write to this might work. Else I am afraid it will take some time...

**Comment by hongenxu** [comment]
The organism has 31 chromosomes and 3286 unplaced contigs. I will ignore these contigs.
